ROS Motion Planning: rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare > Class Template Reference
rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare > Class Template Reference
Bounded priority queue.
Public Member Functions
BoundedPriorityQueue ()=delete
Construct a new Bounded Priority Queue object.
BoundedPriorityQueue (size_t bound)
Construct a new Bounded Priority Queue object.
void push (const T &val)
Push value.
const T & back () const
Get back value.
const T & operator[] (size_t index) const
Get using index.
size_t size () const
Get size of the queue.
Private Attributes
size_t bound_
std::vector< T > elements_
Detailed Description
template<typename PointT>
template<class T, class Compare = std::less<T>>
class rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >
Bounded priority queue.
Constructor & Destructor Documentation
BoundedPriorityQueue() [1/2]
template<typename PointT > template<class T , class Compare = std::less<T>> rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::BoundedPriorityQueue () delete
Construct a new Bounded Priority Queue object.
BoundedPriorityQueue() [2/2]
template<typename PointT > template<class T , class Compare = std::less<T>> rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::BoundedPriorityQueue (size_t bound) inline
Construct a new Bounded Priority Queue object.
Parameters
bound priority queue size
                                        : bound_(bound)
     {
       elements_.reserve(bound + 1);
     };
References rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::elements_.
Member Function Documentation
back()
template<typename PointT > template<class T , class Compare = std::less<T>> const T& rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::back () const inline
Get back value.
Returns
back value
     {
       return elements_.back();
     };
References rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::elements_.
Referenced by rmp::common::structure::KDTree< PointT >::_knnSearchRecursive().
operator[]()
template<typename PointT > template<class T , class Compare = std::less<T>> const T& rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::operator[] (size_t index) const inline
Get using index.
Parameters
index index to get
Returns
element with index
     {
       return elements_[index];
     }
References rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::elements_.
push()
template<typename PointT > template<class T , class Compare = std::less<T>> void rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::push (const T & val) inline
Push value.
Parameters
val the new element to push in priority queue size
     {
       auto it = std::find_if(std::begin(elements_), std::end(elements_),
                              [&](const T& element) { return Compare()(val, element); });
       elements_.insert(it, val);
       if (elements_.size() >> bound_)
         elements_.resize(bound_);
     }
References rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::bound_, and rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::elements_.
Referenced by rmp::common::structure::KDTree< PointT >::_knnSearchRecursive().
size()
template<typename PointT > template<class T , class Compare = std::less<T>> size_t rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::size () const inline
Get size of the queue.
Returns
size of the queue
     {
       return elements_.size();
     }
References rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::elements_.
Referenced by rmp::common::structure::KDTree< PointT >::_knnSearchRecursive(), and rmp::common::structure::KDTree< PointT >::knnSearch().
Member Data Documentation
bound_
template<typename PointT > template<class T , class Compare = std::less<T>> size_t rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::bound_ private
Referenced by rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::push().
elements_
template<typename PointT > template<class T , class Compare = std::less<T>> std::vector<T> rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::elements_ private
Referenced by rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::back(), rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::BoundedPriorityQueue(), rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::operator[](), rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::push(), and rmp::common::structure::KDTree< PointT >::BoundedPriorityQueue< T, Compare >::size().
The documentation for this class was generated from the following file:
src/core/common/include/common/structure/kd_tree.h