ROS Motion Planning: rmp::path_planner::PSOPathPlanner Class Reference
rmp::path_planner::PSOPathPlanner Class Reference
Class for objects that plan using the PSO algorithm.
#include <pso_planner.h>
Classes
struct Particle
Public Types
enum GEN_MODE { RANDOM = 1, CIRCLE = 2 }
Public Types inherited from rmp::path_planner::PathPlanner
using Point2d = rmp::common::geometry::Point2d
using Point3d = rmp::common::geometry::Point3d
using Points2d = rmp::common::geometry::Points2d
using Points3d = rmp::common::geometry::Points3d
Public Member Functions
PSOPathPlanner (costmap_2d::Costmap2DROS *costmap_ros, int n_particles, int n_inherited, int point_num, double w_inertial, double w_social, double w_cognitive, double max_speed, int init_mode, int max_iter)
Construct a new PSO object.
~PSOPathPlanner ()
bool plan (const Point3d &start, const Point3d &goal, Points3d &path, Points3d &expand)
PSO implementation.
void initializePositions (PositionSequence &initial_positions, const Point2d &start, const Point2d &goal, int gen_mode=GEN_MODE::CIRCLE)
Generate n particles with pointNum_ positions each within the map range.
double calFitnessValue (const Points2d &position)
Calculate the value of fitness function.
void updateParticleVelocity (Particle &particle, const Particle &global_best, std::mt19937 &gen)
A function to update the particle velocity.
void updateParticlePosition (Particle &particle)
A function to update the particle position.
void optimizeParticle (Particle &particle, Particle &best_particle, std::mt19937 &gen, Points3d &expand)
Particle update optimization iteration.
Public Member Functions inherited from rmp::path_planner::PathPlanner
PathPlanner (costmap_2d::Costmap2DROS *costmap_ros)
Construct a new Global PathPlanner object.
virtual ~PathPlanner ()=default
Destroy the Global PathPlanner object.
void setFactor (float factor)
Set or reset obstacle factor.
costmap_2d::Costmap2D * getCostMap () const
get the costmap
int getMapSize () const
get the size of costmap
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap ()
Inflate the boundary of costmap into obstacles to prevent cross planning.
Protected Attributes
int max_iter_
int n_particles_
int n_inherited_
int point_num_
double w_inertial_
double w_social_
double w_cognitive_
double max_speed_
int init_mode_
Point2d start_
Point2d goal_
Protected Attributes inherited from rmp::path_planner::PathPlanner
int map_size_
float factor_
costmap_2d::Costmap2DROS * costmap_ros_
costmap_2d::Costmap2D * costmap_
Private Types
using PositionSequence = std::vector< Points2d >
Private Attributes
std::mutex mutex_
std::vector< Particle > inherited_particles_
std::unique_ptr< rmp::common::geometry::BSplineCurve > bspline_gen_
Additional Inherited Members
Protected Member Functions inherited from rmp::path_planner::PathPlanner
template<typename Node >
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
template<typename Node >
std::vector< Node > _convertBiClosedListToPath (std::unordered_map< int, Node > &f_closed_list, std::unordered_map< int, Node > &b_closed_list, const Node &start, const Node &goal, const Node &boundary)
Detailed Description
Class for objects that plan using the PSO algorithm.
Member Typedef Documentation
PositionSequence
using rmp::path_planner::PSOPathPlanner::PositionSequence = std::vector<Points2d> private
Member Enumeration Documentation
GEN_MODE
enum rmp::path_planner::PSOPathPlanner::GEN_MODE
Enumerator
RANDOM
CIRCLE
   {
     RANDOM = 1,
     CIRCLE = 2,
   };
Constructor & Destructor Documentation
PSOPathPlanner()
rmp::path_planner::PSOPathPlanner::PSOPathPlanner (costmap_2d::Costmap2DROS * costmap_ros, int n_particles, int n_inherited, int point_num, double w_inertial, double w_social, double w_cognitive, double max_speed, int init_mode, int max_iter)
Construct a new PSO object.
Parameters
costmap the environment for path planning
n_particles number of particles
n_inherited number of inherited particles
point_num number of position points contained in each particle
w_inertial inertia weight
w_social social weight
w_cognitive cognitive weight
max_speed The maximum movement speed of particles
init_mode Set the generation mode for the initial position points of the particle swarm
max_iter maximum iterations
   : PathPlanner(costmap_ros)
   , n_particles_(n_particles)
   , n_inherited_(n_inherited)
   , point_num_(point_num)
   , w_inertial_(w_inertial)
   , w_social_(w_social)
   , w_cognitive_(w_cognitive)
   , max_speed_(max_speed)
   , init_mode_(init_mode)
   , max_iter_(max_iter)
 {
   bspline_gen_ = std::make_unique<rmp::common::geometry::BSplineCurve>();
   inherited_particles_.emplace_back(Points2d(point_num), Points2d(point_num), 0.0);
 }
References bspline_gen_, and inherited_particles_.
~PSOPathPlanner()
rmp::path_planner::PSOPathPlanner::~PSOPathPlanner ()
 {
 }
Member Function Documentation
calFitnessValue()
double rmp::path_planner::PSOPathPlanner::calFitnessValue (const Points2d & position)
Calculate the value of fitness function.
Parameters
position the control points calculated by PSO
Returns
fitness the value of fitness function
 {
   Points2d points, b_path;
   points.push_back(start_);
   for (const auto& pos : position)
     points.emplace_back(pos.x(), pos.y());
   points.push_back(goal_);
   points.erase(std::unique(std::begin(points), std::end(points)), std::end(points));
   bspline_gen_->run(points, b_path);
   // collision detection
   int point_index;
   double obs_cost = 1;
   for (size_t i = 1; i < b_path.size(); ++i)
   {
     point_index = grid2Index(static_cast<int>(b_path[i].x()), static_cast<int>(b_path[i].y()));
     // next node hit the boundary or obstacle
     if ((point_index < 0) || (point_index >= map_size_) ||
         (costmap_->getCharMap()[point_index] >= costmap_2d::LETHAL_OBSTACLE * factor_))
       obs_cost++;
   }
   // Calculate particle fitness
   return 100000.0 / (bspline_gen_->len(b_path) + 1000 * obs_cost);
 }
References bspline_gen_, rmp::path_planner::PathPlanner::costmap_, rmp::path_planner::PathPlanner::factor_, goal_, rmp::path_planner::PathPlanner::grid2Index(), rmp::path_planner::PathPlanner::map_size_, start_, FakeAMCL::x, and FakeAMCL::y.
Referenced by optimizeParticle(), and plan().
initializePositions()
void rmp::path_planner::PSOPathPlanner::initializePositions (PositionSequence & initial_positions, const Point2d & start, const Point2d & goal, int gen_mode = GEN_MODE::CIRCLE)
Generate n particles with pointNum_ positions each within the map range.
Parameters
initial_positions The initial position sequence of particle swarm
start start node
goal goal node
gen_mode generation mode
 {
   // Use a random device and engine to generate random numbers
   std::random_device rd;
   std::mt19937 gen(rd());
   int x[point_num_], y[point_num_];
   int point_id, pos_id;
   // Calculate sequence direction
   bool x_order = (goal.x() > start.x());
   bool y_order = (goal.y() > start.y());
   // circle generation
   int center_x, center_y;
   double radius;
   if (gen_mode == GEN_MODE::CIRCLE)
   {
     // Calculate the center and the radius of the circle (midpoint between start and goal)
     center_x = (start.x() + goal.x()) / 2;
     center_y = (start.y() + goal.y()) / 2;
     double dist = 0.5 * std::hypot(start.x() - goal.x(), start.y() - goal.y());
     radius = dist < 5 ? 5 : dist;
   }
   // initialize n_particles positions
   for (int i = 0; i < n_particles_; ++i)
   {
     point_id = 0;
     Points2d particle_positions;
     std::unordered_set<int> visited;
     // Generate point_num_ unique coordinates
     while (point_id < point_num_)
     {
       if (gen_mode == GEN_MODE::RANDOM)
       {
         x[point_id] = std::uniform_int_distribution<int>(0, costmap_->getSizeInCellsX() - 1)(gen);
         y[point_id] = std::uniform_int_distribution<int>(0, costmap_->getSizeInCellsY() - 1)(gen);
         pos_id = grid2Index(x[point_id], y[point_id]);
       }
       else
       {
         // Generate random angle in radians
         double angle = std::uniform_real_distribution<double>(0, 2 * M_PI)(gen);
         // Generate random distance from the center within the circle
         double r = std::sqrt(std::uniform_real_distribution<double>(0, 1)(gen)) * radius;
         // Convert polar coordinates to Cartesian coordinates
         x[point_id] = static_cast<int>(std::round(center_x + r * std::cos(angle)));
         y[point_id] = static_cast<int>(std::round(center_y + r * std::sin(angle)));
         // Check if the coordinates are within the map range
         if (x[point_id] >= 0 && x[point_id] < costmap_->getSizeInCellsX() && y[point_id] >= 0 &&
             y[point_id] < costmap_->getSizeInCellsY())
           pos_id = grid2Index(x[point_id], y[point_id]);
         else
           continue;
       }
       // Check if the coordinates have already been used
       if (visited.find(pos_id) == visited.end())
       {
         point_id++;
         visited.insert(pos_id);
       }
     }
     // sort
     if (x_order)
       std::sort(x, x + point_num_, [](int a, int b) { return a < b; });
     else
       std::sort(x, x + point_num_, [](int a, int b) { return a > b; });
     if (y_order)
       std::sort(y, y + point_num_, [](int a, int b) { return a < b; });
     else
       std::sort(y, y + point_num_, [](int a, int b) { return a > b; });
     // Store elements from x and y in particle_positions
     for (int j = 0; j < point_num_; ++j)
       particle_positions.emplace_back(x[j], y[j]);
     initial_positions.push_back(particle_positions);
   }
 }
References key_ctrl::a, OkayPlan_main::b, rmp::path_planner::PathPlanner::costmap_, rmp::path_planner::PathPlanner::grid2Index(), n_particles_, point_num_, rviz_generate::r, FakeAMCL::x, rmp::common::geometry::Point2_< T >::x(), FakeAMCL::y, and rmp::common::geometry::Point2_< T >::y().
Referenced by plan().
optimizeParticle()
void rmp::path_planner::PSOPathPlanner::optimizeParticle (Particle & particle, Particle & best_particle, std::mt19937 & gen, Points3d & expand)
Particle update optimization iteration.
Parameters
particle Particles to be updated for velocity
best_particle Global optimal particle
gen randomizer
expand containing the node been search during the process
 {
   // update speed
   updateParticleVelocity(particle, best_particle, gen);
   // update position
   updateParticlePosition(particle);
   // Calculate fitness
   particle.fitness = calFitnessValue(particle.position);
   // Update individual optima
   if (particle.fitness > particle.best_fitness)
   {
     particle.best_fitness = particle.fitness;
     particle.best_pos = particle.position;
   }
   // Update expand points
   std::lock_guard<std::mutex> lock(mutex_);
   for (auto pos : particle.position)
     expand.emplace_back(pos.x(), pos.y());
   if (particle.best_fitness > best_particle.fitness)
   {
     best_particle.fitness = particle.best_fitness;
     best_particle.position = particle.position;
   }
 }
References rmp::path_planner::PSOPathPlanner::Particle::best_fitness, rmp::path_planner::PSOPathPlanner::Particle::best_pos, calFitnessValue(), rmp::path_planner::PSOPathPlanner::Particle::fitness, mutex_, rmp::path_planner::PSOPathPlanner::Particle::position, updateParticlePosition(), and updateParticleVelocity().
Referenced by plan().
plan()
bool rmp::path_planner::PSOPathPlanner::plan (const Point3d & start, const Point3d & goal, Points3d & path, Points3d & expand) virtual
PSO implementation.
Parameters
start start node
goal goal node
path optimal path consists of Node
expand containing the node been search during the process
Returns
true if path found, else false
Parameters
start start node
goal goal node
path optimal path consists of Node
expand containing the node been search during the process(unused)
Returns
true if path found, else false
Implements rmp::path_planner::PathPlanner.
 {
   start_.setX(start.x());
   start_.setY(start.y());
   goal_.setX(goal.x());
   goal_.setY(goal.y());
   expand.clear();
   // variable initialization
   double init_fitness;
   Particle best_particle;
   PositionSequence init_positions;
   std::vector<Particle> particles;
   // Generate initial position of particle swarm
   initializePositions(init_positions, start_, goal_, init_mode_);
   // Particle initialization
   for (int i = 0; i < n_particles_; ++i)
   {
     Points2d init_position;
     if ((i < n_inherited_) && (inherited_particles_.size() == n_inherited_))
       init_position = inherited_particles_[i].best_pos;
     else
       init_position = init_positions[i];
     Points2d init_velocity(point_num_);
     // Calculate fitness
     init_fitness = calFitnessValue(init_position);
     if ((i == 0) || (init_fitness > best_particle.fitness))
     {
       best_particle.fitness = init_fitness;
       best_particle.position = init_position;
     }
     // Create and add particle objects to containers
     particles.emplace_back(init_position, init_velocity, init_fitness);
   }
   // random data
   std::random_device rd;
   std::mt19937 gen(rd());
   // Iterative optimization
   for (size_t iter = 0; iter < max_iter_; iter++)
   {
     std::vector<std::thread> particle_list = std::vector<std::thread>(n_particles_);
     for (size_t i = 0; i < n_particles_; ++i)
       particle_list[i] = std::thread(&PSOPathPlanner::optimizeParticle, this, std::ref(particles[i]),
                                      std::ref(best_particle), std::ref(gen), std::ref(expand));
     for (size_t i = 0; i < n_particles_; ++i)
       particle_list[i].join();
   }
   // Generating Paths from Optimal Particles
   Points2d points, b_path;
   points.emplace_back(start.x(), start.y());
   for (const auto& pos : best_particle.position)
     points.emplace_back(pos.x(), pos.y());
   points.emplace_back(goal.x(), goal.y());
   points.erase(std::unique(std::begin(points), std::end(points)), std::end(points));
   bspline_gen_->run(points, b_path);
   // Path data structure conversion
   path.clear();
   for (const auto& pt : b_path)
   {
     path.emplace_back(pt.x(), pt.y());
   }
   // Update inheritance particles based on optimal fitness
   std::sort(particles.begin(), particles.end(),
             [](const Particle& a, const Particle& b) { return a.best_fitness > b.best_fitness; });
   inherited_particles_.clear();
   for (size_t inherit = 0; inherit < n_inherited_; ++inherit)
     inherited_particles_.emplace_back(particles[inherit]);
   return !path.empty();
 }
References key_ctrl::a, OkayPlan_main::b, bspline_gen_, calFitnessValue(), rmp::path_planner::PSOPathPlanner::Particle::fitness, goal_, inherited_particles_, init_mode_, initializePositions(), max_iter_, n_inherited_, n_particles_, optimizeParticle(), point_num_, rmp::path_planner::PSOPathPlanner::Particle::position, rmp::common::geometry::Point2_< T >::setX(), rmp::common::geometry::Point2_< T >::setY(), start_, rmp::common::geometry::Point3_< T >::x(), and rmp::common::geometry::Point3_< T >::y().
updateParticlePosition()
void rmp::path_planner::PSOPathPlanner::updateParticlePosition (Particle & particle)
A function to update the particle position.
Parameters
particle Particles to be updated for velocity
 {
   // update Position
   for (size_t i = 0; i < point_num_; ++i)
   {
     particle.position[i].setX(particle.position[i].x() + particle.velocity[i].x());
     particle.position[i].setY(particle.position[i].y() + particle.velocity[i].y());
     // Position limit
     particle.position[i].setX(
         rmp::common::math::clamp(particle.position[i].x(), 1.0, static_cast<double>(costmap_->getSizeInCellsX()) - 1));
     particle.position[i].setY(
         rmp::common::math::clamp(particle.position[i].y(), 1.0, static_cast<double>(costmap_->getSizeInCellsY()) - 1));
   }
 }
References rmp::common::math::clamp(), rmp::path_planner::PathPlanner::costmap_, point_num_, rmp::path_planner::PSOPathPlanner::Particle::position, and rmp::path_planner::PSOPathPlanner::Particle::velocity.
Referenced by optimizeParticle().
updateParticleVelocity()
void rmp::path_planner::PSOPathPlanner::updateParticleVelocity (Particle & particle, const Particle & global_best, std::mt19937 & gen)
A function to update the particle velocity.
Parameters
particle Particles to be updated for velocity
global_best Global optimal particle
gen randomizer
 {
   // The random numbers are distributed between [0, 1).
   std::uniform_real_distribution<double> dist(0.0, 1.0);
   // update Velocity
   for (size_t i = 0; i < point_num_; ++i)
   {
     double rand1 = dist(gen);
     double rand2 = dist(gen);
     particle.velocity[i].setX(w_inertial_ * particle.velocity[i].x() +
                               w_social_ * rand1 * (particle.best_pos[i].x() - particle.position[i].x()) +
                               w_cognitive_ * rand2 * (global_best.position[i].x() - particle.position[i].x()));
     particle.velocity[i].setY(w_inertial_ * particle.velocity[i].y() +
                               w_social_ * rand1 * (particle.best_pos[i].y() - particle.position[i].y()) +
                               w_cognitive_ * rand2 * (global_best.position[i].y() - particle.position[i].y()));
     // Velocity limit
     particle.velocity[i].setX(rmp::common::math::clamp(particle.velocity[i].x(), -1.0 * max_speed_, max_speed_));
     particle.velocity[i].setY(rmp::common::math::clamp(particle.velocity[i].y(), -1.0 * max_speed_, max_speed_));
   }
 }
References rmp::path_planner::PSOPathPlanner::Particle::best_pos, rmp::common::math::clamp(), max_speed_, point_num_, rmp::path_planner::PSOPathPlanner::Particle::position, rmp::path_planner::PSOPathPlanner::Particle::velocity, w_cognitive_, w_inertial_, and w_social_.
Referenced by optimizeParticle().
Member Data Documentation
bspline_gen_
std::unique_ptr<rmp::common::geometry::BSplineCurve> rmp::path_planner::PSOPathPlanner::bspline_gen_ private
Referenced by calFitnessValue(), plan(), and PSOPathPlanner().
goal_
Point2d rmp::path_planner::PSOPathPlanner::goal_ protected
Referenced by calFitnessValue(), and plan().
inherited_particles_
std::vector<Particle> rmp::path_planner::PSOPathPlanner::inherited_particles_ private
Referenced by plan(), and PSOPathPlanner().
init_mode_
int rmp::path_planner::PSOPathPlanner::init_mode_ protected
Referenced by plan().
max_iter_
int rmp::path_planner::PSOPathPlanner::max_iter_ protected
Referenced by plan().
max_speed_
double rmp::path_planner::PSOPathPlanner::max_speed_ protected
Referenced by updateParticleVelocity().
mutex_
std::mutex rmp::path_planner::PSOPathPlanner::mutex_ private
Referenced by optimizeParticle().
n_inherited_
int rmp::path_planner::PSOPathPlanner::n_inherited_ protected
Referenced by plan().
n_particles_
int rmp::path_planner::PSOPathPlanner::n_particles_ protected
Referenced by initializePositions(), and plan().
point_num_
int rmp::path_planner::PSOPathPlanner::point_num_ protected
Referenced by initializePositions(), plan(), updateParticlePosition(), and updateParticleVelocity().
start_
Point2d rmp::path_planner::PSOPathPlanner::start_ protected
Referenced by calFitnessValue(), and plan().
w_cognitive_
double rmp::path_planner::PSOPathPlanner::w_cognitive_ protected
Referenced by updateParticleVelocity().
w_inertial_
double rmp::path_planner::PSOPathPlanner::w_inertial_ protected
Referenced by updateParticleVelocity().
w_social_
double rmp::path_planner::PSOPathPlanner::w_social_ protected
Referenced by updateParticleVelocity().
The documentation for this class was generated from the following files:
src/core/path_planner/path_planner/include/path_planner/evolutionary_planner/pso_planner.h
src/core/path_planner/path_planner/src/evolutionary_planner/pso_planner.cpp