ROS Motion Planning: rmp::path_planner::DStarLitePathPlanner::LNode Class Reference
rmp::path_planner::DStarLitePathPlanner::LNode Class Reference
Public Member Functions
LNode (const int x=0, const int y=0, const double g=std::numeric_limits< double >::max(), const double h=std::numeric_limits< double >::max(), const int id=0, const int pid=-1, const double rhs=std::numeric_limits< double >::max(), const double key=std::numeric_limits< double >::max())
Construct a new LNode object.
double rhs () const
double key () const
const std::multimap< double, LNode * >::iterator & iter () const
void setRhs (double rhs)
void setKey (double key)
void setIterator (std::multimap< double, LNode * >::iterator iter)
Public Member Functions inherited from rmp::common::structure::Node< int >
Node (int x=0, int y=0, double g=0.0, double h=0.0, int id=0, int pid=0)
Constructor for Node class.
Node (const Node &n)
int x () const
get the property of node
int y () const
double g () const
double h () const
int id () const
int pid () const
void set_x (int x)
set the property of node
void set_y (int y)
void set_g (double g)
void set_h (double h)
void set_id (int id)
void set_pid (int pid)
Node operator+ (const Node &n) const
Overloading operator + for Node class.
Node operator- (const Node &n) const
Overloading operator - for Node class.
bool operator== (const Node &n) const
Overloading operator == for Node class.
bool operator!= (const Node &n) const
Overloading operator != for Node class.
Private Attributes
double rhs_
double key_
std::multimap< double, LNode * >::iterator open_it_
Additional Inherited Members
Protected Attributes inherited from rmp::common::structure::Node< int >
int x_
int y_
double g_
double h_
int id_
int pid_
Constructor & Destructor Documentation
LNode()
rmp::path_planner::DStarLitePathPlanner::LNode::LNode (const int x = 0, const int y = 0, const double g = std::numeric_limits<double>::max(), const double h = std::numeric_limits<double>::max(), const int id = 0, const int pid = -1, const double rhs = std::numeric_limits<double>::max(), const double key = std::numeric_limits<double>::max()) inline
Construct a new LNode object.
Parameters
x X value
y Y value
g Cost to get to this node
h Heuritic cost of this node
id Node's id
pid Node's parent's id
rhs Node's right hand side
key Node's key value
       : Node(x, y, g, h, id, pid), rhs_(rhs), key_(key)
     {
     }
Member Function Documentation
iter()
const std::multimap<double, LNode*>::iterator& rmp::path_planner::DStarLitePathPlanner::LNode::iter () const inline
     {
       return open_it_;
     }
References open_it_.
Referenced by setIterator(), and rmp::path_planner::DStarLitePathPlanner::updateVertex().
key()
double rmp::path_planner::DStarLitePathPlanner::LNode::key () const inline
     {
       return key_;
     }
References key_.
Referenced by rmp::path_planner::DStarLitePathPlanner::computeShortestPath(), rmp::path_planner::DStarLitePathPlanner::plan(), setKey(), and rmp::path_planner::DStarLitePathPlanner::updateVertex().
rhs()
double rmp::path_planner::DStarLitePathPlanner::LNode::rhs () const inline
     {
       return rhs_;
     }
References rhs_.
Referenced by rmp::path_planner::DStarLitePathPlanner::computeShortestPath(), setRhs(), and rmp::path_planner::DStarLitePathPlanner::updateVertex().
setIterator()
void rmp::path_planner::DStarLitePathPlanner::LNode::setIterator (std::multimap< double, LNode * >::iterator iter) inline
     {
       open_it_ = iter;
     }
References iter(), and open_it_.
Referenced by rmp::path_planner::DStarLitePathPlanner::computeShortestPath(), rmp::path_planner::DStarLitePathPlanner::initMap(), rmp::path_planner::DStarLitePathPlanner::plan(), and rmp::path_planner::DStarLitePathPlanner::updateVertex().
setKey()
void rmp::path_planner::DStarLitePathPlanner::LNode::setKey (double key) inline
     {
       key_ = key;
     }
References key(), and key_.
Referenced by rmp::path_planner::DStarLitePathPlanner::computeShortestPath(), rmp::path_planner::DStarLitePathPlanner::plan(), and rmp::path_planner::DStarLitePathPlanner::updateVertex().
setRhs()
void rmp::path_planner::DStarLitePathPlanner::LNode::setRhs (double rhs) inline
     {
       rhs_ = rhs;
     }
References rhs(), and rhs_.
Referenced by rmp::path_planner::DStarLitePathPlanner::plan(), and rmp::path_planner::DStarLitePathPlanner::updateVertex().
Member Data Documentation
key_
double rmp::path_planner::DStarLitePathPlanner::LNode::key_ private
Referenced by key(), and setKey().
open_it_
std::multimap<double, LNode*>::iterator rmp::path_planner::DStarLitePathPlanner::LNode::open_it_ private
Referenced by iter(), and setIterator().
rhs_
double rmp::path_planner::DStarLitePathPlanner::LNode::rhs_ private
Referenced by rhs(), and setRhs().
The documentation for this class was generated from the following file:
src/core/path_planner/path_planner/include/path_planner/graph_planner/dstar_lite_planner.h