ROS Motion Planning: rmp::controller::DWAController Class Reference
rmp::controller::DWAController Class Reference
A class implementing a local planner using the Dynamic Window Approach.
#include <dwa_controller.h>
Public Member Functions
DWAController ()
Constructor for DWAControllerROS wrapper.
void initialize (std::string name, tf2_ros::Buffer *tf, costmap_2d::Costmap2DROS *costmap_ros)
Constructs the ros wrapper.
~DWAController ()
Destructor for the wrapper.
bool computeVelocityCommands (geometry_msgs::Twist &cmd_vel)
Given the current position, orientation, and velocity of the robot, compute velocity commands to send to the base.
bool dwaComputeVelocityCommands (geometry_msgs::PoseStamped &global_pose, geometry_msgs::Twist &cmd_vel)
Given the current position, orientation, and velocity of the robot, compute velocity commands to send to the base, using dynamic window approach.
bool setPlan (const std::vector< geometry_msgs::PoseStamped > &orig_global_plan)
Set the plan that the controller is following.
bool isGoalReached ()
Check if the goal pose has been achieved.
bool isInitialized ()
Private Member Functions
void reconfigureCB (dwa_controller::DWAControllerConfig &config, uint32_t level)
Callback to update the local planner's parameters based on dynamic reconfigure.
void publishLocalPlan (std::vector< geometry_msgs::PoseStamped > &path)
void publishGlobalPlan (std::vector< geometry_msgs::PoseStamped > &path)
Private Attributes
tf2_ros::Buffer * tf_
Used for transforming point clouds.
ros::Publisher g_plan_pub_
ros::Publisher l_plan_pub_
base_local_planner::LocalPlannerUtil planner_util_
boost::shared_ptr< DWA > dp_
The trajectory controller.
costmap_2d::Costmap2DROS * costmap_ros_
dynamic_reconfigure::Server< dwa_controller::DWAControllerConfig > * dsrv_
dwa_controller::DWAControllerConfig default_config_
bool setup_
geometry_msgs::PoseStamped current_pose_
base_local_planner::LatchedStopRotateController latchedStopRotateController_
bool initialized_
base_local_planner::OdometryHelperRos odom_helper_
std::string odom_topic_
Detailed Description
A class implementing a local planner using the Dynamic Window Approach.
Constructor & Destructor Documentation
DWAController()
rmp::controller::DWAController::DWAController ()
Constructor for DWAControllerROS wrapper.
                              : initialized_(false), odom_helper_("odom"), setup_(false)
 {
 }
~DWAController()
rmp::controller::DWAController::~DWAController ()
Destructor for the wrapper.
 {
   // make sure to clean things up
   delete dsrv_;
 }
References dsrv_.
Member Function Documentation
computeVelocityCommands()
bool rmp::controller::DWAController::computeVelocityCommands (geometry_msgs::Twist & cmd_vel)
Given the current position, orientation, and velocity of the robot, compute velocity commands to send to the base.
Parameters
cmd_vel Will be filled with the velocity command to be passed to the robot base
Returns
True if a valid trajectory was found, false otherwise
 {
   // dispatches to either dwa sampling control or stop and rotate control, depending on whether we have been close
   // enough to goal
   if (!costmap_ros_->getRobotPose(current_pose_))
   {
     ROS_ERROR("Could not get robot pose");
     return false;
   }
   std::vector<geometry_msgs::PoseStamped> transformed_plan;
   if (!planner_util_.getLocalPlan(current_pose_, transformed_plan))
   {
     ROS_ERROR("Could not get local plan");
     return false;
   }
   // if the global plan passed in is empty... we won't do anything
   if (transformed_plan.empty())
   {
     ROS_WARN_NAMED("dwa_local_planner", "Received an empty transformed plan.");
     return false;
   }
   ROS_DEBUG_NAMED("dwa_local_planner", "Received a transformed plan with %zu points.", transformed_plan.size());
   // update plan in dwa_planner even if we just stop and rotate, to allow checkTrajectory
   dp_->updatePlanAndLocalCosts(current_pose_, transformed_plan, costmap_ros_->getRobotFootprint());
   if (latchedStopRotateController_.isPositionReached(&planner_util_, current_pose_))
   {
     // publish an empty plan because we've reached our goal position
     std::vector<geometry_msgs::PoseStamped> local_plan;
     std::vector<geometry_msgs::PoseStamped> transformed_plan;
     publishGlobalPlan(transformed_plan);
     publishLocalPlan(local_plan);
     base_local_planner::LocalPlannerLimits limits = planner_util_.getCurrentLimits();
     return latchedStopRotateController_.computeVelocityCommandsStopRotate(
         cmd_vel, limits.getAccLimits(), dp_->getSimPeriod(), &planner_util_, odom_helper_, current_pose_,
         boost::bind(&DWA::checkTrajectory, dp_, _1, _2, _3));
   }
   else
   {
     bool isOk = dwaComputeVelocityCommands(current_pose_, cmd_vel);
     if (isOk)
     {
       publishGlobalPlan(transformed_plan);
     }
     else
     {
       ROS_WARN_NAMED("dwa_local_planner", "DWA planner failed to produce path.");
       std::vector<geometry_msgs::PoseStamped> empty_plan;
       publishGlobalPlan(empty_plan);
     }
     return isOk;
   }
 }
References rmp::controller::DWA::checkTrajectory(), costmap_ros_, current_pose_, dp_, dwaComputeVelocityCommands(), latchedStopRotateController_, odom_helper_, planner_util_, publishGlobalPlan(), and publishLocalPlan().
dwaComputeVelocityCommands()
bool rmp::controller::DWAController::dwaComputeVelocityCommands (geometry_msgs::PoseStamped & global_pose, geometry_msgs::Twist & cmd_vel)
Given the current position, orientation, and velocity of the robot, compute velocity commands to send to the base, using dynamic window approach.
Parameters
cmd_vel Will be filled with the velocity command to be passed to the robot base
Returns
True if a valid trajectory was found, false otherwise
 {
   // dynamic window sampling approach to get useful velocity commands
   if (!isInitialized())
   {
     ROS_ERROR("This planner has not been initialized, please call initialize() before using this planner");
     return false;
   }
   geometry_msgs::PoseStamped robot_vel;
   odom_helper_.getRobotVel(robot_vel);
   /* For timing uncomment
   struct timeval start, end;
   double start_t, end_t, t_diff;
   gettimeofday(&start, NULL);
   */
   // compute what trajectory to drive along
   geometry_msgs::PoseStamped drive_cmds;
   drive_cmds.header.frame_id = costmap_ros_->getBaseFrameID();
   // call with updated footprint
   base_local_planner::Trajectory path = dp_->findBestPath(global_pose, robot_vel, drive_cmds);
   // ROS_ERROR("Best: %.2f, %.2f, %.2f, %.2f", path.xv_, path.yv_, path.thetav_, path.cost_);
   /* For timing uncomment
   gettimeofday(&end, NULL);
   start_t = start.tv_sec + double(start.tv_usec) / 1e6;
   end_t = end.tv_sec + double(end.tv_usec) / 1e6;
   t_diff = end_t - start_t;
   ROS_INFO("Cycle time: %.9f", t_diff);
   */
   // pass along drive commands
   cmd_vel.linear.x = drive_cmds.pose.position.x;
   cmd_vel.linear.y = drive_cmds.pose.position.y;
   cmd_vel.angular.z = tf2::getYaw(drive_cmds.pose.orientation);
   // if we cannot move... tell someone
   std::vector<geometry_msgs::PoseStamped> local_plan;
   if (path.cost_ < 0)
   {
     ROS_DEBUG_NAMED("dwa_local_planner",
                     "The dwa local planner failed to find a valid plan, cost functions discarded all candidates. This "
                     "can mean there is an obstacle too close to the robot.");
     local_plan.clear();
     publishLocalPlan(local_plan);
     return false;
   }
   ROS_DEBUG_NAMED("dwa_local_planner", "A valid velocity command of (%.2f, %.2f, %.2f) was found for this cycle.",
                   cmd_vel.linear.x, cmd_vel.linear.y, cmd_vel.angular.z);
   // Fill out the local plan
   for (unsigned int i = 0; i < path.getPointsSize(); ++i)
   {
     double p_x, p_y, p_th;
     path.getPoint(i, p_x, p_y, p_th);
     geometry_msgs::PoseStamped p;
     p.header.frame_id = costmap_ros_->getGlobalFrameID();
     p.header.stamp = ros::Time::now();
     p.pose.position.x = p_x;
     p.pose.position.y = p_y;
     p.pose.position.z = 0.0;
     tf2::Quaternion q;
     q.setRPY(0, 0, p_th);
     tf2::convert(q, p.pose.orientation);
     local_plan.push_back(p);
   }
   // publish information to the visualizer
   publishLocalPlan(local_plan);
   return true;
 }
References costmap_ros_, dp_, isInitialized(), odom_helper_, and publishLocalPlan().
Referenced by computeVelocityCommands().
initialize()
void rmp::controller::DWAController::initialize (std::string name, tf2_ros::Buffer * tf, costmap_2d::Costmap2DROS * costmap_ros)
Constructs the ros wrapper.
Parameters
name The name to give this instance of the trajectory planner
tf A pointer to a transform listener
costmap The cost map to use for assigning costs to trajectories
 {
   if (!isInitialized())
   {
     ros::NodeHandle private_nh("~/" + name);
     g_plan_pub_ = private_nh.advertise<nav_msgs::Path>("global_plan", 1);
     l_plan_pub_ = private_nh.advertise<nav_msgs::Path>("local_plan", 1);
     tf_ = tf;
     costmap_ros_ = costmap_ros;
     costmap_ros_->getRobotPose(current_pose_);
     // make sure to update the costmap we'll use for this cycle
     costmap_2d::Costmap2D* costmap = costmap_ros_->getCostmap();
     planner_util_.initialize(tf, costmap, costmap_ros_->getGlobalFrameID());
     // create the actual planner that we'll use.. it'll configure itself from the parameter server
     dp_ = boost::shared_ptr<DWA>(new DWA(name, &planner_util_));
     if (private_nh.getParam("odom_topic", odom_topic_))
     {
       odom_helper_.setOdomTopic(odom_topic_);
     }
     initialized_ = true;
     ROS_INFO("Using local controller: %s", name.c_str());
     dsrv_ = new dynamic_reconfigure::Server<dwa_controller::DWAControllerConfig>(private_nh);
     dynamic_reconfigure::Server<dwa_controller::DWAControllerConfig>::CallbackType cb =
         boost::bind(&DWAController::reconfigureCB, this, _1, _2);
     dsrv_->setCallback(cb);
   }
   else
   {
     ROS_WARN("This planner has already been initialized, doing nothing.");
   }
 }
References costmap_ros_, current_pose_, dp_, dsrv_, g_plan_pub_, initialized_, isInitialized(), l_plan_pub_, rviz_generate::name, odom_helper_, odom_topic_, planner_util_, reconfigureCB(), and tf_.
isGoalReached()
bool rmp::controller::DWAController::isGoalReached ()
Check if the goal pose has been achieved.
Returns
True if achieved, false otherwise
 {
   if (!isInitialized())
   {
     ROS_ERROR("This planner has not been initialized, please call initialize() before using this planner");
     return false;
   }
   if (!costmap_ros_->getRobotPose(current_pose_))
   {
     ROS_ERROR("Could not get robot pose");
     return false;
   }
   if (latchedStopRotateController_.isGoalReached(&planner_util_, odom_helper_, current_pose_))
   {
     ROS_INFO("Goal reached");
     return true;
   }
   else
   {
     return false;
   }
 }
References costmap_ros_, current_pose_, isInitialized(), latchedStopRotateController_, odom_helper_, and planner_util_.
isInitialized()
bool rmp::controller::DWAController::isInitialized () inline
   {
     return initialized_;
   }
References initialized_.
Referenced by dwaComputeVelocityCommands(), initialize(), isGoalReached(), and setPlan().
publishGlobalPlan()
void rmp::controller::DWAController::publishGlobalPlan (std::vector< geometry_msgs::PoseStamped > & path) private
 {
   base_local_planner::publishPlan(path, g_plan_pub_);
 }
References g_plan_pub_.
Referenced by computeVelocityCommands().
publishLocalPlan()
void rmp::controller::DWAController::publishLocalPlan (std::vector< geometry_msgs::PoseStamped > & path) private
 {
   base_local_planner::publishPlan(path, l_plan_pub_);
 }
References l_plan_pub_.
Referenced by computeVelocityCommands(), and dwaComputeVelocityCommands().
reconfigureCB()
void rmp::controller::DWAController::reconfigureCB (dwa_controller::DWAControllerConfig & config, uint32_t level) private
Callback to update the local planner's parameters based on dynamic reconfigure.
 {
   if (setup_ && config.restore_defaults)
   {
     config = default_config_;
     config.restore_defaults = false;
   }
   if (!setup_)
   {
     default_config_ = config;
     setup_ = true;
   }
   // update generic local planner params
   base_local_planner::LocalPlannerLimits limits;
   limits.max_vel_trans = config.max_vel_trans;
   limits.min_vel_trans = config.min_vel_trans;
   limits.max_vel_x = config.max_vel_x;
   limits.min_vel_x = config.min_vel_x;
   limits.max_vel_y = config.max_vel_y;
   limits.min_vel_y = config.min_vel_y;
   limits.max_vel_theta = config.max_vel_theta;
   limits.min_vel_theta = config.min_vel_theta;
   limits.acc_lim_x = config.acc_lim_x;
   limits.acc_lim_y = config.acc_lim_y;
   limits.acc_lim_theta = config.acc_lim_theta;
   limits.acc_lim_trans = config.acc_lim_trans;
   limits.xy_goal_tolerance = config.xy_goal_tolerance;
   limits.yaw_goal_tolerance = config.yaw_goal_tolerance;
   limits.prune_plan = config.prune_plan;
   limits.trans_stopped_vel = config.trans_stopped_vel;
   limits.theta_stopped_vel = config.theta_stopped_vel;
   planner_util_.reconfigureCB(limits, config.restore_defaults);
   // update dwa specific configuration
   dp_->reconfigure(config);
 }
References default_config_, dp_, planner_util_, and setup_.
Referenced by initialize().
setPlan()
bool rmp::controller::DWAController::setPlan (const std::vector< geometry_msgs::PoseStamped > & orig_global_plan)
Set the plan that the controller is following.
Parameters
orig_global_plan The plan to pass to the controller
Returns
True if the plan was updated successfully, false otherwise
 {
   if (!isInitialized())
   {
     ROS_ERROR("This planner has not been initialized, please call initialize() before using this planner");
     return false;
   }
   // when we get a new plan, we also want to clear any latch we may have on goal tolerances
   latchedStopRotateController_.resetLatching();
   ROS_INFO("Got new plan");
   return dp_->setPlan(orig_global_plan);
 }
References dp_, isInitialized(), and latchedStopRotateController_.
Member Data Documentation
costmap_ros_
costmap_2d::Costmap2DROS* rmp::controller::DWAController::costmap_ros_ private
Referenced by computeVelocityCommands(), dwaComputeVelocityCommands(), initialize(), and isGoalReached().
current_pose_
geometry_msgs::PoseStamped rmp::controller::DWAController::current_pose_ private
Referenced by computeVelocityCommands(), initialize(), and isGoalReached().
default_config_
dwa_controller::DWAControllerConfig rmp::controller::DWAController::default_config_ private
Referenced by reconfigureCB().
dp_
boost::shared_ptr<DWA> rmp::controller::DWAController::dp_ private
The trajectory controller.
Referenced by computeVelocityCommands(), dwaComputeVelocityCommands(), initialize(), reconfigureCB(), and setPlan().
dsrv_
dynamic_reconfigure::Server<dwa_controller::DWAControllerConfig>* rmp::controller::DWAController::dsrv_ private
Referenced by initialize(), and ~DWAController().
g_plan_pub_
ros::Publisher rmp::controller::DWAController::g_plan_pub_ private
Referenced by initialize(), and publishGlobalPlan().
initialized_
bool rmp::controller::DWAController::initialized_ private
Referenced by initialize(), and isInitialized().
l_plan_pub_
ros::Publisher rmp::controller::DWAController::l_plan_pub_ private
Referenced by initialize(), and publishLocalPlan().
latchedStopRotateController_
base_local_planner::LatchedStopRotateController rmp::controller::DWAController::latchedStopRotateController_ private
Referenced by computeVelocityCommands(), isGoalReached(), and setPlan().
odom_helper_
base_local_planner::OdometryHelperRos rmp::controller::DWAController::odom_helper_ private
Referenced by computeVelocityCommands(), dwaComputeVelocityCommands(), initialize(), and isGoalReached().
odom_topic_
std::string rmp::controller::DWAController::odom_topic_ private
Referenced by initialize().
planner_util_
base_local_planner::LocalPlannerUtil rmp::controller::DWAController::planner_util_ private
Referenced by computeVelocityCommands(), initialize(), isGoalReached(), and reconfigureCB().
setup_
bool rmp::controller::DWAController::setup_ private
Referenced by reconfigureCB().
tf_
tf2_ros::Buffer* rmp::controller::DWAController::tf_ private
Used for transforming point clouds.
Referenced by initialize().
The documentation for this class was generated from the following files:
src/core/controller/dwa_controller/include/controller/dwa_controller.h
src/core/controller/dwa_controller/src/dwa_controller.cpp