ROS Motion Planning: rmp::common::geometry::Vec2d Class Reference
rmp::common::geometry::Vec2d Class Reference
Implements a class of 2-dimensional vectors.
#include <vec2d.h>
Public Member Functions
constexpr Vec2d (const double x, const double y) noexcept
Constructor which takes x- and y-coordinates.
constexpr Vec2d () noexcept
Constructor returning the zero vector.
double x () const
Getter for x component.
double y () const
Getter for y component.
void setX (const double x)
Setter for x component.
void setY (const double y)
Setter for y component.
double length () const
Gets the length of the vector.
double lengthSquare () const
Gets the squared length of the vector.
double angle () const
Gets the angle between the vector and the positive x semi-axis.
void normalize ()
Returns the unit vector that is co-linear with this vector.
double distanceTo (const Vec2d &other) const
Returns the distance to the given vector.
double distanceSquareTo (const Vec2d &other) const
Returns the squared distance to the given vector.
double crossProd (const Vec2d &other) const
Returns the "cross" product between these two Vec2d (non-standard).
double innerProd (const Vec2d &other) const
Returns the inner product between these two Vec2d.
Vec2d rotate (const double angle) const
rotate the vector by angle.
void selfRotate (const double angle)
rotate the vector itself by angle.
Vec2d operator+ (const Vec2d &other) const
Sums two Vec2d.
Vec2d operator- (const Vec2d &other) const
Subtracts two Vec2d.
Vec2d operator* (const double ratio) const
Multiplies Vec2d by a scalar.
Vec2d operator/ (const double ratio) const
Divides Vec2d by a scalar.
Vec2d & operator+= (const Vec2d &other)
Sums another Vec2d to the current one.
Vec2d & operator-= (const Vec2d &other)
Subtracts another Vec2d to the current one.
Vec2d & operator*= (const double ratio)
Multiplies this Vec2d by a scalar.
Vec2d & operator/= (const double ratio)
Divides this Vec2d by a scalar.
bool operator== (const Vec2d &other) const
Compares two Vec2d.
Static Public Member Functions
static Vec2d createUnitVec2d (const double angle)
Creates a unit-vector with a given angle to the positive x semi-axis.
Protected Attributes
double x_ = 0.0
double y_ = 0.0
Detailed Description
Implements a class of 2-dimensional vectors.
Constructor & Destructor Documentation
Vec2d() [1/2]
constexpr rmp::common::geometry::Vec2d::Vec2d (const double x, const double y) inline constexpr noexcept
Constructor which takes x- and y-coordinates.
                                                            : x_(x), y_(y)
   {
   }
Vec2d() [2/2]
constexpr rmp::common::geometry::Vec2d::Vec2d () inline constexpr noexcept
Constructor returning the zero vector.
                              : Vec2d(0, 0)
   {
   }
Referenced by createUnitVec2d(), operator*(), operator+(), operator-(), operator/(), and rotate().
Member Function Documentation
angle()
double rmp::common::geometry::Vec2d::angle () const
Gets the angle between the vector and the positive x semi-axis.
 {
   return std::atan2(y_, x_);
 }
References x_, and y_.
Referenced by rmp::controller::APFController::computeVelocityCommands(), createUnitVec2d(), rotate(), and selfRotate().
createUnitVec2d()
Vec2d rmp::common::geometry::Vec2d::createUnitVec2d (const double angle) static
Creates a unit-vector with a given angle to the positive x semi-axis.
 {
   return Vec2d(std::cos(angle), std::sin(angle));
 }
References angle(), and Vec2d().
crossProd()
double rmp::common::geometry::Vec2d::crossProd (const Vec2d & other) const
Returns the "cross" product between these two Vec2d (non-standard).
 {
   return x_ * other.y() - y_ * other.x();
 }
References x(), x_, y(), and y_.
distanceSquareTo()
double rmp::common::geometry::Vec2d::distanceSquareTo (const Vec2d & other) const
Returns the squared distance to the given vector.
 {
   const double dx = x_ - other.x_;
   const double dy = y_ - other.y_;
   return dx * dx + dy * dy;
 }
References x_, and y_.
distanceTo()
double rmp::common::geometry::Vec2d::distanceTo (const Vec2d & other) const
Returns the distance to the given vector.
 {
   return std::hypot(x_ - other.x_, y_ - other.y_);
 }
References x_, and y_.
innerProd()
double rmp::common::geometry::Vec2d::innerProd (const Vec2d & other) const
Returns the inner product between these two Vec2d.
 {
   return x_ * other.x() + y_ * other.y();
 }
References x(), x_, y(), and y_.
length()
double rmp::common::geometry::Vec2d::length () const
Gets the length of the vector.
 {
   return std::hypot(x_, y_);
 }
References x_, and y_.
Referenced by rmp::controller::APFController::computeVelocityCommands(), and normalize().
lengthSquare()
double rmp::common::geometry::Vec2d::lengthSquare () const
Gets the squared length of the vector.
 {
   return x_ * x_ + y_ * y_;
 }
References x_, and y_.
normalize()
void rmp::common::geometry::Vec2d::normalize ()
Returns the unit vector that is co-linear with this vector.
 {
   const double l = length();
   if (l > kMathEpsilon)
   {
     x_ /= l;
     y_ /= l;
   }
 }
References rmp::common::geometry::kMathEpsilon, length(), x_, and y_.
Referenced by rmp::controller::APFController::getAttractiveForce().
operator*()
Vec2d rmp::common::geometry::Vec2d::operator* (const double ratio) const
Multiplies Vec2d by a scalar.
 {
   return Vec2d(x_ * ratio, y_ * ratio);
 }
References Vec2d(), x_, and y_.
operator*=()
Vec2d & rmp::common::geometry::Vec2d::operator*= (const double ratio)
Multiplies this Vec2d by a scalar.
 {
   x_ *= ratio;
   y_ *= ratio;
   return *this;
 }
References x_, and y_.
operator+()
Vec2d rmp::common::geometry::Vec2d::operator+ (const Vec2d & other) const
Sums two Vec2d.
 {
   return Vec2d(x_ + other.x(), y_ + other.y());
 }
References Vec2d(), x(), x_, y(), and y_.
operator+=()
Vec2d & rmp::common::geometry::Vec2d::operator+= (const Vec2d & other)
Sums another Vec2d to the current one.
 {
   x_ += other.x();
   y_ += other.y();
   return *this;
 }
References x(), x_, y(), and y_.
operator-()
Vec2d rmp::common::geometry::Vec2d::operator- (const Vec2d & other) const
Subtracts two Vec2d.
 {
   return Vec2d(x_ - other.x(), y_ - other.y());
 }
References Vec2d(), x(), x_, y(), and y_.
operator-=()
Vec2d & rmp::common::geometry::Vec2d::operator-= (const Vec2d & other)
Subtracts another Vec2d to the current one.
 {
   x_ -= other.x();
   y_ -= other.y();
   return *this;
 }
References x(), x_, y(), and y_.
operator/()
Vec2d rmp::common::geometry::Vec2d::operator/ (const double ratio) const
Divides Vec2d by a scalar.
 {
   CHECK_GT(std::abs(ratio), kMathEpsilon);
   return Vec2d(x_ / ratio, y_ / ratio);
 }
References rmp::common::math::abs(), rmp::common::geometry::kMathEpsilon, Vec2d(), x_, and y_.
operator/=()
Vec2d & rmp::common::geometry::Vec2d::operator/= (const double ratio)
Divides this Vec2d by a scalar.
 {
   CHECK_GT(std::abs(ratio), kMathEpsilon);
   x_ /= ratio;
   y_ /= ratio;
   return *this;
 }
References rmp::common::math::abs(), rmp::common::geometry::kMathEpsilon, x_, and y_.
operator==()
bool rmp::common::geometry::Vec2d::operator== (const Vec2d & other) const
Compares two Vec2d.
 {
   return (std::abs(x_ - other.x()) < kMathEpsilon && std::abs(y_ - other.y()) < kMathEpsilon);
 }
References rmp::common::math::abs(), rmp::common::geometry::kMathEpsilon, x(), x_, y(), and y_.
rotate()
Vec2d rmp::common::geometry::Vec2d::rotate (const double angle) const
rotate the vector by angle.
 {
   return Vec2d(x_ * cos(angle) - y_ * sin(angle), x_ * sin(angle) + y_ * cos(angle));
 }
References angle(), Vec2d(), x_, and y_.
selfRotate()
void rmp::common::geometry::Vec2d::selfRotate (const double angle)
rotate the vector itself by angle.
 {
   double tmp_x = x_;
   x_ = x_ * cos(angle) - y_ * sin(angle);
   y_ = tmp_x * sin(angle) + y_ * cos(angle);
 }
References angle(), x_, and y_.
setX()
void rmp::common::geometry::Vec2d::setX (const double x) inline
Setter for x component.
   {
     x_ = x;
   }
References x(), and x_.
setY()
void rmp::common::geometry::Vec2d::setY (const double y) inline
Setter for y component.
   {
     y_ = y;
   }
References y(), and y_.
x()
double rmp::common::geometry::Vec2d::x () const inline
Getter for x component.
   {
     return x_;
   }
References x_.
Referenced by crossProd(), innerProd(), operator+(), operator+=(), operator-(), operator-=(), operator==(), and setX().
y()
double rmp::common::geometry::Vec2d::y () const inline
Getter for y component.
   {
     return y_;
   }
References y_.
Referenced by crossProd(), innerProd(), operator+(), operator+=(), operator-(), operator-=(), operator==(), and setY().
Member Data Documentation
x_
double rmp::common::geometry::Vec2d::x_ = 0.0 protected
Referenced by angle(), crossProd(), distanceSquareTo(), distanceTo(), innerProd(), length(), lengthSquare(), normalize(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), rotate(), selfRotate(), setX(), and x().
y_
double rmp::common::geometry::Vec2d::y_ = 0.0 protected
Referenced by angle(), crossProd(), distanceSquareTo(), distanceTo(), innerProd(), length(), lengthSquare(), normalize(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), operator/(), operator/=(), operator==(), rotate(), selfRotate(), setY(), and y().
The documentation for this class was generated from the following files:
src/core/common/include/common/geometry/vec2d.h
src/core/common/src/geometry/vec2d.cpp