ROS Motion Planning: Scheduler.LinearSchedule Class Reference
Scheduler.LinearSchedule Class Reference
Public Member Functions
def __init__ (self, schedule_timesteps, initial_p, final_p)
def value (self, t)
def __init__ (self, schedule_timesteps, initial_p, final_p)
def value (self, t)
def __init__ (self, schedule_timesteps, initial_p, final_p)
def value (self, t)
Public Attributes
schedule_timesteps
initial_p
final_p
Constructor & Destructor Documentation
__init__() [1/3]
def Scheduler.LinearSchedule.__init__ (self, schedule_timesteps, initial_p, final_p)
Linear interpolation between initial_p and final_p over
     def __init__(self, schedule_timesteps, initial_p, final_p):
         """Linear interpolation between initial_p and final_p over"""
         self.schedule_timesteps = schedule_timesteps
         self.initial_p = initial_p
         self.final_p = final_p
Referenced by Scheduler.LinearSchedule.__init__().
__init__() [2/3]
def Scheduler.LinearSchedule.__init__ (self, schedule_timesteps, initial_p, final_p)
Linear interpolation between initial_p and final_p over
     def __init__(self, schedule_timesteps, initial_p, final_p):
         """Linear interpolation between initial_p and final_p over"""
         self.schedule_timesteps = schedule_timesteps
         self.initial_p = initial_p
         self.final_p = final_p
References Scheduler.LinearSchedule.__init__(), Scheduler.LinearSchedule.final_p, Scheduler.LinearSchedule.initial_p, and Scheduler.LinearSchedule.schedule_timesteps.
__init__() [3/3]
def Scheduler.LinearSchedule.__init__ (self, schedule_timesteps, initial_p, final_p)
Linear interpolation between initial_p and final_p over
     def __init__(self, schedule_timesteps, initial_p, final_p):
         """Linear interpolation between initial_p and final_p over"""
         self.schedule_timesteps = schedule_timesteps
         self.initial_p = initial_p
         self.final_p = final_p
References Scheduler.LinearSchedule.__init__(), Scheduler.LinearSchedule.final_p, Scheduler.LinearSchedule.initial_p, and Scheduler.LinearSchedule.schedule_timesteps.
Member Function Documentation
value() [1/3]
def Scheduler.LinearSchedule.value (self, t)
     def value(self, t):
         fraction = min(float(t) / self.schedule_timesteps, 1.0)
         return self.initial_p + fraction * (self.final_p - self.initial_p)
References Scheduler.LinearSchedule.final_p, OkayPlan_main.float, Scheduler.LinearSchedule.initial_p, and Scheduler.LinearSchedule.schedule_timesteps.
Referenced by Scheduler.LinearSchedule.value().
value() [2/3]
def Scheduler.LinearSchedule.value (self, t)
     def value(self, t):
         fraction = min(float(t) / self.schedule_timesteps, 1.0)
         return self.initial_p + fraction * (self.final_p - self.initial_p)
References Scheduler.LinearSchedule.final_p, OkayPlan_main.float, Scheduler.LinearSchedule.initial_p, Scheduler.LinearSchedule.schedule_timesteps, and Scheduler.LinearSchedule.value().
value() [3/3]
def Scheduler.LinearSchedule.value (self, t)
     def value(self, t):
         fraction = min(float(t) / self.schedule_timesteps, 1.0)
         return self.initial_p + fraction * (self.final_p - self.initial_p)
References Scheduler.LinearSchedule.final_p, OkayPlan_main.float, Scheduler.LinearSchedule.initial_p, Scheduler.LinearSchedule.schedule_timesteps, and Scheduler.LinearSchedule.value().
Member Data Documentation
final_p
Scheduler.LinearSchedule.final_p
Referenced by Scheduler.LinearSchedule.__init__(), and Scheduler.LinearSchedule.value().
initial_p
Scheduler.LinearSchedule.initial_p
Referenced by Scheduler.LinearSchedule.__init__(), and Scheduler.LinearSchedule.value().
schedule_timesteps
Scheduler.LinearSchedule.schedule_timesteps
Referenced by Scheduler.LinearSchedule.__init__(), and Scheduler.LinearSchedule.value().
The documentation for this class was generated from the following file:
src/sim_env/scripts/ColorDynamic_ROS/utils/Scheduler.py