ROS Motion Planning: rmp::path_planner::RRTStarPathPlanner Class Reference
rmp::path_planner::RRTStarPathPlanner Class Reference
Class for objects that plan using the RRT* algorithm.
#include <rrt_star_planner.h>
Public Member Functions
RRTStarPathPlanner (costmap_2d::Costmap2DROS *costmap_ros, int sample_num, double max_dist, double r)
Constructor.
bool plan (const Point3d &start, const Point3d &goal, Points3d &path, Points3d &expand)
RRT implementation.
Public Member Functions inherited from rmp::path_planner::RRTPathPlanner
RRTPathPlanner (costmap_2d::Costmap2DROS *costmap_ros, int sample_num, double max_dist)
Constructor.
Public Member Functions inherited from rmp::path_planner::PathPlanner
PathPlanner (costmap_2d::Costmap2DROS *costmap_ros)
Construct a new Global PathPlanner object.
virtual ~PathPlanner ()=default
Destroy the Global PathPlanner object.
void setFactor (float factor)
Set or reset obstacle factor.
costmap_2d::Costmap2D * getCostMap () const
get the costmap
int getMapSize () const
get the size of costmap
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap ()
Inflate the boundary of costmap into obstacles to prevent cross planning.
Protected Member Functions
Node _findNearestPoint (std::unordered_map< int, Node > &list, Node &node)
Regular the new node by the nearest node in the sample list.
Protected Member Functions inherited from rmp::path_planner::RRTPathPlanner
Node _findNearestPoint (std::unordered_map< int, Node > &list, const Node &node)
Regular the sample node by the nearest node in the sample list.
Node _generateRandomNode ()
Generates a random node.
bool _checkGoal (const Node &new_node)
Check if goal is reachable from current node.
Protected Member Functions inherited from rmp::path_planner::PathPlanner
template<typename Node >
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
template<typename Node >
std::vector< Node > _convertBiClosedListToPath (std::unordered_map< int, Node > &f_closed_list, std::unordered_map< int, Node > &b_closed_list, const Node &start, const Node &goal, const Node &boundary)
Protected Attributes
double r_
Protected Attributes inherited from rmp::path_planner::RRTPathPlanner
Node start_
Node goal_
std::unordered_map< int, Node > sample_list_
int sample_num_
double max_dist_
double opti_sample_p_ = 0.05
Protected Attributes inherited from rmp::path_planner::PathPlanner
int map_size_
float factor_
costmap_2d::Costmap2DROS * costmap_ros_
costmap_2d::Costmap2D * costmap_
Private Types
using Node = rmp::common::structure::Node< int >
Additional Inherited Members
Public Types inherited from rmp::path_planner::PathPlanner
using Point2d = rmp::common::geometry::Point2d
using Point3d = rmp::common::geometry::Point3d
using Points2d = rmp::common::geometry::Points2d
using Points3d = rmp::common::geometry::Points3d
Detailed Description
Class for objects that plan using the RRT* algorithm.
Member Typedef Documentation
Node
using rmp::path_planner::RRTStarPathPlanner::Node = rmp::common::structure::Node<int> private
Constructor & Destructor Documentation
RRTStarPathPlanner()
rmp::path_planner::RRTStarPathPlanner::RRTStarPathPlanner (costmap_2d::Costmap2DROS * costmap_ros, int sample_num, double max_dist, double r)
Constructor.
Parameters
costmap the environment for path planning
sample_num andom sample points
max_dist max distance between sample points
r optimization radius
   : RRTPathPlanner(costmap_ros, sample_num, max_dist), r_(r)
 {
 }
Member Function Documentation
_findNearestPoint()
RRTStarPathPlanner::Node rmp::path_planner::RRTStarPathPlanner::_findNearestPoint (std::unordered_map< int, Node > & list, Node & node) protected
Regular the new node by the nearest node in the sample list.
Parameters
list sample list
node sample node
Returns
nearest node
 {
   Node nearest_node, new_node(node);
   double min_dist = std::numeric_limits<double>::max();
   for (const auto& p : list)
   {
     // calculate distance
     double new_dist = std::hypot(p.second.x() - new_node.x(), p.second.y() - new_node.y());
     // update nearest node
     if (new_dist < min_dist)
     {
       nearest_node = p.second;
       new_node.set_pid(nearest_node.id());
       new_node.set_g(new_dist + p.second.g());
       min_dist = new_dist;
     }
   }
   // distance longer than the threshold
   if (min_dist > max_dist_)
   {
     // connect sample node and nearest node, then move the nearest node
     // forward to sample node with `max_distance` as result
     double theta = std::atan2(new_node.y() - nearest_node.y(), new_node.x() - nearest_node.x());
     new_node.set_x(nearest_node.x() + static_cast<int>(max_dist_ * cos(theta)));
     new_node.set_y(nearest_node.y() + static_cast<int>(max_dist_ * sin(theta)));
     new_node.set_id(grid2Index(new_node.x(), new_node.y()));
     new_node.set_g(max_dist_ + nearest_node.g());
   }
   // obstacle check
   auto isCollision = [&](const Node& node1, const Node& node2) {
     return CollisionChecker::BresenhamCollisionDetection(node1, node2, [&](const Node& node) {
       return costmap_->getCharMap()[grid2Index(node.x(), node.y())] >= costmap_2d::LETHAL_OBSTACLE * factor_;
     });
   };
   if (!isCollision(new_node, nearest_node))
   {
     // rewire optimization
     for (auto& p : sample_list_)
     {
       // inside the optimization circle
       double new_dist = std::hypot(p.second.x() - new_node.x(), p.second.y() - new_node.y());
       if (new_dist < r_)
       {
         double cost = p.second.g() + new_dist;
         // update new sample node's cost and parent
         if (new_node.g() > cost)
         {
           if (!isCollision(new_node, p.second))
           {
             new_node.set_pid(p.second.id());
             new_node.set_g(cost);
           }
         }
         else
         {
           // update nodes' cost inside the radius
           cost = new_node.g() + new_dist;
           if (cost < p.second.g())
           {
             if (!isCollision(new_node, p.second))
             {
               p.second.set_pid(new_node.id());
               p.second.set_g(cost);
             }
           }
         }
       }
       else
         continue;
     }
   }
   else
     new_node.set_id(-1);
   return new_node;
 }
References rmp::path_planner::PathPlanner::costmap_, rmp::path_planner::PathPlanner::factor_, rmp::common::structure::Node< T >::g(), rmp::path_planner::PathPlanner::grid2Index(), rmp::common::structure::Node< T >::id(), rmp::path_planner::RRTPathPlanner::max_dist_, tf_map2odom::node, r_, rmp::path_planner::RRTPathPlanner::sample_list_, rmp::common::structure::Node< T >::set_g(), rmp::common::structure::Node< T >::set_id(), rmp::common::structure::Node< T >::set_pid(), rmp::common::structure::Node< T >::set_x(), rmp::common::structure::Node< T >::set_y(), rmp::common::structure::Node< T >::x(), and rmp::common::structure::Node< T >::y().
Referenced by plan(), and rmp::path_planner::InformedRRTStarPathPlanner::plan().
plan()
bool rmp::path_planner::RRTStarPathPlanner::plan (const Point3d & start, const Point3d & goal, Points3d & path, Points3d & expand) virtual
RRT implementation.
Parameters
start start node
goal goal node
expand containing the node been search during the process
Returns
tuple contatining a bool as to whether a path was found, and the path
Reimplemented from rmp::path_planner::RRTPathPlanner.
 {
   path.clear();
   expand.clear();
   sample_list_.clear();
   // copy
   start_.set_x(start.x());
   start_.set_y(start.y());
   start_.set_id(grid2Index(start_.x(), start_.y()));
   goal_.set_x(goal.x());
   goal_.set_y(goal.y());
   goal_.set_id(grid2Index(goal_.x(), goal_.y()));
   sample_list_.insert(std::make_pair(start_.id(), start_));
   expand.emplace_back(start.x(), start.y(), 0);
   // main loop
   int iteration = 0;
   bool optimized = false;
   while (iteration < sample_num_)
   {
     // generate a random node in the map
     Node sample_node = _generateRandomNode();
     // obstacle
     if (costmap_->getCharMap()[sample_node.id()] >= costmap_2d::LETHAL_OBSTACLE * factor_)
       continue;
     // visited
     if (sample_list_.find(sample_node.id()) != sample_list_.end())
       continue;
     // regular the sample node
     Node new_node = _findNearestPoint(sample_list_, sample_node);
     if (new_node.id() == -1)
       continue;
     else
     {
       sample_list_.insert(std::make_pair(new_node.id(), new_node));
       expand.emplace_back(new_node.x(), new_node.y(), new_node.pid());
     }
     // goal found
     if (_checkGoal(new_node))
     {
       path.clear();
       const auto& backtrace = _convertClosedListToPath<Node>(sample_list_, start_, goal_);
       for (auto iter = backtrace.rbegin(); iter != backtrace.rend(); ++iter)
       {
         path.emplace_back(iter->x(), iter->y());
       }
       optimized = true;
     }
     iteration++;
   }
   return optimized;
 }
References rmp::path_planner::RRTPathPlanner::_checkGoal(), _findNearestPoint(), rmp::path_planner::RRTPathPlanner::_generateRandomNode(), rmp::path_planner::PathPlanner::costmap_, rmp::path_planner::PathPlanner::factor_, rmp::path_planner::RRTPathPlanner::goal_, rmp::path_planner::PathPlanner::grid2Index(), rmp::common::structure::Node< T >::id(), rmp::common::structure::Node< T >::pid(), rmp::path_planner::RRTPathPlanner::sample_list_, rmp::path_planner::RRTPathPlanner::sample_num_, rmp::common::structure::Node< T >::set_id(), rmp::common::structure::Node< T >::set_x(), rmp::common::structure::Node< T >::set_y(), rmp::path_planner::RRTPathPlanner::start_, rmp::common::structure::Node< T >::x(), rmp::common::geometry::Point3_< T >::x(), rmp::common::structure::Node< T >::y(), and rmp::common::geometry::Point3_< T >::y().
Member Data Documentation
r_
double rmp::path_planner::RRTStarPathPlanner::r_ protected
Referenced by _findNearestPoint(), and rmp::path_planner::QuickInformedRRTStarPathPlanner::_findNearestPoint().
The documentation for this class was generated from the following files:
src/core/path_planner/path_planner/include/path_planner/sample_planner/rrt_star_planner.h
src/core/path_planner/path_planner/src/sample_planner/rrt_star_planner.cpp