ROS Motion Planning: rmp::common::geometry::Point3_< T > Class Template Reference
rmp::common::geometry::Point3_< T > Class Template Reference
#include <point.h>
Public Member Functions
Point3_ (T x=0, T y=0, T theta=0)
~Point3_ ()=default
T x () const
T y () const
T theta () const
void setX (T x)
void setY (T y)
void setTheta (T theta)
T operator[] (size_t i) const
bool operator== (const Point3_ &other)
bool operator!= (const Point3_ &other)
Static Public Attributes
static const int dim = 3
Private Attributes
T x_
T y_
T theta_
Constructor & Destructor Documentation
Point3_()
template<typename T > rmp::common::geometry::Point3_< T >::Point3_ (T x = 0, T y = 0, T theta = 0) inline
 {
~Point3_()
template<typename T > rmp::common::geometry::Point3_< T >::~Point3_ () default
Member Function Documentation
operator!=()
template<typename T > bool rmp::common::geometry::Point3_< T >::operator!= (const Point3_< T > & other) inline
operator==()
template<typename T > bool rmp::common::geometry::Point3_< T >::operator== (const Point3_< T > & other) inline
Referenced by rmp::common::geometry::Point3_< T >::y().
operator[]()
template<typename T > T rmp::common::geometry::Point3_< T >::operator[] (size_t i) const inline
setTheta()
template<typename T > void rmp::common::geometry::Point3_< T >::setTheta (T theta) inline
setX()
template<typename T > void rmp::common::geometry::Point3_< T >::setX (T x) inline
setY()
template<typename T > void rmp::common::geometry::Point3_< T >::setY (T y) inline
theta()
template<typename T > T rmp::common::geometry::Point3_< T >::theta () const inline
       :
   static const int dim = 3;
 private:
Referenced by rmp::common::geometry::BezierCurve::generation(), rmp::common::geometry::DubinsCurve::generation(), rmp::common::geometry::ReedsSheppCurve::generation(), rmp::common::geometry::BezierCurve::getControlPoints(), rmp::common::geometry::DubinsCurve::interpolate(), rmp::common::geometry::ReedsSheppCurve::interpolate(), rmp::common::geometry::Point2_< T >::operator==(), and rmp::path_planner::HybridAStarPathPlanner::plan().
x()
template<typename T > T rmp::common::geometry::Point3_< T >::x () const inline
   {
     return (x_ == static_cast<T>(other.x())) &&
            (y_ == static_cast<T>(other.y()) && (theta_ == static_cast<T>(other.theta())));
   }
References rmp::common::geometry::Point3_< T >::x_.
Referenced by rmp::common::geometry::BezierCurve::generation(), rmp::common::geometry::DubinsCurve::generation(), rmp::common::geometry::ReedsSheppCurve::generation(), rmp::common::geometry::BezierCurve::getControlPoints(), rmp::common::geometry::DubinsCurve::interpolate(), rmp::common::geometry::ReedsSheppCurve::interpolate(), rmp::path_planner::AStarPathPlanner::plan(), rmp::path_planner::JPSPathPlanner::plan(), rmp::path_planner::LazyThetaStarPathPlanner::plan(), rmp::path_planner::SThetaStarPathPlanner::plan(), rmp::path_planner::RRTConnectPathPlanner::plan(), rmp::path_planner::RRTStarPathPlanner::plan(), rmp::path_planner::InformedRRTStarPathPlanner::plan(), rmp::path_planner::RRTPathPlanner::plan(), rmp::path_planner::ThetaStarPathPlanner::plan(), rmp::path_planner::QuickInformedRRTStarPathPlanner::plan(), rmp::path_planner::VoronoiPathPlanner::plan(), rmp::path_planner::ACOPathPlanner::plan(), rmp::path_planner::GAPathPlanner::plan(), rmp::path_planner::PSOPathPlanner::plan(), rmp::path_planner::HybridAStarPathPlanner::plan(), rmp::path_planner::DStarPathPlanner::plan(), rmp::path_planner::LPAStarPathPlanner::plan(), rmp::path_planner::DStarLitePathPlanner::plan(), and rmp::common::geometry::Point2_< T >::setY().
y()
template<typename T > T rmp::common::geometry::Point3_< T >::y () const inline
   {
     return !operator==(other);
   }
References rmp::common::geometry::Point3_< T >::operator==().
Referenced by rmp::common::geometry::BezierCurve::generation(), rmp::common::geometry::DubinsCurve::generation(), rmp::common::geometry::ReedsSheppCurve::generation(), rmp::common::geometry::BezierCurve::getControlPoints(), rmp::common::geometry::DubinsCurve::interpolate(), rmp::common::geometry::ReedsSheppCurve::interpolate(), rmp::common::geometry::Point2_< T >::operator[](), rmp::path_planner::AStarPathPlanner::plan(), rmp::path_planner::JPSPathPlanner::plan(), rmp::path_planner::LazyThetaStarPathPlanner::plan(), rmp::path_planner::SThetaStarPathPlanner::plan(), rmp::path_planner::RRTConnectPathPlanner::plan(), rmp::path_planner::RRTStarPathPlanner::plan(), rmp::path_planner::RRTPathPlanner::plan(), rmp::path_planner::InformedRRTStarPathPlanner::plan(), rmp::path_planner::QuickInformedRRTStarPathPlanner::plan(), rmp::path_planner::ThetaStarPathPlanner::plan(), rmp::path_planner::VoronoiPathPlanner::plan(), rmp::path_planner::ACOPathPlanner::plan(), rmp::path_planner::GAPathPlanner::plan(), rmp::path_planner::PSOPathPlanner::plan(), rmp::path_planner::HybridAStarPathPlanner::plan(), rmp::path_planner::DStarPathPlanner::plan(), rmp::path_planner::LPAStarPathPlanner::plan(), and rmp::path_planner::DStarLitePathPlanner::plan().
Member Data Documentation
dim
template<typename T > const int rmp::common::geometry::Point3_< T >::dim = 3 static
theta_
template<typename T > T rmp::common::geometry::Point3_< T >::theta_ private
Referenced by rmp::common::geometry::Point2_< T >::operator==(), and rmp::common::geometry::Point2_< T >::setX().
x_
template<typename T > T rmp::common::geometry::Point3_< T >::x_ private
Referenced by rmp::common::geometry::Point2_< T >::setY(), rmp::common::geometry::Point2_< T >::x(), and rmp::common::geometry::Point3_< T >::x().
y_
template<typename T > T rmp::common::geometry::Point3_< T >::y_ private
Referenced by rmp::common::geometry::Point2_< T >::operator[](), and rmp::common::geometry::Point2_< T >::y().
The documentation for this class was generated from the following file:
src/core/common/include/common/geometry/point.h