ROS Motion Planning: rmp::path_planner::ThetaStarPathPlanner Class Reference
rmp::path_planner::ThetaStarPathPlanner Class Reference
Class for objects that plan using the Theta* algorithm.
#include <theta_star_planner.h>
Public Member Functions
ThetaStarPathPlanner (costmap_2d::Costmap2DROS *costmap_ros)
Construct a new ThetaStar object.
bool plan (const Point3d &start, const Point3d &goal, Points3d &path, Points3d &expand)
Theta* implementation.
Public Member Functions inherited from rmp::path_planner::PathPlanner
PathPlanner (costmap_2d::Costmap2DROS *costmap_ros)
Construct a new Global PathPlanner object.
virtual ~PathPlanner ()=default
Destroy the Global PathPlanner object.
void setFactor (float factor)
Set or reset obstacle factor.
costmap_2d::Costmap2D * getCostMap () const
get the costmap
int getMapSize () const
get the size of costmap
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap ()
Inflate the boundary of costmap into obstacles to prevent cross planning.
Protected Member Functions
void _updateVertex (const Node &parent, Node &child)
update the g value of child node
Protected Member Functions inherited from rmp::path_planner::PathPlanner
template<typename Node >
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
template<typename Node >
std::vector< Node > _convertBiClosedListToPath (std::unordered_map< int, Node > &f_closed_list, std::unordered_map< int, Node > &b_closed_list, const Node &start, const Node &goal, const Node &boundary)
Private Types
using Node = rmp::common::structure::Node< int >
Private Attributes
const std::vector< Node > motions
Additional Inherited Members
Public Types inherited from rmp::path_planner::PathPlanner
using Point2d = rmp::common::geometry::Point2d
using Point3d = rmp::common::geometry::Point3d
using Points2d = rmp::common::geometry::Points2d
using Points3d = rmp::common::geometry::Points3d
Protected Attributes inherited from rmp::path_planner::PathPlanner
int map_size_
float factor_
costmap_2d::Costmap2DROS * costmap_ros_
costmap_2d::Costmap2D * costmap_
Detailed Description
Class for objects that plan using the Theta* algorithm.
Member Typedef Documentation
Node
using rmp::path_planner::ThetaStarPathPlanner::Node = rmp::common::structure::Node<int> private
Constructor & Destructor Documentation
ThetaStarPathPlanner()
rmp::path_planner::ThetaStarPathPlanner::ThetaStarPathPlanner (costmap_2d::Costmap2DROS * costmap_ros)
Construct a new ThetaStar object.
Parameters
costmap the environment for path planning
 : PathPlanner(costmap_ros){};
Member Function Documentation
_updateVertex()
void rmp::path_planner::ThetaStarPathPlanner::_updateVertex (const Node & parent, Node & child) protected
update the g value of child node
Parameters
parent
child
 {
   auto isCollision = [&](const Node& node1, const Node& node2) {
     return CollisionChecker::BresenhamCollisionDetection(node1, node2, [&](const Node& node) {
       return costmap_->getCharMap()[grid2Index(node.x(), node.y())] >= costmap_2d::LETHAL_OBSTACLE * factor_;
     });
   };
   if (!isCollision(parent, child))
   {
     // path 2
     const double dist = std::hypot(parent.x() - child.x(), parent.y() - child.y());
     if (parent.g() + dist < child.g())
     {
       child.set_g(parent.g() + dist);
       child.set_pid(parent.id());
     }
   }
 }
References rmp::path_planner::PathPlanner::costmap_, rmp::path_planner::PathPlanner::factor_, rmp::common::structure::Node< T >::g(), rmp::path_planner::PathPlanner::grid2Index(), rmp::common::structure::Node< T >::id(), tf_map2odom::node, rmp::common::structure::Node< T >::set_g(), rmp::common::structure::Node< T >::set_pid(), rmp::common::structure::Node< T >::x(), and rmp::common::structure::Node< T >::y().
Referenced by plan().
plan()
bool rmp::path_planner::ThetaStarPathPlanner::plan (const Point3d & start, const Point3d & goal, Points3d & path, Points3d & expand) virtual
Theta* implementation.
Parameters
start start node
goal goal node
path optimal path consists of Node
expand containing the node been search during the process
Returns
true if path found, else false
Implements rmp::path_planner::PathPlanner.
 {
   // initialize
   Node start_node(start.x(), start.y());
   Node goal_node(goal.x(), goal.y());
   start_node.set_id(grid2Index(start_node.x(), start_node.y()));
   goal_node.set_id(grid2Index(goal_node.x(), goal_node.y()));
   path.clear();
   expand.clear();
   // open list and closed list
   std::priority_queue<Node, std::vector<Node>, Node::compare_cost> open_list;
   std::unordered_map<int, Node> closed_list;
   open_list.push(start_node);
   // main process
   while (!open_list.empty())
   {
     // pop current node from open list
     auto current = open_list.top();
     open_list.pop();
     // current node does not exist in closed list
     if (closed_list.find(current.id()) != closed_list.end())
       continue;
     closed_list.insert(std::make_pair(current.id(), current));
     expand.emplace_back(current.x(), current.y());
     // goal found
     if (current == goal_node)
     {
       const auto& backtrace = _convertClosedListToPath<Node>(closed_list, start_node, goal_node);
       for (auto iter = backtrace.rbegin(); iter != backtrace.rend(); ++iter)
       {
         path.emplace_back(iter->x(), iter->y());
       }
       return true;
     }
     // explore neighbor of current node
     for (const auto& m : motions)
     {
       // explore a new node
       // path 1
       auto node_new = current + m;  // add the x_, y_, g_
       node_new.set_g(current.g() + m.g());
       node_new.set_h(std::hypot(node_new.x() - goal_node.x(), node_new.y() - goal_node.y()));
       node_new.set_id(grid2Index(node_new.x(), node_new.y()));
       node_new.set_pid(current.id());
       // current node do not exist in closed list
       if (closed_list.find(node_new.id()) != closed_list.end())
         continue;
       // next node hit the boundary or obstacle
       if ((node_new.id() < 0) || (node_new.id() >= map_size_) ||
           (costmap_->getCharMap()[node_new.id()] >= costmap_2d::LETHAL_OBSTACLE * factor_ &&
            costmap_->getCharMap()[node_new.id()] >= costmap_->getCharMap()[current.id()]))
         continue;
       // get the coordinate of parent node
       Node parent;
       parent.set_id(current.pid());
       int tmp_x, tmp_y;
       index2Grid(parent.id(), tmp_x, tmp_y);
       parent.set_x(tmp_x);
       parent.set_y(tmp_y);
       // update g value
       auto find_parent = closed_list.find(parent.id());
       if (find_parent != closed_list.end())
       {
         parent = find_parent->second;
         _updateVertex(parent, node_new);
       }
       open_list.push(node_new);
     }
   }
   return false;
 }
References _updateVertex(), rmp::path_planner::PathPlanner::costmap_, rmp::path_planner::PathPlanner::factor_, rmp::path_planner::PathPlanner::grid2Index(), rmp::common::structure::Node< T >::id(), rmp::path_planner::PathPlanner::index2Grid(), rmp::path_planner::PathPlanner::map_size_, motions, rmp::common::structure::Node< T >::set_id(), rmp::common::structure::Node< T >::set_x(), rmp::common::structure::Node< T >::set_y(), rmp::common::structure::Node< T >::x(), rmp::common::geometry::Point3_< T >::x(), rmp::common::structure::Node< T >::y(), and rmp::common::geometry::Point3_< T >::y().
Member Data Documentation
motions
const std::vector<Node> rmp::path_planner::ThetaStarPathPlanner::motions private
Initial value:
= {
    { 0, 1, 1.0 },          { 1, 0, 1.0 },           { 0, -1, 1.0 },          { -1, 0, 1.0 },
    { 1, 1, std::sqrt(2) }, { 1, -1, std::sqrt(2) }, { -1, 1, std::sqrt(2) }, { -1, -1, std::sqrt(2) },
  }
Referenced by plan().
The documentation for this class was generated from the following files:
src/core/path_planner/path_planner/include/path_planner/graph_planner/theta_star_planner.h
src/core/path_planner/path_planner/src/graph_planner/theta_star_planner.cpp