ROS Motion Planning: rmp::path_planner::DStarPathPlanner::DNode Class Reference
rmp::path_planner::DStarPathPlanner::DNode Class Reference
Public Types
enum Tag { NEW = 0, OPEN = 1, CLOSED = 2 }
Public Member Functions
DNode (const int x=0, const int y=0, const double g=std::numeric_limits< double >::max(), const double h=std::numeric_limits< double >::max(), const int id=0, const int pid=-1, const int t=NEW, const double k=std::numeric_limits< double >::max())
Construct a new DNode object.
int t () const
double k () const
void setTag (int t)
void setK (double k)
Public Member Functions inherited from rmp::common::structure::Node< int >
Node (int x=0, int y=0, double g=0.0, double h=0.0, int id=0, int pid=0)
Constructor for Node class.
Node (const Node &n)
int x () const
get the property of node
int y () const
double g () const
double h () const
int id () const
int pid () const
void set_x (int x)
set the property of node
void set_y (int y)
void set_g (double g)
void set_h (double h)
void set_id (int id)
void set_pid (int pid)
Node operator+ (const Node &n) const
Overloading operator + for Node class.
Node operator- (const Node &n) const
Overloading operator - for Node class.
bool operator== (const Node &n) const
Overloading operator == for Node class.
bool operator!= (const Node &n) const
Overloading operator != for Node class.
Private Attributes
int t_
double k_
Additional Inherited Members
Protected Attributes inherited from rmp::common::structure::Node< int >
int x_
int y_
double g_
double h_
int id_
int pid_
Member Enumeration Documentation
Tag
enum rmp::path_planner::DStarPathPlanner::DNode::Tag
Enumerator
NEW
OPEN
CLOSED
     {
       NEW = 0,
       OPEN = 1,
       CLOSED = 2
     };
Constructor & Destructor Documentation
DNode()
rmp::path_planner::DStarPathPlanner::DNode::DNode (const int x = 0, const int y = 0, const double g = std::numeric_limits<double>::max(), const double h = std::numeric_limits<double>::max(), const int id = 0, const int pid = -1, const int t = NEW, const double k = std::numeric_limits<double>::max()) inline
Construct a new DNode object.
Parameters
x X value
y Y value
g Cost to get to this node
h Heuritic cost of this node
id DNode's id
pid DNode's parent's id
t DNode's tag among enum Tag
k DNode's k_min in history
       : Node(x, y, g, h, id, pid), t_(t), k_(k)
     {
     }
Member Function Documentation
k()
double rmp::path_planner::DStarPathPlanner::DNode::k () const inline
     {
       return k_;
     }
References k_.
Referenced by rmp::path_planner::DStarPathPlanner::insert(), and setK().
setK()
void rmp::path_planner::DStarPathPlanner::DNode::setK (double k) inline
     {
       k_ = k;
     }
References k(), and k_.
Referenced by rmp::path_planner::DStarPathPlanner::insert().
setTag()
void rmp::path_planner::DStarPathPlanner::DNode::setTag (int t) inline
     {
       t_ = t;
     }
References t(), and t_.
Referenced by rmp::path_planner::DStarPathPlanner::insert().
t()
int rmp::path_planner::DStarPathPlanner::DNode::t () const inline
     {
       return t_;
     }
References t_.
Referenced by rmp::path_planner::DStarPathPlanner::extractExpand(), rmp::path_planner::DStarPathPlanner::insert(), rmp::path_planner::DStarPathPlanner::plan(), and setTag().
Member Data Documentation
k_
double rmp::path_planner::DStarPathPlanner::DNode::k_ private
Referenced by k(), and setK().
t_
int rmp::path_planner::DStarPathPlanner::DNode::t_ private
Referenced by setTag(), and t().
The documentation for this class was generated from the following file:
src/core/path_planner/path_planner/include/path_planner/graph_planner/dstar_planner.h