ROS Motion Planning: rmp::common::structure::Node< T > Class Template Reference
rmp::common::structure::Node< T > Class Template Reference
Basic Node class.
#include <node.h>
Classes
struct compare_coordinates
Struct created to encapsulate function compare coordinates between 2 Nodes. Used in with multiple algorithms and classes.
struct compare_cost
Struct created to encapsulate function compare cost between 2 Nodes. Used in with multiple algorithms and classes.
Public Member Functions
Node (T x=0, T y=0, double g=0.0, double h=0.0, int id=0, int pid=0)
Constructor for Node class.
Node (const Node &n)
T x () const
get the property of node
T y () const
double g () const
double h () const
int id () const
int pid () const
void set_x (T x)
set the property of node
void set_y (T y)
void set_g (double g)
void set_h (double h)
void set_id (int id)
void set_pid (int pid)
Node operator+ (const Node &n) const
Overloading operator + for Node class.
Node operator- (const Node &n) const
Overloading operator - for Node class.
bool operator== (const Node &n) const
Overloading operator == for Node class.
bool operator!= (const Node &n) const
Overloading operator != for Node class.
Protected Attributes
T x_
T y_
double g_
double h_
int id_
int pid_
Detailed Description
template<typename T>
class rmp::common::structure::Node< T >
Basic Node class.
Constructor & Destructor Documentation
Node() [1/2]
template<typename T > rmp::common::structure::Node< T >::Node (T x = 0, T y = 0, double g = 0.0, double h = 0.0, int id = 0, int pid = 0) inline
Constructor for Node class.
Parameters
x x value
y y value
g g value, cost to get to this node
h h value, heuritic cost of this node
id node's id
pid node's parent's id
     : x_(x), y_(y), g_(g), h_(h), id_(id), pid_(pid){};
Referenced by rmp::common::structure::Node< int >::operator+(), and rmp::common::structure::Node< int >::operator-().
Node() [2/2]
template<typename T > rmp::common::structure::Node< T >::Node (const Node< T > & n) inline
 : x_(n.x()), y_(n.y()), g_(n.g()), h_(n.h()), id_(n.id()), pid_(n.pid()){};
Member Function Documentation
g()
template<typename T > double rmp::common::structure::Node< T >::g () const inline
   {
     return g_;
   };
Referenced by rmp::path_planner::RRTPathPlanner::_checkGoal(), rmp::path_planner::RRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::RRTPathPlanner::_findNearestPoint(), rmp::path_planner::QuickInformedRRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::LazyThetaStarPathPlanner::_updateVertex(), rmp::path_planner::SThetaStarPathPlanner::_updateVertex(), rmp::path_planner::ThetaStarPathPlanner::_updateVertex(), rmp::path_planner::LPAStarPathPlanner::computeShortestPath(), rmp::path_planner::DStarLitePathPlanner::computeShortestPath(), rmp::path_planner::LPAStarPathPlanner::extractPath(), rmp::path_planner::DStarLitePathPlanner::extractPath(), rmp::path_planner::DStarPathPlanner::insert(), rmp::path_planner::JPSPathPlanner::jump(), rmp::common::structure::Node< T >::compare_cost::operator()(), rmp::path_planner::RRTConnectPathPlanner::plan(), rmp::path_planner::InformedRRTStarPathPlanner::plan(), rmp::path_planner::QuickInformedRRTStarPathPlanner::plan(), rmp::common::structure::Node< int >::set_g(), rmp::path_planner::LPAStarPathPlanner::updateVertex(), and rmp::path_planner::DStarLitePathPlanner::updateVertex().
h()
template<typename T > double rmp::common::structure::Node< T >::h () const inline
   {
     return h_;
   };
Referenced by rmp::common::structure::Node< T >::compare_cost::operator()(), and rmp::common::structure::Node< int >::set_h().
id()
template<typename T > int rmp::common::structure::Node< T >::id () const inline
   {
     return id_;
   };
Referenced by rmp::path_planner::RRTPathPlanner::_checkGoal(), rmp::path_planner::HybridAStarPathPlanner::_convertClosedListToPath(), rmp::path_planner::RRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::RRTPathPlanner::_findNearestPoint(), rmp::path_planner::QuickInformedRRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::QuickInformedRRTStarPathPlanner::_generateRandomNode(), rmp::path_planner::RRTPathPlanner::_generateRandomNode(), rmp::path_planner::InformedRRTStarPathPlanner::_generateRandomNode(), rmp::path_planner::LazyThetaStarPathPlanner::_setVertex(), rmp::path_planner::LazyThetaStarPathPlanner::_updateVertex(), rmp::path_planner::SThetaStarPathPlanner::_updateVertex(), rmp::path_planner::ThetaStarPathPlanner::_updateVertex(), rmp::path_planner::HybridAStarPathPlanner::genHeurisiticMap(), rmp::path_planner::DStarPathPlanner::isCollision(), rmp::path_planner::LPAStarPathPlanner::isCollision(), rmp::path_planner::DStarLitePathPlanner::isCollision(), rmp::path_planner::JPSPathPlanner::jump(), rmp::path_planner::LazyThetaStarPathPlanner::plan(), rmp::path_planner::SThetaStarPathPlanner::plan(), rmp::path_planner::RRTConnectPathPlanner::plan(), rmp::path_planner::RRTStarPathPlanner::plan(), rmp::path_planner::RRTPathPlanner::plan(), rmp::path_planner::InformedRRTStarPathPlanner::plan(), rmp::path_planner::QuickInformedRRTStarPathPlanner::plan(), rmp::path_planner::ThetaStarPathPlanner::plan(), rmp::path_planner::HybridAStarPathPlanner::plan(), and rmp::common::structure::Node< int >::set_id().
operator!=()
template<typename T > bool rmp::common::structure::Node< T >::operator!= (const Node< T > & n) const inline
Overloading operator != for Node class.
Parameters
n another Node
Returns
true if current node equals node n, else false
   {
     return !operator==(n);
   };
operator+()
template<typename T > Node rmp::common::structure::Node< T >::operator+ (const Node< T > & n) const inline
Overloading operator + for Node class.
Parameters
n another Node
Returns
Node with current node's and input node n's values added
   {
     return Node(x_ + n.x(), y_ + n.y());
   };
operator-()
template<typename T > Node rmp::common::structure::Node< T >::operator- (const Node< T > & n) const inline
Overloading operator - for Node class.
Parameters
n another Node
Returns
Node with current node's and input node n's values subtracted
   {
     return Node(x_ - n.x(), y_ - n.y());
   };
operator==()
template<typename T > bool rmp::common::structure::Node< T >::operator== (const Node< T > & n) const inline
Overloading operator == for Node class.
Parameters
n another Node
Returns
true if current node equals node n, else false
   {
     return x_ == n.x() && y_ == n.y();
   };
Referenced by rmp::common::structure::Node< int >::operator!=().
pid()
template<typename T > int rmp::common::structure::Node< T >::pid () const inline
   {
     return pid_;
   };
Referenced by rmp::path_planner::DStarPathPlanner::extractPath(), rmp::path_planner::RRTConnectPathPlanner::plan(), rmp::path_planner::RRTStarPathPlanner::plan(), rmp::path_planner::InformedRRTStarPathPlanner::plan(), rmp::path_planner::RRTPathPlanner::plan(), rmp::path_planner::QuickInformedRRTStarPathPlanner::plan(), and rmp::common::structure::Node< int >::set_pid().
set_g()
template<typename T > void rmp::common::structure::Node< T >::set_g (double g) inline
   {
     g_ = g;
   };
Referenced by rmp::path_planner::RRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::RRTPathPlanner::_findNearestPoint(), rmp::path_planner::QuickInformedRRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::LazyThetaStarPathPlanner::_updateVertex(), rmp::path_planner::SThetaStarPathPlanner::_updateVertex(), rmp::path_planner::ThetaStarPathPlanner::_updateVertex(), rmp::path_planner::LPAStarPathPlanner::computeShortestPath(), rmp::path_planner::DStarLitePathPlanner::computeShortestPath(), rmp::path_planner::DStarPathPlanner::insert(), rmp::path_planner::JPSPathPlanner::jump(), rmp::path_planner::HybridAStarPathPlanner::HybridNode::operator+(), rmp::path_planner::RRTConnectPathPlanner::plan(), and rmp::path_planner::DStarPathPlanner::plan().
set_h()
template<typename T > void rmp::common::structure::Node< T >::set_h (double h) inline
   {
     h_ = h;
   };
set_id()
template<typename T > void rmp::common::structure::Node< T >::set_id (int id) inline
   {
     id_ = id;
   };
Referenced by rmp::path_planner::RRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::RRTPathPlanner::_findNearestPoint(), rmp::path_planner::QuickInformedRRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::LazyThetaStarPathPlanner::_setVertex(), rmp::path_planner::JPSPathPlanner::plan(), rmp::path_planner::AStarPathPlanner::plan(), rmp::path_planner::SThetaStarPathPlanner::plan(), rmp::path_planner::LazyThetaStarPathPlanner::plan(), rmp::path_planner::RRTStarPathPlanner::plan(), rmp::path_planner::RRTConnectPathPlanner::plan(), rmp::path_planner::RRTPathPlanner::plan(), rmp::path_planner::InformedRRTStarPathPlanner::plan(), rmp::path_planner::QuickInformedRRTStarPathPlanner::plan(), rmp::path_planner::ThetaStarPathPlanner::plan(), rmp::path_planner::VoronoiPathPlanner::plan(), rmp::path_planner::DStarPathPlanner::plan(), rmp::path_planner::LPAStarPathPlanner::plan(), rmp::path_planner::DStarLitePathPlanner::plan(), and rmp::path_planner::VoronoiPathPlanner::searchPathWithVoronoi().
set_pid()
template<typename T > void rmp::common::structure::Node< T >::set_pid (int pid) inline
   {
     pid_ = pid;
   };
Referenced by rmp::path_planner::RRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::RRTPathPlanner::_findNearestPoint(), rmp::path_planner::QuickInformedRRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::LazyThetaStarPathPlanner::_updateVertex(), rmp::path_planner::SThetaStarPathPlanner::_updateVertex(), rmp::path_planner::ThetaStarPathPlanner::_updateVertex(), rmp::path_planner::RRTConnectPathPlanner::plan(), and rmp::path_planner::HybridAStarPathPlanner::plan().
set_x()
template<typename T > void rmp::common::structure::Node< T >::set_x (T x) inline
set the property of node
   {
     x_ = x;
   };
Referenced by rmp::path_planner::RRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::RRTPathPlanner::_findNearestPoint(), rmp::path_planner::QuickInformedRRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::LazyThetaStarPathPlanner::_setVertex(), rmp::path_planner::DStarLitePathPlanner::DStarLitePathPlanner(), rmp::path_planner::DStarPathPlanner::DStarPathPlanner(), rmp::path_planner::DStarPathPlanner::getState(), rmp::path_planner::LPAStarPathPlanner::getState(), rmp::path_planner::DStarLitePathPlanner::getState(), rmp::path_planner::LPAStarPathPlanner::LPAStarPathPlanner(), rmp::path_planner::JPSPathPlanner::plan(), rmp::path_planner::LazyThetaStarPathPlanner::plan(), rmp::path_planner::SThetaStarPathPlanner::plan(), rmp::path_planner::RRTStarPathPlanner::plan(), rmp::path_planner::RRTConnectPathPlanner::plan(), rmp::path_planner::RRTPathPlanner::plan(), rmp::path_planner::InformedRRTStarPathPlanner::plan(), rmp::path_planner::ThetaStarPathPlanner::plan(), rmp::path_planner::QuickInformedRRTStarPathPlanner::plan(), rmp::path_planner::HybridAStarPathPlanner::plan(), rmp::path_planner::DStarPathPlanner::plan(), rmp::path_planner::LPAStarPathPlanner::plan(), rmp::path_planner::DStarLitePathPlanner::plan(), and rmp::path_planner::VoronoiPathPlanner::searchPathWithVoronoi().
set_y()
template<typename T > void rmp::common::structure::Node< T >::set_y (T y) inline
   {
     y_ = y;
   };
Referenced by rmp::path_planner::RRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::RRTPathPlanner::_findNearestPoint(), rmp::path_planner::QuickInformedRRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::LazyThetaStarPathPlanner::_setVertex(), rmp::path_planner::DStarLitePathPlanner::DStarLitePathPlanner(), rmp::path_planner::DStarPathPlanner::DStarPathPlanner(), rmp::path_planner::DStarPathPlanner::getState(), rmp::path_planner::LPAStarPathPlanner::getState(), rmp::path_planner::DStarLitePathPlanner::getState(), rmp::path_planner::LPAStarPathPlanner::LPAStarPathPlanner(), rmp::path_planner::JPSPathPlanner::plan(), rmp::path_planner::LazyThetaStarPathPlanner::plan(), rmp::path_planner::SThetaStarPathPlanner::plan(), rmp::path_planner::RRTStarPathPlanner::plan(), rmp::path_planner::RRTConnectPathPlanner::plan(), rmp::path_planner::RRTPathPlanner::plan(), rmp::path_planner::InformedRRTStarPathPlanner::plan(), rmp::path_planner::ThetaStarPathPlanner::plan(), rmp::path_planner::QuickInformedRRTStarPathPlanner::plan(), rmp::path_planner::HybridAStarPathPlanner::plan(), rmp::path_planner::DStarPathPlanner::plan(), rmp::path_planner::LPAStarPathPlanner::plan(), rmp::path_planner::DStarLitePathPlanner::plan(), and rmp::path_planner::VoronoiPathPlanner::searchPathWithVoronoi().
x()
template<typename T > T rmp::common::structure::Node< T >::x () const inline
get the property of node
   {
     return x_;
   };
Referenced by rmp::path_planner::SThetaStarPathPlanner::_alpha(), rmp::path_planner::RRTPathPlanner::_checkGoal(), rmp::path_planner::HybridAStarPathPlanner::_convertClosedListToPath(), rmp::path_planner::RRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::RRTPathPlanner::_findNearestPoint(), rmp::path_planner::QuickInformedRRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::RRTPathPlanner::_generateRandomNode(), rmp::path_planner::InformedRRTStarPathPlanner::_transform(), rmp::path_planner::LazyThetaStarPathPlanner::_updateVertex(), rmp::path_planner::SThetaStarPathPlanner::_updateVertex(), rmp::path_planner::ThetaStarPathPlanner::_updateVertex(), rmp::path_planner::JPSPathPlanner::detectForceNeighbor(), rmp::path_planner::HybridAStarPathPlanner::dubinsShot(), rmp::path_planner::DStarPathPlanner::extractPath(), rmp::path_planner::LPAStarPathPlanner::extractPath(), rmp::path_planner::DStarLitePathPlanner::extractPath(), rmp::path_planner::DStarPathPlanner::getCost(), rmp::path_planner::LPAStarPathPlanner::getCost(), rmp::path_planner::DStarLitePathPlanner::getCost(), rmp::path_planner::DStarLitePathPlanner::getH(), rmp::path_planner::LPAStarPathPlanner::getH(), rmp::path_planner::DStarPathPlanner::getNeighbours(), rmp::path_planner::LPAStarPathPlanner::getNeighbours(), rmp::path_planner::DStarLitePathPlanner::getNeighbours(), rmp::path_planner::DStarPathPlanner::getState(), rmp::path_planner::LPAStarPathPlanner::getState(), rmp::path_planner::DStarLitePathPlanner::getState(), rmp::path_planner::JPSPathPlanner::jump(), rmp::common::structure::Node< T >::compare_coordinates::operator()(), rmp::common::structure::Node< int >::operator+(), rmp::common::structure::Node< int >::operator-(), rmp::common::structure::Node< int >::operator==(), rmp::path_planner::JPSPathPlanner::plan(), rmp::path_planner::AStarPathPlanner::plan(), rmp::path_planner::SThetaStarPathPlanner::plan(), rmp::path_planner::LazyThetaStarPathPlanner::plan(), rmp::path_planner::RRTConnectPathPlanner::plan(), rmp::path_planner::RRTStarPathPlanner::plan(), rmp::path_planner::InformedRRTStarPathPlanner::plan(), rmp::path_planner::RRTPathPlanner::plan(), rmp::path_planner::QuickInformedRRTStarPathPlanner::plan(), rmp::path_planner::ThetaStarPathPlanner::plan(), rmp::path_planner::VoronoiPathPlanner::plan(), rmp::path_planner::HybridAStarPathPlanner::plan(), rmp::path_planner::DStarPathPlanner::plan(), rmp::path_planner::LPAStarPathPlanner::plan(), rmp::path_planner::DStarLitePathPlanner::plan(), rmp::path_planner::VoronoiPathPlanner::searchPathWithVoronoi(), rmp::common::structure::Node< int >::set_x(), rmp::path_planner::LPAStarPathPlanner::updateVertex(), and rmp::path_planner::DStarLitePathPlanner::updateVertex().
y()
template<typename T > T rmp::common::structure::Node< T >::y () const inline
   {
     return y_;
   };
Referenced by rmp::path_planner::SThetaStarPathPlanner::_alpha(), rmp::path_planner::RRTPathPlanner::_checkGoal(), rmp::path_planner::HybridAStarPathPlanner::_convertClosedListToPath(), rmp::path_planner::RRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::RRTPathPlanner::_findNearestPoint(), rmp::path_planner::QuickInformedRRTStarPathPlanner::_findNearestPoint(), rmp::path_planner::RRTPathPlanner::_generateRandomNode(), rmp::path_planner::InformedRRTStarPathPlanner::_transform(), rmp::path_planner::LazyThetaStarPathPlanner::_updateVertex(), rmp::path_planner::SThetaStarPathPlanner::_updateVertex(), rmp::path_planner::ThetaStarPathPlanner::_updateVertex(), rmp::path_planner::JPSPathPlanner::detectForceNeighbor(), rmp::path_planner::HybridAStarPathPlanner::dubinsShot(), rmp::path_planner::DStarPathPlanner::extractPath(), rmp::path_planner::LPAStarPathPlanner::extractPath(), rmp::path_planner::DStarLitePathPlanner::extractPath(), rmp::path_planner::DStarPathPlanner::getCost(), rmp::path_planner::LPAStarPathPlanner::getCost(), rmp::path_planner::DStarLitePathPlanner::getCost(), rmp::path_planner::DStarLitePathPlanner::getH(), rmp::path_planner::LPAStarPathPlanner::getH(), rmp::path_planner::DStarPathPlanner::getNeighbours(), rmp::path_planner::LPAStarPathPlanner::getNeighbours(), rmp::path_planner::DStarLitePathPlanner::getNeighbours(), rmp::path_planner::DStarPathPlanner::getState(), rmp::path_planner::LPAStarPathPlanner::getState(), rmp::path_planner::DStarLitePathPlanner::getState(), rmp::path_planner::JPSPathPlanner::jump(), rmp::common::structure::Node< T >::compare_coordinates::operator()(), rmp::common::structure::Node< int >::operator+(), rmp::common::structure::Node< int >::operator-(), rmp::common::structure::Node< int >::operator==(), rmp::path_planner::JPSPathPlanner::plan(), rmp::path_planner::AStarPathPlanner::plan(), rmp::path_planner::SThetaStarPathPlanner::plan(), rmp::path_planner::LazyThetaStarPathPlanner::plan(), rmp::path_planner::RRTConnectPathPlanner::plan(), rmp::path_planner::RRTStarPathPlanner::plan(), rmp::path_planner::InformedRRTStarPathPlanner::plan(), rmp::path_planner::RRTPathPlanner::plan(), rmp::path_planner::QuickInformedRRTStarPathPlanner::plan(), rmp::path_planner::ThetaStarPathPlanner::plan(), rmp::path_planner::VoronoiPathPlanner::plan(), rmp::path_planner::HybridAStarPathPlanner::plan(), rmp::path_planner::DStarPathPlanner::plan(), rmp::path_planner::LPAStarPathPlanner::plan(), rmp::path_planner::DStarLitePathPlanner::plan(), rmp::path_planner::VoronoiPathPlanner::searchPathWithVoronoi(), rmp::common::structure::Node< int >::set_y(), rmp::path_planner::LPAStarPathPlanner::updateVertex(), and rmp::path_planner::DStarLitePathPlanner::updateVertex().
Member Data Documentation
g_
template<typename T > double rmp::common::structure::Node< T >::g_ protected
Referenced by rmp::common::structure::Node< int >::g(), and rmp::common::structure::Node< int >::set_g().
h_
template<typename T > double rmp::common::structure::Node< T >::h_ protected
Referenced by rmp::common::structure::Node< int >::h(), and rmp::common::structure::Node< int >::set_h().
id_
template<typename T > int rmp::common::structure::Node< T >::id_ protected
Referenced by rmp::common::structure::Node< int >::id(), and rmp::common::structure::Node< int >::set_id().
pid_
template<typename T > int rmp::common::structure::Node< T >::pid_ protected
Referenced by rmp::common::structure::Node< int >::pid(), and rmp::common::structure::Node< int >::set_pid().
x_
template<typename T > T rmp::common::structure::Node< T >::x_ protected
Referenced by rmp::path_planner::HybridAStarPathPlanner::HybridNode::operator+(), rmp::common::structure::Node< int >::operator+(), rmp::common::structure::Node< int >::operator-(), rmp::path_planner::HybridAStarPathPlanner::HybridNode::operator==(), rmp::common::structure::Node< int >::operator==(), rmp::common::structure::Node< int >::set_x(), and rmp::common::structure::Node< int >::x().
y_
template<typename T > T rmp::common::structure::Node< T >::y_ protected
Referenced by rmp::path_planner::HybridAStarPathPlanner::HybridNode::operator+(), rmp::common::structure::Node< int >::operator+(), rmp::common::structure::Node< int >::operator-(), rmp::path_planner::HybridAStarPathPlanner::HybridNode::operator==(), rmp::common::structure::Node< int >::operator==(), rmp::common::structure::Node< int >::set_y(), and rmp::common::structure::Node< int >::y().
The documentation for this class was generated from the following file:
src/core/common/include/common/structure/node.h