ROS Motion Planning: rmp::common::geometry::BSplineCurve Class Reference
rmp::common::geometry::BSplineCurve Class Reference
#include <bspline_curve.h>
Public Types
enum PARAM_MODE { UNIFORMSPACED = 0, CENTRIPETAL = 1, CHORDLENGTH = 2 }
enum SPLINE_MODE { INTERPOLATION = 0, APPROXIMATION = 1 }
Public Member Functions
BSplineCurve ()
Construct a new B-Spline generation object.
BSplineCurve (double step, int order, int param_mode, int spline_mode)
Construct a new B-Spline generation object.
~BSplineCurve ()
Destroy the B-Spline generation object.
bool run (const Points2d points, Points2d &path)
Running trajectory generation.
bool run (const Points3d points, Points2d &path)
Running trajectory generation.
double baseFunction (int i, int k, double t, std::vector< double > knot)
Calculate base function using Cox-deBoor function.
std::vector< double > paramSelection (const Points2d points)
Calculate parameters using the uniform spaced or chrod length or centripetal method.
std::vector< double > knotGeneration (const std::vector< double > param, int n)
Generate knot vector.
Points2d interpolation (const Points2d points, const std::vector< double > param, const std::vector< double > knot)
Given a set of N data points, D0, D1, ..., Dn and a degree k, find a B-spline curve of degree k defined by N control points that passes all data points in the given order.
Points2d approximation (const Points2d points, const std::vector< double > param, const std::vector< double > knot)
Given a set of N data points, D0, D1, ..., Dn, a degree k, and a number H, where N > H > k >= 1, find a B-spline curve of degree k defined by H control points that satisfies the following conditions:
Points2d generation (int k, const std::vector< double > knot, Points2d control_pts)
Generate the path.
void setSplineOrder (int order)
Configure the degree of the curve.
void setParamMode (int param_mode)
Configure the parameterization mode.
void setSPlineMode (int spline_mode)
Configure the B-Spline generation mode.
Public Member Functions inherited from rmp::common::geometry::Curve
Curve (double step)
Construct a new Curve object.
virtual ~Curve ()=default
Destroy the curve generation object.
double len (Points2d path)
Calculate length of given path.
void setStep (double step)
Configure the simulation step.
Protected Attributes
int order_
int param_mode_
int spline_mode_
Protected Attributes inherited from rmp::common::geometry::Curve
double step_
Member Enumeration Documentation
PARAM_MODE
enum rmp::common::geometry::BSplineCurve::PARAM_MODE
Enumerator
UNIFORMSPACED
CENTRIPETAL
CHORDLENGTH
   {
     UNIFORMSPACED = 0,
     CENTRIPETAL = 1,
     CHORDLENGTH = 2,
   };
SPLINE_MODE
enum rmp::common::geometry::BSplineCurve::SPLINE_MODE
Enumerator
INTERPOLATION
APPROXIMATION
   {
     INTERPOLATION = 0,
     APPROXIMATION = 1,
   };
Constructor & Destructor Documentation
BSplineCurve() [1/2]
rmp::common::geometry::BSplineCurve::BSplineCurve ()
Construct a new B-Spline generation object.
Parameters
step Simulation or interpolation size (default: 0.01)
order Degree of curve (default: 3)
param_mode Parameterization mode (default: PARAM_MODE_CHORDLENGTH)
spline_mode B-Spline generation mode (default: SPLINE_MODE_INTERPOLATION)
   : Curve(0.01), order_(3), param_mode_(PARAM_MODE::CENTRIPETAL), spline_mode_(SPLINE_MODE::INTERPOLATION)
 {
 }
BSplineCurve() [2/2]
rmp::common::geometry::BSplineCurve::BSplineCurve (double step, int order, int param_mode, int spline_mode)
Construct a new B-Spline generation object.
Parameters
step Simulation or interpolation size (default: 0.01)
order Degree of curve (default: 3)
param_mode Parameterization mode (default: PARAM_MODE_CHORDLENGTH)
spline_mode B-Spline generation mode (default: SPLINE_MODE_INTERPOLATION)
   : Curve(step), order_(order), param_mode_(param_mode), spline_mode_(spline_mode)
 {
 }
~BSplineCurve()
rmp::common::geometry::BSplineCurve::~BSplineCurve ()
Destroy the B-Spline generation object.
 {
 }
Member Function Documentation
approximation()
Points2d rmp::common::geometry::BSplineCurve::approximation (const Points2d points, const std::vector< double > param, const std::vector< double > knot)
Given a set of N data points, D0, D1, ..., Dn, a degree k, and a number H, where N > H > k >= 1, find a B-spline curve of degree k defined by H control points that satisfies the following conditions:
this curve contains the first and last data points;
this curve approximates the data polygon in the sense of least square
Parameters
points Path points
parameters The parameters of given points
knot The knot vector
Returns
control_points The control points
 {
   size_t n = points.size();
   Eigen::MatrixXd D(n, 2);
   for (size_t i = 0; i < n; i++)
   {
     D(i, 0) = points[i].x();
     D(i, 1) = points[i].y();
   }
   // heuristically setting the number of control points
   size_t h = n - 1;
   Eigen::MatrixXd N = Eigen::MatrixXd::Zero(n, h);
   for (size_t i = 0; i < n; i++)
     for (size_t j = 0; j < h; j++)
       N(i, j) = baseFunction(j, order_, param[i], knot);
   Eigen::MatrixXd N_ = Eigen::MatrixXd::Zero(n - 2, h - 2);
   for (size_t i = 1; i < n - 1; i++)
     for (size_t j = 1; j < h - 1; j++)
       N_(i - 1, j - 1) = N(i, j);
   Eigen::MatrixXd qk = Eigen::MatrixXd::Zero(n - 2, 2);
   for (size_t i = 1; i < n - 1; i++)
   {
     qk(i - 1, 0) = D(i, 0) - N(i, 0) * D(0, 0) - N(i, h - 1) * D(n - 1, 0);
     qk(i - 1, 1) = D(i, 1) - N(i, 0) * D(0, 1) - N(i, h - 1) * D(n - 1, 1);
   }
   Eigen::MatrixXd Q = N_.transpose() * qk;
   Eigen::MatrixXd P = (N_.transpose() * N_).inverse() * Q;
   Points2d control_points(h);
   control_points[0] = { D(0, 0), D(0, 1) };
   control_points[h - 1] = { D(n - 1, 0), D(n - 1, 1) };
   for (size_t i = 1; i < h - 1; i++)
     control_points[i] = { P(i - 1, 0), P(i - 1, 1) };
   return control_points;
 }
References baseFunction(), and order_.
Referenced by run().
baseFunction()
double rmp::common::geometry::BSplineCurve::baseFunction (int i, int k, double t, std::vector< double > knot)
Calculate base function using Cox-deBoor function.
Parameters
i The index of base function
k The degree of curve
t Parameter
knot Knot vector
Returns
Nik_t The value of base function Nik(t)
 {
   double Nik_t = 0;
   // 1st order B-spline
   if (k == 0)
     Nik_t = ((t >= knot[i]) && (t < knot[i + 1])) ? 1.0 : 0.0;
   // 2nd order and higher B-spline
   else
   {
     double length1 = double(knot[i + k]) - knot[i];
     double length2 = double(knot[i + k + 1]) - knot[i + 1];
     // Handle the case where the denominator is 0 by replacing it with 1, defining 0/0 as 0
     if ((length1 == 0) && (length2 == 0))
       Nik_t = 0;
     else if (length1 == 0)
       Nik_t = (knot[i + k + 1] - t) / length2 * baseFunction(i + 1, k - 1, t, knot);
     else if (length2 == 0)
       Nik_t = (t - knot[i]) / length1 * baseFunction(i, k - 1, t, knot);
     else
       Nik_t = (t - knot[i]) / length1 * baseFunction(i, k - 1, t, knot) +
               (knot[i + k + 1] - t) / length2 * baseFunction(i + 1, k - 1, t, knot);
   }
   return Nik_t;
 }
Referenced by approximation(), generation(), and interpolation().
generation()
Points2d rmp::common::geometry::BSplineCurve::generation (int k, const std::vector< double > knot, Points2d control_pts)
Generate the path.
Parameters
k The degree of curve
knot The knot vector
control_points The control points
Returns
path The smoothed trajectory points
 {
   size_t n = static_cast<int>(1.0 / step_);
   std::vector<double> t(n);
   for (size_t i = 0; i < n; i++)
     t[i] = (double)(i) / (double)(n - 1);
   Eigen::MatrixXd N(n, control_pts.size());
   for (size_t i = 0; i < n; i++)
     for (size_t j = 0; j < control_pts.size(); j++)
       N(i, j) = baseFunction(j, order_, t[i], knot);
   N(n - 1, control_pts.size() - 1) = 1.0;
   Eigen::MatrixXd C(control_pts.size(), 2);
   for (size_t i = 0; i < control_pts.size(); i++)
   {
     C(i, 0) = control_pts[i].x();
     C(i, 1) = control_pts[i].y();
   }
   Eigen::MatrixXd P = N * C;
   Points2d points(n);
   for (size_t i = 0; i < n; i++)
     points[i] = { P(i, 0), P(i, 1) };
   return points;
 }
References baseFunction(), order_, and rmp::common::geometry::Curve::step_.
Referenced by run().
interpolation()
Points2d rmp::common::geometry::BSplineCurve::interpolation (const Points2d points, const std::vector< double > param, const std::vector< double > knot)
Given a set of N data points, D0, D1, ..., Dn and a degree k, find a B-spline curve of degree k defined by N control points that passes all data points in the given order.
Parameters
points Path points
parameters The parameters of given points
knot The knot vector
Returns
control_points The control points
 {
   size_t n = points.size();
   Eigen::MatrixXd N = Eigen::MatrixXd::Zero(n, n);
   Eigen::MatrixXd D(n, 2);
   for (size_t i = 0; i < n; i++)
     for (size_t j = 0; j < n; j++)
       N(i, j) = baseFunction(j, order_, param[i], knot);
   N(n - 1, n - 1) = 1;
   for (size_t i = 0; i < n; i++)
   {
     D(i, 0) = points[i].x();
     D(i, 1) = points[i].y();
   }
   Eigen::MatrixXd C = N.inverse() * D;
   Points2d control_points(n);
   for (size_t i = 0; i < n; i++)
   {
     control_points[i] = { C(i, 0), C(i, 1) };
   }
   return control_points;
 }
References baseFunction(), and order_.
Referenced by run().
knotGeneration()
std::vector< double > rmp::common::geometry::BSplineCurve::knotGeneration (const std::vector< double > param, int n)
Generate knot vector.
Parameters
parameters The parameters of given points
n The number of data points
Returns
knot The knot vector
 {
   int m = n + order_ + 1;
   std::vector<double> knot(m);
   for (size_t i = 0; i < n; i++)
     knot[i] = 0.0;
   for (size_t i = n; i < m; i++)
     knot[i] = 1.0;
   for (size_t i = order_ + 1; i < n; i++)
   {
     for (size_t j = i - order_; j < i; j++)
       knot[i] += param[j];
     knot[i] /= order_;
   }
   return knot;
 }
References order_.
Referenced by run().
paramSelection()
std::vector< double > rmp::common::geometry::BSplineCurve::paramSelection (const Points2d points)
Calculate parameters using the uniform spaced or chrod length or centripetal method.
Parameters
points Path points
Returns
parameters The parameters of given points
 {
   size_t n = points.size();
   std::vector<double> parameters(n);
   if (param_mode_ == PARAM_MODE::UNIFORMSPACED)
   {
     for (size_t i = 0; i < n; i++)
       parameters[i] = (double)(i) / (double)(n - 1);
   }
   else
   {
     parameters[0] = 0.0;
     std::vector<double> s(n - 1);
     double d_cumsum = 0.0;
     for (size_t i = 0; i < n - 1; i++)
     {
       double d;
       if (param_mode_ == PARAM_MODE::CHORDLENGTH)
       {
         d = std::hypot(points[i].x() - points[i + 1].x(), points[i].y() - points[i + 1].y());
       }
       else
       {
         double alpha = 0.5;
         d = std::pow(std::hypot(points[i].x() - points[i + 1].x(), points[i].y() - points[i + 1].y()), alpha);
       }
       d_cumsum += d;
       s[i] = d_cumsum;
     }
     for (size_t i = 1; i < n; i++)
       parameters[i] = s[i - 1] / s[n - 2];
   }
   return parameters;
 }
References rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::alpha, rviz_generate::d, param_mode_, key_ctrl::s, FakeAMCL::x, and FakeAMCL::y.
Referenced by run().
run() [1/2]
bool rmp::common::geometry::BSplineCurve::run (const Points2d points, Points2d & path) virtual
Running trajectory generation.
Parameters
points path points <x, y>
path generated trajectory
Returns
true if generate successfully, else failed
Parameters
points path points
path generated trajectory
Returns
true if generate successfully, else failed
Implements rmp::common::geometry::Curve.
 {
   if (points.size() < 4)
     return false;
   else
   {
     Points2d control_pts;
     std::vector<double> params = paramSelection(points);
     std::vector<double> knot = knotGeneration(params, points.size());
     if (spline_mode_ == SPLINE_MODE::INTERPOLATION)
     {
       control_pts = interpolation(points, params, knot);
     }
     else if (spline_mode_ == SPLINE_MODE::APPROXIMATION)
     {
       control_pts = approximation(points, params, knot);
       params = paramSelection(control_pts);
       knot = knotGeneration(params, control_pts.size());
     }
     else
       return false;
     path = generation(order_, knot, control_pts);
     return !path.empty();
   }
 }
References approximation(), generation(), interpolation(), knotGeneration(), order_, OkayPlan_main::params, paramSelection(), and spline_mode_.
Referenced by run().
run() [2/2]
bool rmp::common::geometry::BSplineCurve::run (const Points3d points, Points2d & path) virtual
Running trajectory generation.
Parameters
points path points <x, y, theta>
path generated trajectory
Returns
true if generate successfully, else failed
Implements rmp::common::geometry::Curve.
 {
   Points2d points_pair;
   for (const auto& p : points)
   {
     points_pair.emplace_back(p.x(), p.y());
   }
   return run(points_pair, path);
 }
References run().
setParamMode()
void rmp::common::geometry::BSplineCurve::setParamMode (int param_mode)
Configure the parameterization mode.
Configure the parameterization mode .
Parameters
param_mode The parameterization mode
 {
   assert((param_mode == PARAM_MODE::CENTRIPETAL) || (param_mode == PARAM_MODE::CHORDLENGTH) ||
          (param_mode == PARAM_MODE::UNIFORMSPACED));
   param_mode_ = param_mode;
 }
References param_mode_.
setSPlineMode()
void rmp::common::geometry::BSplineCurve::setSPlineMode (int spline_mode)
Configure the B-Spline generation mode.
Parameters
spline_mode The B-Spline generation mode
 {
   assert((spline_mode == SPLINE_MODE::APPROXIMATION) || (spline_mode == SPLINE_MODE::INTERPOLATION));
   spline_mode_ = spline_mode;
 }
References spline_mode_.
setSplineOrder()
void rmp::common::geometry::BSplineCurve::setSplineOrder (int order)
Configure the degree of the curve.
Parameters
order The degree of curve
 {
   assert(order > 0);
   order_ = order;
 }
References order_.
Member Data Documentation
order_
int rmp::common::geometry::BSplineCurve::order_ protected
Referenced by approximation(), generation(), interpolation(), knotGeneration(), run(), and setSplineOrder().
param_mode_
int rmp::common::geometry::BSplineCurve::param_mode_ protected
Referenced by paramSelection(), and setParamMode().
spline_mode_
int rmp::common::geometry::BSplineCurve::spline_mode_ protected
Referenced by run(), and setSPlineMode().
The documentation for this class was generated from the following files:
src/core/common/include/common/geometry/bspline_curve.h
src/core/common/src/geometry/bspline_curve.cpp