ROS Motion Planning: rmp::common::geometry::ReedsSheppCurve Class Reference
rmp::common::geometry::ReedsSheppCurve Class Reference
#include <reeds_shepp_curve.h>
Classes
class RSPath
Public Member Functions
ReedsSheppCurve ()
Construct a new ReedsShepp generation object.
ReedsSheppCurve (double step, double max_curv)
Construct a new ReedsShepp generation object.
~ReedsSheppCurve ()
Destroy the ReedsShepp generation object.
bool run (const Points2d points, Points2d &path)
Running trajectory generation.
bool run (const Points3d points, Points2d &path)
Running trajectory generation.
void R (double x, double y, double &r, double &theta)
Return the polar coordinates (r, theta) of the point (x, y), i.e. rcos(theta) = x; rsin(theta) = y.
double M (double theta)
Truncate the angle to the interval of -π to π.
bool SLS (double x, double y, double phi, RSLength &length)
Straight-Left-Straight generation mode.
bool LRL (double x, double y, double phi, RSLength &length)
Left-Right-Left generation mode. (L+R-L-)
bool LSL (double x, double y, double phi, RSLength &length)
Left-Straight-Left generation mode. (L+S+L+)
bool LSR (double x, double y, double phi, RSLength &length)
Left-Straight-Right generation mode. (L+S+R+)
bool LRLRn (double x, double y, double phi, RSLength &length)
Left-Right(beta)-Left(beta)-Right generation mode. (L+R+L-R-)
bool LRLRp (double x, double y, double phi, RSLength &length)
Left-Right(beta)-Left(beta)-Right generation mode. (L+R-L-R+)
bool LRSR (double x, double y, double phi, RSLength &length)
Left-Right(pi/2)-Straight-Right generation mode. (L+R-S-R-)
bool LRSL (double x, double y, double phi, RSLength &length)
Left-Right(pi/2)-Straight-Left generation mode. (L+R-S-L-)
bool LRSLR (double x, double y, double phi, RSLength &length)
Left-Right(pi/2)-Straight-Left(pi/2)-Right generation mode. (L+R-S-L-R+)
std::vector< RSPath > SCS (double x, double y, double phi)
# 2 Straight-Circle-Straight generation mode(using reflect).
std::vector< RSPath > CCC (double x, double y, double phi)
# 8 Circle-Circle-Circle generation mode(using reflect, timeflip and backwards).
std::vector< RSPath > CSC (double x, double y, double phi)
# 8 Circle-Straight-Circle generation mode(using reflect, timeflip and backwards).
std::vector< RSPath > CCCC (double x, double y, double phi)
# 8 Circle-Circle(beta)-Circle(beta)-Circle generation mode (using reflect, timeflip and backwards).
std::vector< RSPath > CCSC (double x, double y, double phi)
# 16 Circle-Circle(pi/2)-Straight-Circle and Circle-Straight-Circle(pi/2)-Circle generation mode (using reflect, timeflip and backwards).
std::vector< RSPath > CCSCC (double x, double y, double phi)
# 4 Circle-Circle(pi/2)-Straight–Circle(pi/2)-Circle generation mode (using reflect, timeflip and backwards).
Point3d interpolate (int mode, double length, Point3d init_pose)
Planning path interpolation.
Points2d generation (Point3d start, Point3d goal)
Generate the path.
void setMaxCurv (double max_curv)
Configure the maximum curvature.
Public Member Functions inherited from rmp::common::geometry::Curve
Curve (double step)
Construct a new Curve object.
virtual ~Curve ()=default
Destroy the curve generation object.
double len (Points2d path)
Calculate length of given path.
void setStep (double step)
Configure the simulation step.
Protected Member Functions
void _calTauOmega (double u, double v, double xi, double eta, double phi, double &tau, double &omega)
void _update (std::vector< RSPath > cur_paths, RSPath &best_path)
Update the best motion mode.
Protected Attributes
double max_curv_
Protected Attributes inherited from rmp::common::geometry::Curve
double step_
Private Types
enum { REEDS_SHEPP_NONE = -1, REEDS_SHEPP_L = 0, REEDS_SHEPP_S = 1, REEDS_SHEPP_R = 2 }
using RSMode = std::tuple< int, int, int >
using RSLength = std::tuple< double, double, double >
Member Typedef Documentation
RSLength
using rmp::common::geometry::ReedsSheppCurve::RSLength = std::tuple<double, double, double> private
RSMode
using rmp::common::geometry::ReedsSheppCurve::RSMode = std::tuple<int, int, int> private
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
REEDS_SHEPP_NONE
REEDS_SHEPP_L
REEDS_SHEPP_S
REEDS_SHEPP_R
   {
     REEDS_SHEPP_NONE = -1,
     REEDS_SHEPP_L = 0,
     REEDS_SHEPP_S = 1,
     REEDS_SHEPP_R = 2,
   };
Constructor & Destructor Documentation
ReedsSheppCurve() [1/2]
rmp::common::geometry::ReedsSheppCurve::ReedsSheppCurve ()
Construct a new ReedsShepp generation object.
Parameters
step Simulation or interpolation size (default: 0.1)
max_curv The maximum curvature of the curve (default: 0.25)
                                  : Curve(0.1), max_curv_(0.25)
 {
 }
ReedsSheppCurve() [2/2]
rmp::common::geometry::ReedsSheppCurve::ReedsSheppCurve (double step, double max_curv)
Construct a new ReedsShepp generation object.
Parameters
step Simulation or interpolation size (default: 0.1)
max_curv The maximum curvature of the curve (default: 0.25)
                                                              : Curve(step), max_curv_(max_curv)
 {
 }
~ReedsSheppCurve()
rmp::common::geometry::ReedsSheppCurve::~ReedsSheppCurve ()
Destroy the ReedsShepp generation object.
 {
 }
Member Function Documentation
_calTauOmega()
void rmp::common::geometry::ReedsSheppCurve::_calTauOmega (double u, double v, double xi, double eta, double phi, double & tau, double & omega) protected
 {
   double delta = M(u - v);
   double A = sin(u) - sin(delta);
   double B = cos(u) - cos(delta) - 1.0;
   double t1 = atan2(eta * A - xi * B, xi * A + eta * B);
   double t2 = 2.0 * (cos(delta) - cos(v) - cos(u)) + 3.0;
   tau = t2 < 0 ? M(t1 + M_PI) : M(t1);
   omega = M(tau - u + v - phi);
 }
References M().
Referenced by LRLRn(), and LRLRp().
_update()
void rmp::common::geometry::ReedsSheppCurve::_update (std::vector< RSPath > cur_paths, RSPath & best_path) protected
Update the best motion mode.
Parameters
cur_paths current generated Reeds-Shepp paths
best_path The best generated Reeds-Shepp path so far
 {
   for (auto p : cur_paths)
   {
     if (p.len() < best_path.len())
       best_path = p;
   }
 }
References rmp::common::geometry::ReedsSheppCurve::RSPath::len().
Referenced by generation().
CCC()
std::vector< ReedsSheppCurve::RSPath > rmp::common::geometry::ReedsSheppCurve::CCC (double x, double y, double phi)
# 8 Circle-Circle-Circle generation mode(using reflect, timeflip and backwards).
Parameters
x/y Goal position
phi Goal pose
Returns
Reeds-Shepp Paths
 {
   std::vector<RSPath> paths;
   RSLength length;
   double t, u, v;
   bool flag;
   // L+R-L-
   flag = LRL(x, y, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, u, v }, { REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_L } });
   }
   // timefilp: L-R+L+
   flag = LRL(-x, y, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -t, -u, -v }, { REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_L } });
   }
   // reflect: R+L-R-
   flag = LRL(x, -y, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, u, v }, { REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_R } });
   }
   // timeflip + reflect: R-L+R+
   flag = LRL(-x, -y, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -t, -u, -v }, { REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_R } });
   }
   // backwards
   double xb = x * cos(phi) + y * sin(phi);
   double yb = x * sin(phi) - y * cos(phi);
   // backwards: L-R-L+
   flag = LRL(xb, yb, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { v, u, t }, { REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_L } });
   }
   // backwards + timefilp: L+R+L-
   flag = LRL(-xb, yb, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -v, -u, -t }, { REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_L } });
   }
   // backwards + reflect: R-L-R+
   flag = LRL(xb, -yb, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { v, u, t }, { REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_R } });
   }
   // backwards + timeflip + reflect: R+L+R-
   flag = LRL(-xb, -yb, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -v, -u, -t }, { REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_R } });
   }
   return paths;
 }
References LRL(), REEDS_SHEPP_L, REEDS_SHEPP_R, FakeAMCL::x, and FakeAMCL::y.
Referenced by generation().
CCCC()
std::vector< ReedsSheppCurve::RSPath > rmp::common::geometry::ReedsSheppCurve::CCCC (double x, double y, double phi)
# 8 Circle-Circle(beta)-Circle(beta)-Circle generation mode (using reflect, timeflip and backwards).
Parameters
x/y Goal position
phi Goal pose
Returns
Reeds-Shepp Paths
 {
   std::vector<RSPath> paths;
   RSLength length;
   double t, u, v;
   bool flag;
   // L+R+L-R-
   flag = LRLRn(x, y, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, u, -u, v }, { REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_R } });
   }
   // timefilp: L-R-L+R+
   flag = LRLRn(-x, y, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -t, -u, u, -v }, { REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_R } });
   }
   // reflect: R+L+R-L-
   flag = LRLRn(x, -y, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, u, -u, v }, { REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_L } });
   }
   // timeflip + reflect: R-L-R+L+
   flag = LRLRn(-x, -y, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -t, -u, u, -v }, { REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_L } });
   }
   // L+R-L-R+
   flag = LRLRp(x, y, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, u, u, v }, { REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_R } });
   }
   // timefilp: L-R+L+R-
   flag = LRLRp(-x, y, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -t, -u, -u, -v }, { REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_R } });
   }
   // reflect: R+L-R-L+
   flag = LRLRp(x, -y, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, u, u, v }, { REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_L } });
   }
   // timeflip + reflect: R-L+R+L-
   flag = LRLRp(-x, -y, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -t, -u, -u, -v }, { REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_L } });
   }
   return paths;
 }
References LRLRn(), LRLRp(), REEDS_SHEPP_L, REEDS_SHEPP_R, FakeAMCL::x, and FakeAMCL::y.
Referenced by generation().
CCSC()
std::vector< ReedsSheppCurve::RSPath > rmp::common::geometry::ReedsSheppCurve::CCSC (double x, double y, double phi)
# 16 Circle-Circle(pi/2)-Straight-Circle and Circle-Straight-Circle(pi/2)-Circle generation mode (using reflect, timeflip and backwards).
Parameters
x/y Goal position
phi Goal pose
Returns
Reeds-Shepp Paths
 {
   std::vector<RSPath> paths;
   RSLength length;
   double t, u, v;
   bool flag;
   // L+R-(pi/2)S-L-
   flag = LRSL(x, y, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, -0.5 * M_PI, u, v }, { REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_S, REEDS_SHEPP_L } });
   }
   // timefilp: L-R+(pi/2)S+L+
   flag = LRSL(-x, y, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -t, 0.5 * M_PI, -u, -v }, { REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_S, REEDS_SHEPP_L } });
   }
   // reflect: R+L-(pi/2)S-R-
   flag = LRSL(x, -y, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, -0.5 * M_PI, u, v }, { REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_S, REEDS_SHEPP_R } });
   }
   // timeflip + reflect: R-L+(pi/2)S+R+
   flag = LRSL(-x, -y, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -t, 0.5 * M_PI, -u, -v }, { REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_S, REEDS_SHEPP_R } });
   }
   // L+R-(pi/2)S-R-
   flag = LRSR(x, y, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, -0.5 * M_PI, u, v }, { REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_S, REEDS_SHEPP_R } });
   }
   // timefilp: L-R+(pi/2)S+R+
   flag = LRSR(-x, y, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -t, 0.5 * M_PI, -u, -v }, { REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_S, REEDS_SHEPP_R } });
   }
   // reflect: R+L-(pi/2)S-L-
   flag = LRSR(x, -y, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, -0.5 * M_PI, u, v }, { REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_S, REEDS_SHEPP_L } });
   }
   // timeflip + reflect: R-L+(pi/2)S+L+
   flag = LRSR(-x, -y, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -t, 0.5 * M_PI, -u, -v }, { REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_S, REEDS_SHEPP_L } });
   }
   // backwards
   double xb = x * cos(phi) + y * sin(phi);
   double yb = x * sin(phi) - y * cos(phi);
   // backwards: L-S-R-(pi/2)L+
   flag = LRSL(xb, yb, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { v, u, -0.5 * M_PI, t }, { REEDS_SHEPP_L, REEDS_SHEPP_S, REEDS_SHEPP_R, REEDS_SHEPP_L } });
   }
   // backwards + timefilp: L+S+R+(pi/2)L-
   flag = LRSL(-xb, yb, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -v, -u, 0.5 * M_PI, -t }, { REEDS_SHEPP_L, REEDS_SHEPP_S, REEDS_SHEPP_R, REEDS_SHEPP_L } });
   }
   // backwards + reflect: R-S-L-(pi/2)R+
   flag = LRSL(xb, -yb, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { v, u, -0.5 * M_PI, t }, { REEDS_SHEPP_R, REEDS_SHEPP_S, REEDS_SHEPP_L, REEDS_SHEPP_R } });
   }
   // backwards + timefilp + reflect: R+S+L+(pi/2)R-
   flag = LRSL(-xb, -yb, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -v, -u, 0.5 * M_PI, -t }, { REEDS_SHEPP_R, REEDS_SHEPP_S, REEDS_SHEPP_L, REEDS_SHEPP_R } });
   }
   // backwards: R-S-R-(pi/2)L+
   flag = LRSR(xb, yb, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { v, u, -0.5 * M_PI, t }, { REEDS_SHEPP_R, REEDS_SHEPP_S, REEDS_SHEPP_R, REEDS_SHEPP_L } });
   }
   // backwards + timefilp: R+S+R+(pi/2)L-
   flag = LRSR(-xb, yb, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -v, -u, 0.5 * M_PI, -t }, { REEDS_SHEPP_R, REEDS_SHEPP_S, REEDS_SHEPP_R, REEDS_SHEPP_L } });
   }
   // backwards + reflect: L-S-L-(pi/2)R+
   flag = LRSR(xb, -yb, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { v, u, -0.5 * M_PI, t }, { REEDS_SHEPP_L, REEDS_SHEPP_S, REEDS_SHEPP_L, REEDS_SHEPP_R } });
   }
   // backwards + timefilp + reflect: L+S+L+(pi/2)R-
   flag = LRSR(-xb, -yb, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -v, -u, 0.5 * M_PI, -t }, { REEDS_SHEPP_L, REEDS_SHEPP_S, REEDS_SHEPP_L, REEDS_SHEPP_R } });
   }
   return paths;
 }
References LRSL(), LRSR(), REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_S, FakeAMCL::x, and FakeAMCL::y.
Referenced by generation().
CCSCC()
std::vector< ReedsSheppCurve::RSPath > rmp::common::geometry::ReedsSheppCurve::CCSCC (double x, double y, double phi)
# 4 Circle-Circle(pi/2)-Straight–Circle(pi/2)-Circle generation mode (using reflect, timeflip and backwards).
Parameters
x/y Goal position
phi Goal pose
Returns
Reeds-Shepp Paths
 {
   std::vector<RSPath> paths;
   RSLength length;
   double t, u, v;
   bool flag;
   // L+R-(pi/2)S-L-(pi/2)R+
   flag = LRSLR(x, y, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, -0.5 * M_PI, u, -0.5 * M_PI, v },
                       { REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_S, REEDS_SHEPP_L, REEDS_SHEPP_R } });
   }
   // timefilp: L-R+(pi/2)S+L+(pi/2)R-
   flag = LRSLR(-x, y, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -t, 0.5 * M_PI, -u, 0.5 * M_PI, -v },
                       { REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_S, REEDS_SHEPP_L, REEDS_SHEPP_R } });
   }
   // reflect: R+L-(pi/2)S-R-(pi/2)L+
   flag = LRSLR(x, -y, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, -0.5 * M_PI, u, -0.5 * M_PI, v },
                       { REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_S, REEDS_SHEPP_R, REEDS_SHEPP_L } });
   }
   // timefilp + reflect: R-L+(pi/2)S+R+(pi/2)L-
   flag = LRSLR(-x, -y, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -t, 0.5 * M_PI, -u, 0.5 * M_PI, -v },
                       { REEDS_SHEPP_R, REEDS_SHEPP_L, REEDS_SHEPP_S, REEDS_SHEPP_R, REEDS_SHEPP_L } });
   }
   return paths;
 }
References LRSLR(), REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_S, FakeAMCL::x, and FakeAMCL::y.
Referenced by generation().
CSC()
std::vector< ReedsSheppCurve::RSPath > rmp::common::geometry::ReedsSheppCurve::CSC (double x, double y, double phi)
# 8 Circle-Straight-Circle generation mode(using reflect, timeflip and backwards).
Parameters
x/y Goal position
phi Goal pose
Returns
Reeds-Shepp Paths
 {
   std::vector<RSPath> paths;
   RSLength length;
   double t, u, v;
   bool flag;
   // L+S+L+
   flag = LSL(x, y, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, u, v }, { REEDS_SHEPP_L, REEDS_SHEPP_S, REEDS_SHEPP_L } });
   }
   // timefilp: L-S-L-
   flag = LSL(-x, y, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -t, -u, -v }, { REEDS_SHEPP_L, REEDS_SHEPP_S, REEDS_SHEPP_L } });
   }
   // reflect: R+S+R+
   flag = LSL(x, -y, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, u, v }, { REEDS_SHEPP_R, REEDS_SHEPP_S, REEDS_SHEPP_R } });
   }
   // timeflip + reflect: R-S-R-
   flag = LSL(-x, -y, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -t, -u, -v }, { REEDS_SHEPP_R, REEDS_SHEPP_S, REEDS_SHEPP_R } });
   }
   // L+S+R+
   flag = LSR(x, y, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, u, v }, { REEDS_SHEPP_L, REEDS_SHEPP_S, REEDS_SHEPP_R } });
   }
   // timefilp: L-S-R-
   flag = LSR(-x, y, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -t, -u, -v }, { REEDS_SHEPP_L, REEDS_SHEPP_S, REEDS_SHEPP_R } });
   }
   // reflect: R+S+L+
   flag = LSR(x, -y, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, u, v }, { REEDS_SHEPP_R, REEDS_SHEPP_S, REEDS_SHEPP_L } });
   }
   // timeflip + reflect: R+S+l-
   flag = LSR(-x, -y, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { -t, -u, -v }, { REEDS_SHEPP_R, REEDS_SHEPP_S, REEDS_SHEPP_L } });
   }
   return paths;
 }
References LSL(), LSR(), REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_S, FakeAMCL::x, and FakeAMCL::y.
Referenced by generation().
generation()
Points2d rmp::common::geometry::ReedsSheppCurve::generation (Point3d start, Point3d goal)
Generate the path.
Parameters
start Initial pose (x, y, yaw)
goal Target pose (x, y, yaw)
Returns
path The smoothed trajectory points
 {
   Points2d path;
   double sx = start.x(), sy = start.y(), syaw = start.theta();
   double gx = goal.x(), gy = goal.y(), gyaw = goal.theta();
   // coordinate transformation
   double dx = gx - sx;
   double dy = gy - sy;
   double dyaw = gyaw - syaw;
   double x = (cos(syaw) * dx + sin(syaw) * dy) * max_curv_;
   double y = (-sin(syaw) * dx + cos(syaw) * dy) * max_curv_;
   // select the best motion
   RSPath best_path({ std::numeric_limits<double>::max() }, { REEDS_SHEPP_NONE });
   _update(SCS(x, y, dyaw), best_path);
   _update(CCC(x, y, dyaw), best_path);
   _update(CSC(x, y, dyaw), best_path);
   _update(CCCC(x, y, dyaw), best_path);
   _update(CCSC(x, y, dyaw), best_path);
   _update(CCSCC(x, y, dyaw), best_path);
   if (best_path.len() == std::numeric_limits<double>::max())
     return path;
   // interpolation
   int points_num = int(best_path.len() / step_) + 6;
   std::vector<double> path_x(points_num);
   std::vector<double> path_y(points_num);
   std::vector<double> path_yaw(points_num);
   int i = 0;
   for (size_t j = 0; j < best_path.size(); j++)
   {
     int m;
     double seg_length;
     best_path.get(j, seg_length, m);
     // path increment
     double d_l = seg_length > 0.0 ? step_ : -step_;
     double x = path_x[i];
     double y = path_y[i];
     double yaw = path_yaw[i];
     // current path length
     double l = d_l;
     while (fabs(l) <= fabs(seg_length))
     {
       i += 1;
       auto pt = interpolate(m, l, { x, y, yaw });
       path_x[i] = pt.x(), path_y[i] = pt.y(), path_yaw[i] = pt.theta();
       l += d_l;
     }
     i += 1;
     auto pt = interpolate(m, seg_length, { x, y, yaw });
     path_x[i] = pt.x(), path_y[i] = pt.y(), path_yaw[i] = pt.theta();
   }
   // remove unused data
   while ((path_x.size() >= 1) && (path_x.back() == 0.0))
   {
     path_x.pop_back();
     path_y.pop_back();
     path_yaw.pop_back();
   }
   // coordinate transformation
   for (size_t i = 0; i < path_x.size(); i++)
     path.push_back({ cos(-syaw) * path_x[i] + sin(-syaw) * path_y[i] + sx,
                      -sin(-syaw) * path_x[i] + cos(-syaw) * path_y[i] + sy });
   return path;
 }
References _update(), CCC(), CCCC(), CCSC(), CCSCC(), CSC(), Trans_DDQN_play::int, interpolate(), max_curv_, REEDS_SHEPP_NONE, SCS(), rmp::common::geometry::Curve::step_, rmp::common::geometry::Point3_< T >::theta(), FakeAMCL::x, rmp::common::geometry::Point3_< T >::x(), FakeAMCL::y, and rmp::common::geometry::Point3_< T >::y().
Referenced by run().
interpolate()
Point3d rmp::common::geometry::ReedsSheppCurve::interpolate (int mode, double length, Point3d init_pose)
Planning path interpolation.
Parameters
mode motion, i.e., REEDS_SHEPP_L, REEDS_SHEPP_S, REEDS_SHEPP_R
length Single step motion path length
init_pose Initial pose (x, y, yaw)
Returns
new_pose New pose (new_x, new_y, new_yaw) after moving
 {
   double new_x, new_y, new_yaw;
   double x = init_pose.x(), y = init_pose.y(), yaw = init_pose.theta();
   if (mode == REEDS_SHEPP_S)
   {
     new_x = x + length / max_curv_ * cos(yaw);
     new_y = y + length / max_curv_ * sin(yaw);
     new_yaw = yaw;
   }
   else if (mode == REEDS_SHEPP_L)
   {
     new_x = x + (sin(yaw + length) - sin(yaw)) / max_curv_;
     new_y = y - (cos(yaw + length) - cos(yaw)) / max_curv_;
     new_yaw = yaw + length;
   }
   else if (mode == REEDS_SHEPP_R)
   {
     new_x = x - (sin(yaw - length) - sin(yaw)) / max_curv_;
     new_y = y + (cos(yaw - length) - cos(yaw)) / max_curv_;
     new_yaw = yaw - length;
   }
   else
     std::cerr << "Error mode" << std::endl;
   return { new_x, new_y, new_yaw };
 }
References max_curv_, REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_S, rmp::common::geometry::Point3_< T >::theta(), FakeAMCL::x, rmp::common::geometry::Point3_< T >::x(), FakeAMCL::y, and rmp::common::geometry::Point3_< T >::y().
Referenced by generation().
LRL()
bool rmp::common::geometry::ReedsSheppCurve::LRL (double x, double y, double phi, RSLength & length)
Left-Right-Left generation mode. (L+R-L-)
 {
   double r, theta;
   R(x - sin(phi), y - 1.0 + cos(phi), r, theta);
   if (r <= 4.0)
   {
     double u = -2.0 * asin(0.25 * r);
     double t = M(theta + 0.5 * u + M_PI);
     double v = M(phi - t + u);
     if ((t >= 0.0) && (u <= 0.0))
     {
       length = { t, u, v };
       return true;
     }
   }
   length = { REEDS_SHEPP_NONE, REEDS_SHEPP_NONE, REEDS_SHEPP_NONE };
   return false;
 }
References M(), rviz_generate::r, R(), REEDS_SHEPP_NONE, FakeAMCL::x, and FakeAMCL::y.
Referenced by CCC().
LRLRn()
bool rmp::common::geometry::ReedsSheppCurve::LRLRn (double x, double y, double phi, RSLength & length)
Left-Right(beta)-Left(beta)-Right generation mode. (L+R+L-R-)
 {
   double xi = x + sin(phi);
   double eta = y - 1.0 - cos(phi);
   double rho = 0.25 * (2.0 + sqrt(xi * xi + eta * eta));
   if (rho <= 1.0)
   {
     double u = acos(rho);
     double t, v;
     _calTauOmega(u, -u, xi, eta, phi, t, v);
     if ((t >= 0.0) && (v <= 0.0))
     {
       length = { t, u, v };
       return true;
     }
   }
   length = { REEDS_SHEPP_NONE, REEDS_SHEPP_NONE, REEDS_SHEPP_NONE };
   return false;
 }
References _calTauOmega(), REEDS_SHEPP_NONE, FakeAMCL::x, and FakeAMCL::y.
Referenced by CCCC().
LRLRp()
bool rmp::common::geometry::ReedsSheppCurve::LRLRp (double x, double y, double phi, RSLength & length)
Left-Right(beta)-Left(beta)-Right generation mode. (L+R-L-R+)
 {
   double xi = x + sin(phi);
   double eta = y - 1.0 - cos(phi);
   double rho = (20.0 - xi * xi - eta * eta) / 16.0;
   if ((rho >= 0.0) && (rho <= 1.0))
   {
     double u = -acos(rho);
     if (u >= -0.5 * M_PI)
     {
       double t, v;
       _calTauOmega(u, u, xi, eta, phi, t, v);
       if ((t >= 0.0) && (v >= 0.0))
       {
         length = { t, u, v };
         return true;
       }
     }
   }
   length = { REEDS_SHEPP_NONE, REEDS_SHEPP_NONE, REEDS_SHEPP_NONE };
   return false;
 }
References _calTauOmega(), REEDS_SHEPP_NONE, FakeAMCL::x, and FakeAMCL::y.
Referenced by CCCC().
LRSL()
bool rmp::common::geometry::ReedsSheppCurve::LRSL (double x, double y, double phi, RSLength & length)
Left-Right(pi/2)-Straight-Left generation mode. (L+R-S-L-)
 {
   double xi = x - sin(phi);
   double eta = y - 1.0 + cos(phi);
   double rho, theta;
   R(xi, eta, rho, theta);
   if (rho >= 2.0)
   {
     double r = sqrt(rho * rho - 4.0);
     double u = 2.0 - r;
     double t = M(theta + atan2(r, -2.0));
     double v = M(phi - 0.5 * M_PI - t);
     if ((t >= 0.0) && (u <= 0.0) && (v <= 0.0))
     {
       length = { t, u, v };
       return true;
     }
   }
   length = { REEDS_SHEPP_NONE, REEDS_SHEPP_NONE, REEDS_SHEPP_NONE };
   return false;
 }
References M(), rviz_generate::r, R(), REEDS_SHEPP_NONE, FakeAMCL::x, and FakeAMCL::y.
Referenced by CCSC().
LRSLR()
bool rmp::common::geometry::ReedsSheppCurve::LRSLR (double x, double y, double phi, RSLength & length)
Left-Right(pi/2)-Straight-Left(pi/2)-Right generation mode. (L+R-S-L-R+)
 {
   double xi = x + sin(phi);
   double eta = y - 1.0 - cos(phi);
   double r, theta;
   R(xi, eta, r, theta);
   if (r >= 2.0)
   {
     double u = 4.0 - sqrt(r * r - 4.0);
     if (u <= 0.0)
     {
       double t = M(atan2((4.0 - u) * xi - 2.0 * eta, -2.0 * xi + (u - 4.0) * eta));
       double v = M(t - phi);
       if ((t >= 0.0) && (v >= 0.0))
       {
         length = { t, u, v };
         return true;
       }
     }
   }
   length = { REEDS_SHEPP_NONE, REEDS_SHEPP_NONE, REEDS_SHEPP_NONE };
   return false;
 }
References M(), rviz_generate::r, R(), REEDS_SHEPP_NONE, FakeAMCL::x, and FakeAMCL::y.
Referenced by CCSCC().
LRSR()
bool rmp::common::geometry::ReedsSheppCurve::LRSR (double x, double y, double phi, RSLength & length)
Left-Right(pi/2)-Straight-Right generation mode. (L+R-S-R-)
 {
   double xi = x + sin(phi);
   double eta = y - 1.0 - cos(phi);
   double rho, theta;
   R(-eta, xi, rho, theta);
   if (rho >= 2.0)
   {
     double t = theta;
     double u = 2.0 - rho;
     double v = M(t + 0.5 * M_PI - phi);
     if ((t >= 0.0) && (u <= 0.0) && (v <= 0.0))
     {
       length = { t, u, v };
       return true;
     }
   }
   length = { REEDS_SHEPP_NONE, REEDS_SHEPP_NONE, REEDS_SHEPP_NONE };
   return false;
 }
References M(), R(), REEDS_SHEPP_NONE, FakeAMCL::x, and FakeAMCL::y.
Referenced by CCSC().
LSL()
bool rmp::common::geometry::ReedsSheppCurve::LSL (double x, double y, double phi, RSLength & length)
Left-Straight-Left generation mode. (L+S+L+)
 {
   double u, t;
   R(x - sin(phi), y - 1.0 + cos(phi), u, t);
   if (t >= 0.0)
   {
     double v = M(phi - t);
     if (v >= 0.0)
     {
       length = { t, u, v };
       return true;
     }
   }
   length = { REEDS_SHEPP_NONE, REEDS_SHEPP_NONE, REEDS_SHEPP_NONE };
   return false;
 }
References M(), R(), REEDS_SHEPP_NONE, FakeAMCL::x, and FakeAMCL::y.
Referenced by CSC().
LSR()
bool rmp::common::geometry::ReedsSheppCurve::LSR (double x, double y, double phi, RSLength & length)
Left-Straight-Right generation mode. (L+S+R+)
 {
   double r, theta;
   R(x + sin(phi), y - 1.0 - cos(phi), r, theta);
   r = r * r;
   if (r >= 4.0)
   {
     double u = sqrt(r - 4.0);
     double t = M(theta + atan2(2.0, u));
     double v = M(t - phi);
     if ((t >= 0.0) && (v >= 0.0))
     {
       length = { t, u, v };
       return true;
     }
   }
   length = { REEDS_SHEPP_NONE, REEDS_SHEPP_NONE, REEDS_SHEPP_NONE };
   return false;
 }
References M(), rviz_generate::r, R(), REEDS_SHEPP_NONE, FakeAMCL::x, and FakeAMCL::y.
Referenced by CSC().
M()
double rmp::common::geometry::ReedsSheppCurve::M (double theta)
Truncate the angle to the interval of -π to π.
 {
   return rmp::common::math::pi2pi(theta);
 }
References rmp::common::math::pi2pi().
Referenced by _calTauOmega(), LRL(), LRSL(), LRSLR(), LRSR(), LSL(), LSR(), and SLS().
R()
void rmp::common::geometry::ReedsSheppCurve::R (double x, double y, double & r, double & theta)
Return the polar coordinates (r, theta) of the point (x, y), i.e. rcos(theta) = x; rsin(theta) = y.
 {
   r = hypot(x, y);
   theta = atan2(y, x);
 }
References rviz_generate::r, FakeAMCL::x, and FakeAMCL::y.
Referenced by LRL(), LRSL(), LRSLR(), LRSR(), LSL(), and LSR().
run() [1/2]
bool rmp::common::geometry::ReedsSheppCurve::run (const Points2d points, Points2d & path) virtual
Running trajectory generation.
Parameters
points path points <x, y>
path generated trajectory
Returns
true if generate successfully, else failed
Implements rmp::common::geometry::Curve.
 {
   if (points.size() < 4)
     return false;
   else
   {
     Points3d poses;
     poses.emplace_back(points.begin()->x(), points.begin()->y(), 0);
     for (size_t i = 1; i < points.size() - 1; i++)
     {
       double theta1 = std::atan2(points[i].y() - points[i - 1].y(), points[i].x() - points[i - 1].x());
       double theta2 = std::atan2(points[i + 1].y() - points[i].y(), points[i + 1].x() - points[i].x());
       poses.emplace_back(points[i].x(), points[i].y(), (theta1 + theta2) / 2);
     }
     poses.emplace_back(points.back().x(), points.back().y(), 0);
     return run(poses, path);
   }
 }
References FakeAMCL::x, and FakeAMCL::y.
run() [2/2]
bool rmp::common::geometry::ReedsSheppCurve::run (const Points3d points, Points2d & path) virtual
Running trajectory generation.
Parameters
points path points <x, y, theta>
path generated trajectory
Returns
true if generate successfully, else failed
Implements rmp::common::geometry::Curve.
 {
   if (points.size() < 4)
     return false;
   else
   {
     path.clear();
     for (size_t i = 0; i < points.size() - 1; i++)
     {
       Points2d path_i = generation(points[i], points[i + 1]);
       if (!path_i.empty())
         path.insert(path.end(), path_i.begin(), path_i.end());
     }
     return !path.empty();
   }
 }
References generation().
SCS()
std::vector< ReedsSheppCurve::RSPath > rmp::common::geometry::ReedsSheppCurve::SCS (double x, double y, double phi)
# 2 Straight-Circle-Straight generation mode(using reflect).
Parameters
x/y Goal position
phi Goal pose
Returns
Reeds-Shepp Paths
 {
   std::vector<RSPath> paths;
   RSLength length;
   double t, u, v;
   bool flag;
   flag = SLS(x, y, phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, u, v }, { REEDS_SHEPP_S, REEDS_SHEPP_L, REEDS_SHEPP_S } });
   }
   flag = SLS(x, -y, -phi, length);
   if (flag)
   {
     std::tie(t, u, v) = length;
     paths.push_back({ { t, u, v }, { REEDS_SHEPP_S, REEDS_SHEPP_R, REEDS_SHEPP_S } });
   }
   return paths;
 }
References REEDS_SHEPP_L, REEDS_SHEPP_R, REEDS_SHEPP_S, SLS(), FakeAMCL::x, and FakeAMCL::y.
Referenced by generation().
setMaxCurv()
void rmp::common::geometry::ReedsSheppCurve::setMaxCurv (double max_curv)
Configure the maximum curvature.
Parameters
max_curv the maximum curvature
 {
   assert(max_curv > 0);
   max_curv_ = max_curv;
 }
References max_curv_.
SLS()
bool rmp::common::geometry::ReedsSheppCurve::SLS (double x, double y, double phi, RSLength & length)
Straight-Left-Straight generation mode.
 {
   phi = M(phi);
   if ((y > 0.0) && (phi > 0.0) && (phi < M_PI * 0.99))
   {
     double xd = -y / tan(phi) + x;
     double t = xd - tan(phi / 2.0);
     double u = phi;
     double v = sqrt((x - xd) * (x - xd) + y * y) - tan(phi / 2.0);
     length = { t, u, v };
     return true;
   }
   else if ((y < 0.0) && (phi > 0.0) && (phi < M_PI * 0.99))
   {
     double xd = -y / tan(phi) + x;
     double t = xd - tan(phi / 2.0);
     double u = phi;
     double v = -sqrt((x - xd) * (x - xd) + y * y) - tan(phi / 2.0);
     length = { t, u, v };
     return true;
   }
   length = { REEDS_SHEPP_NONE, REEDS_SHEPP_NONE, REEDS_SHEPP_NONE };
   return false;
 }
References M(), REEDS_SHEPP_NONE, FakeAMCL::x, and FakeAMCL::y.
Referenced by SCS().
Member Data Documentation
max_curv_
double rmp::common::geometry::ReedsSheppCurve::max_curv_ protected
Referenced by generation(), interpolate(), and setMaxCurv().
The documentation for this class was generated from the following files:
src/core/common/include/common/geometry/reeds_shepp_curve.h
src/core/common/src/geometry/reeds_shepp_curve.cpp