ROS Motion Planning: rmp::path_planner::QuickInformedRRTStarPathPlanner Class Reference
rmp::path_planner::QuickInformedRRTStarPathPlanner Class Reference
Class for objects that plan using the Informed RRT* algorithm.
#include <quick_informed_rrt_star_planner.h>
Public Member Functions
QuickInformedRRTStarPathPlanner (costmap_2d::Costmap2DROS *costmap_ros, int sample_num, double max_dist, double r, double r_set, int n_threads, double d_extend, double t_freedom)
Constructor.
bool plan (const Point3d &start, const Point3d &goal, Points3d &path, Points3d &expand)
RRT implementation.
Public Member Functions inherited from rmp::path_planner::InformedRRTStarPathPlanner
InformedRRTStarPathPlanner (costmap_2d::Costmap2DROS *costmap_ros, int sample_num, double max_dist, double r)
Constructor.
Public Member Functions inherited from rmp::path_planner::RRTStarPathPlanner
RRTStarPathPlanner (costmap_2d::Costmap2DROS *costmap_ros, int sample_num, double max_dist, double r)
Constructor.
bool plan (const Point3d &start, const Point3d &goal, Points3d &path, Points3d &expand)
RRT implementation.
Public Member Functions inherited from rmp::path_planner::RRTPathPlanner
RRTPathPlanner (costmap_2d::Costmap2DROS *costmap_ros, int sample_num, double max_dist)
Constructor.
Public Member Functions inherited from rmp::path_planner::PathPlanner
PathPlanner (costmap_2d::Costmap2DROS *costmap_ros)
Construct a new Global PathPlanner object.
virtual ~PathPlanner ()=default
Destroy the Global PathPlanner object.
void setFactor (float factor)
Set or reset obstacle factor.
costmap_2d::Costmap2D * getCostMap () const
get the costmap
int getMapSize () const
get the size of costmap
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap ()
Inflate the boundary of costmap into obstacles to prevent cross planning.
Protected Member Functions
Node _generateRandomNode (int mu, std::vector< Node > path)
Generates a random node.
Node _findNearestPoint (std::unordered_map< int, Node > list, Node &node)
Regular the new node by the nearest node in the sample list.
Protected Member Functions inherited from rmp::path_planner::InformedRRTStarPathPlanner
Node _transform (double x, double y)
Sample in ellipse.
Node _generateRandomNode ()
Generates a random node.
Protected Member Functions inherited from rmp::path_planner::RRTStarPathPlanner
Node _findNearestPoint (std::unordered_map< int, Node > &list, Node &node)
Regular the new node by the nearest node in the sample list.
Protected Member Functions inherited from rmp::path_planner::RRTPathPlanner
Node _findNearestPoint (std::unordered_map< int, Node > &list, const Node &node)
Regular the sample node by the nearest node in the sample list.
Node _generateRandomNode ()
Generates a random node.
bool _checkGoal (const Node &new_node)
Check if goal is reachable from current node.
Protected Member Functions inherited from rmp::path_planner::PathPlanner
template<typename Node >
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
template<typename Node >
std::vector< Node > _convertBiClosedListToPath (std::unordered_map< int, Node > &f_closed_list, std::unordered_map< int, Node > &b_closed_list, const Node &start, const Node &goal, const Node &boundary)
Protected Attributes
double set_r_
int rewire_threads_
double step_extend_d_
double recover_max_dist_
double t_distr_freedom_
Protected Attributes inherited from rmp::path_planner::InformedRRTStarPathPlanner
double c_best_
double c_min_
Protected Attributes inherited from rmp::path_planner::RRTStarPathPlanner
double r_
Protected Attributes inherited from rmp::path_planner::RRTPathPlanner
Node start_
Node goal_
std::unordered_map< int, Node > sample_list_
int sample_num_
double max_dist_
double opti_sample_p_ = 0.05
Protected Attributes inherited from rmp::path_planner::PathPlanner
int map_size_
float factor_
costmap_2d::Costmap2DROS * costmap_ros_
costmap_2d::Costmap2D * costmap_
Private Types
using Node = rmp::common::structure::Node< int >
Additional Inherited Members
Public Types inherited from rmp::path_planner::PathPlanner
using Point2d = rmp::common::geometry::Point2d
using Point3d = rmp::common::geometry::Point3d
using Points2d = rmp::common::geometry::Points2d
using Points3d = rmp::common::geometry::Points3d
Detailed Description
Class for objects that plan using the Informed RRT* algorithm.
Member Typedef Documentation
Node
using rmp::path_planner::QuickInformedRRTStarPathPlanner::Node = rmp::common::structure::Node<int> private
Constructor & Destructor Documentation
QuickInformedRRTStarPathPlanner()
rmp::path_planner::QuickInformedRRTStarPathPlanner::QuickInformedRRTStarPathPlanner (costmap_2d::Costmap2DROS * costmap_ros, int sample_num, double max_dist, double r, double r_set, int n_threads, double d_extend, double t_freedom)
Constructor.
Parameters
costmap the environment for path planning
sample_num andom sample points
max_dist max distance between sample points
r optimization radius
costmap the environment for path planning
max_dist max distance between sample points
   : InformedRRTStarPathPlanner(costmap_ros, sample_num, max_dist, r)
   , set_r_(r_set)
   , rewire_threads_(n_threads)
   , step_extend_d_(d_extend)
   , recover_max_dist_(max_dist)
   , t_distr_freedom_(t_freedom)
 {
 }
Member Function Documentation
_findNearestPoint()
QuickInformedRRTStarPathPlanner::Node rmp::path_planner::QuickInformedRRTStarPathPlanner::_findNearestPoint (std::unordered_map< int, Node > list, Node & node) protected
Regular the new node by the nearest node in the sample list.
Parameters
list sample list
node sample node
Returns
nearest node
 {
   Node nearest_node, new_node(node);
   double min_dist = std::numeric_limits<double>::max();
   for (const auto p : list)
   {
     // calculate distance
     double new_dist = std::hypot(p.second.x() - new_node.x(), p.second.y() - new_node.y());
     // update nearest node
     if (new_dist < min_dist)
     {
       nearest_node = p.second;
       new_node.set_pid(nearest_node.id());
       new_node.set_g(new_dist + p.second.g());
       min_dist = new_dist;
     }
   }
   // distance longer than the threshold
   if (min_dist > max_dist_)
   {
     // connect sample node and nearest node, then move the nearest node
     // forward to sample node with `max_distance` as result
     double theta = std::atan2(new_node.y() - nearest_node.y(), new_node.x() - nearest_node.x());
     new_node.set_x(nearest_node.x() + (int)(max_dist_ * cos(theta)));
     new_node.set_y(nearest_node.y() + (int)(max_dist_ * sin(theta)));
     new_node.set_id(grid2Index(new_node.x(), new_node.y()));
     new_node.set_g(max_dist_ + nearest_node.g());
   }
   // obstacle check
   auto isCollision = [&](const Node& node1, const Node& node2) {
     return CollisionChecker::BresenhamCollisionDetection(node1, node2, [&](const Node& node) {
       return costmap_->getCharMap()[grid2Index(node.x(), node.y())] >= costmap_2d::LETHAL_OBSTACLE * factor_;
     });
   };
   if (!isCollision(new_node, nearest_node))
   {
     max_dist_ += step_extend_d_;
     // parallel rewire optimization
     std::vector<int> v_iters;
     for (auto p : sample_list_)
     {
       v_iters.push_back(p.first);
     }
 #pragma omp parallel for num_threads(rewire_threads_)
     for (size_t i = 0; i < v_iters.size(); i++)
     {
       auto& p = sample_list_[v_iters[i]];
       // inside the optimization circle
       double new_dist = std::hypot(p.x() - new_node.x(), p.y() - new_node.y());
       if (new_dist > r_)
         continue;
       double cost = p.g() + new_dist;
       // update new sample node's cost and parent
       if (new_node.g() > cost)
       {
         if (!isCollision(new_node, p))
         {
           // other thread may update new_node.g()
 #pragma omp critical
           if (new_node.g() > cost)
           {
             new_node.set_pid(p.id());
             new_node.set_g(cost);
           }
         }
       }
       else
       {
         // update nodes' cost inside the radius
         cost = new_node.g() + new_dist;
         if (cost < p.g())
           if (!isCollision(new_node, p))
           {
             p.set_pid(new_node.id());
             p.set_g(cost);
           }
       }
     }
   }
   else
   {
     max_dist_ = recover_max_dist_;
     new_node.set_id(-1);
   }
   return new_node;
 }
References rmp::path_planner::PathPlanner::costmap_, rmp::path_planner::PathPlanner::factor_, rmp::common::structure::Node< T >::g(), rmp::path_planner::PathPlanner::grid2Index(), rmp::common::structure::Node< T >::id(), rmp::path_planner::RRTPathPlanner::max_dist_, tf_map2odom::node, rmp::path_planner::RRTStarPathPlanner::r_, recover_max_dist_, rmp::path_planner::RRTPathPlanner::sample_list_, rmp::common::structure::Node< T >::set_g(), rmp::common::structure::Node< T >::set_id(), rmp::common::structure::Node< T >::set_pid(), rmp::common::structure::Node< T >::set_x(), rmp::common::structure::Node< T >::set_y(), step_extend_d_, rmp::common::structure::Node< T >::x(), and rmp::common::structure::Node< T >::y().
Referenced by plan().
_generateRandomNode()
QuickInformedRRTStarPathPlanner::Node rmp::path_planner::QuickInformedRRTStarPathPlanner::_generateRandomNode (int mu, std::vector< Node > path) protected
Generates a random node.
Returns
Generated node
Parameters
mu
path
Returns
Generated node
 {
   std::random_device rd;
   std::mt19937 eng(rd());
   std::student_t_distribution<> t_distr(t_distr_freedom_);
   if (std::abs(t_distr(eng)) < mu && path.size() != 0)  // sample in priority circles
   {
     int wc = rand() % path.size();
     std::uniform_real_distribution<float> p(-set_r_, set_r_);
     int cx = path[wc].x() + p(eng);
     int cy = path[wc].y() + p(eng);
     return Node(cx, cy, 0, 0, grid2Index(cx, cy), 0);
   }
   else  // ellipse sample
   {
     if (c_best_ < std::numeric_limits<double>::max())
     {
       while (true)
       {
         // unit ball sample
         double x, y;
         std::uniform_real_distribution<float> p(-1, 1);
         while (true)
         {
           x = p(eng);
           y = p(eng);
           if (x * x + y * y < 1)
             break;
         }
         // transform to ellipse
         Node temp = _transform(x, y);
         if (temp.id() < map_size_ - 1)
           return temp;
       }
     }
     else
       return RRTStarPathPlanner::_generateRandomNode();
   }
 }
References rmp::path_planner::RRTPathPlanner::_generateRandomNode(), rmp::path_planner::InformedRRTStarPathPlanner::_transform(), rmp::common::math::abs(), rmp::path_planner::InformedRRTStarPathPlanner::c_best_, rmp::path_planner::PathPlanner::grid2Index(), rmp::common::structure::Node< T >::id(), rmp::path_planner::PathPlanner::map_size_, set_r_, t_distr_freedom_, FakeAMCL::x, and FakeAMCL::y.
plan()
bool rmp::path_planner::QuickInformedRRTStarPathPlanner::plan (const Point3d & start, const Point3d & goal, Points3d & path, Points3d & expand) virtual
RRT implementation.
Informed RRT* implementation.
Parameters
start start node
goal goal node
expand containing the node been search during the process
Returns
tuple contatining a bool as to whether a path was found, and the path
Reimplemented from rmp::path_planner::InformedRRTStarPathPlanner.
 {
   path.clear();
   expand.clear();
   // initialization
   c_best_ = std::numeric_limits<double>::max();
   c_min_ = std::hypot(start.x() - goal.x(), start.y() - goal.y());
   int best_parent = -1;
   sample_list_.clear();
   // copy
   start_.set_x(start.x());
   start_.set_y(start.y());
   start_.set_id(grid2Index(start_.x(), start_.y()));
   goal_.set_x(goal.x());
   goal_.set_y(goal.y());
   goal_.set_id(grid2Index(goal_.x(), goal_.y()));
   sample_list_.insert(std::make_pair(start_.id(), start_));
   expand.emplace_back(start.x(), start.y(), 0);
   // adaptive sampling bias
   double dist_s2g = c_min_;
   double dist_m2g = dist_s2g * 0.95;
   // priority circles set
   double mu = 0.0;
   int mu_cnt = 0;
   // main loop
   int iteration = 0;
   std::vector<Node> nodes;
   while (iteration < sample_num_)
   {
     iteration++;
     // update probability of sampling bias
     opti_sample_p_ = std::min(0.75, 1 - dist_m2g / dist_s2g);
     // generate a random node in the map
     Node sample_node = _generateRandomNode(mu, nodes);
     // obstacle
     if (costmap_->getCharMap()[sample_node.id()] >= costmap_2d::LETHAL_OBSTACLE * factor_)
       continue;
     // visited
     if (sample_list_.find(sample_node.id()) != sample_list_.end())
       continue;
     // regular the sample node
     Node new_node = _findNearestPoint(sample_list_, sample_node);
     if (new_node.id() == -1)
       continue;
     else
     {
       sample_list_.insert(std::make_pair(new_node.id(), new_node));
       expand.emplace_back(new_node.x(), new_node.y(), new_node.pid());
     }
     auto dist_ = std::hypot(new_node.x() - goal_.x(), new_node.y() - goal_.y());
     // update min dist from tree to goal
     if (dist_ < dist_m2g)
       dist_m2g = dist_;
     // goal found
     auto isCollision = [&](const Node& node1, const Node& node2) {
       return CollisionChecker::BresenhamCollisionDetection(node1, node2, [&](const Node& node) {
         return costmap_->getCharMap()[grid2Index(node.x(), node.y())] >= costmap_2d::LETHAL_OBSTACLE * factor_;
       });
     };
     if (dist_ <= max_dist_ && !isCollision(new_node, goal_))
     {
       double cost = dist_ + new_node.g();
       if (cost < c_best_)
       {
         best_parent = new_node.id();
         c_best_ = cost;
         // update path
         Node goal_star(goal_.x(), goal_.y(), c_best_, 0, grid2Index(goal_.x(), goal_.y()), best_parent);
         sample_list_.insert(std::make_pair(goal_star.id(), goal_star));
         nodes = _convertClosedListToPath<Node>(sample_list_, start_, goal_);
         sample_list_.erase(goal_star.id());
         mu = std::fmin(5, mu + 0.5);
       }
     }
     else  // if do not update, decrease mu termly
     {
       mu_cnt++;
       if (mu_cnt % 100 == 0)
         mu = std::fmax(0, mu - 0.5);
     }
   }
   if (best_parent != -1)
   {
     Node goal_star(goal_.x(), goal_.y(), c_best_, 0, grid2Index(goal_.x(), goal_.y()), best_parent);
     sample_list_.insert(std::make_pair(goal_star.id(), goal_star));
     const auto& backtrace = _convertClosedListToPath<Node>(sample_list_, start_, goal_);
     for (auto iter = backtrace.rbegin(); iter != backtrace.rend(); ++iter)
     {
       path.emplace_back(iter->x(), iter->y());
     }
     return true;
   }
   return false;
 }
References _findNearestPoint(), rmp::path_planner::InformedRRTStarPathPlanner::_generateRandomNode(), rmp::path_planner::InformedRRTStarPathPlanner::c_best_, rmp::path_planner::InformedRRTStarPathPlanner::c_min_, rmp::path_planner::PathPlanner::costmap_, rmp::path_planner::PathPlanner::factor_, rmp::common::structure::Node< T >::g(), rmp::path_planner::RRTPathPlanner::goal_, rmp::path_planner::PathPlanner::grid2Index(), rmp::common::structure::Node< T >::id(), rmp::path_planner::RRTPathPlanner::max_dist_, tf_map2odom::node, rmp::path_planner::RRTPathPlanner::opti_sample_p_, rmp::common::structure::Node< T >::pid(), rmp::path_planner::RRTPathPlanner::sample_list_, rmp::path_planner::RRTPathPlanner::sample_num_, rmp::common::structure::Node< T >::set_id(), rmp::common::structure::Node< T >::set_x(), rmp::common::structure::Node< T >::set_y(), rmp::path_planner::RRTPathPlanner::start_, rmp::common::structure::Node< T >::x(), rmp::common::geometry::Point3_< T >::x(), rmp::common::structure::Node< T >::y(), and rmp::common::geometry::Point3_< T >::y().
Member Data Documentation
recover_max_dist_
double rmp::path_planner::QuickInformedRRTStarPathPlanner::recover_max_dist_ protected
Referenced by _findNearestPoint().
rewire_threads_
int rmp::path_planner::QuickInformedRRTStarPathPlanner::rewire_threads_ protected
set_r_
double rmp::path_planner::QuickInformedRRTStarPathPlanner::set_r_ protected
Referenced by _generateRandomNode().
step_extend_d_
double rmp::path_planner::QuickInformedRRTStarPathPlanner::step_extend_d_ protected
Referenced by _findNearestPoint().
t_distr_freedom_
double rmp::path_planner::QuickInformedRRTStarPathPlanner::t_distr_freedom_ protected
Referenced by _generateRandomNode().
The documentation for this class was generated from the following files:
src/core/path_planner/path_planner/include/path_planner/sample_planner/quick_informed_rrt_star_planner.h
src/core/path_planner/path_planner/src/sample_planner/quick_informed_rrt_star_planner.cpp