ROS Motion Planning: rmp::path_planner::VoronoiPathPlanner Class Reference
rmp::path_planner::VoronoiPathPlanner Class Reference
Class for objects that plan using the Voronoi-based planning algorithm.
#include <voronoi_planner.h>
Classes
struct VoronoiData
Public Member Functions
VoronoiPathPlanner (costmap_2d::Costmap2DROS *costmap_ros, double circumscribed_radius)
Construct a new Voronoi-based planning object.
~VoronoiPathPlanner ()
bool plan (const Point3d &start, const Point3d &goal, Points3d &path, Points3d &expand)
Voronoi-based planning implementation.
Public Member Functions inherited from rmp::path_planner::PathPlanner
PathPlanner (costmap_2d::Costmap2DROS *costmap_ros)
Construct a new Global PathPlanner object.
virtual ~PathPlanner ()=default
Destroy the Global PathPlanner object.
void setFactor (float factor)
Set or reset obstacle factor.
costmap_2d::Costmap2D * getCostMap () const
get the costmap
int getMapSize () const
get the size of costmap
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap ()
Inflate the boundary of costmap into obstacles to prevent cross planning.
Protected Member Functions
bool searchPathWithVoronoi (const Node &start, const Node &goal, std::vector< Node > &path, Node *v_goal=nullptr)
search the shortest path from start to VD, or search the shortest path in VD
Protected Member Functions inherited from rmp::path_planner::PathPlanner
template<typename Node >
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
template<typename Node >
std::vector< Node > _convertBiClosedListToPath (std::unordered_map< int, Node > &f_closed_list, std::unordered_map< int, Node > &b_closed_list, const Node &start, const Node &goal, const Node &boundary)
Private Types
using Node = rmp::common::structure::Node< int >
Private Member Functions
void _updateVoronoi ()
update voronoi object using costmap ROS wrapper
Private Attributes
DynamicVoronoi voronoi_
VoronoiData ** voronoi_diagram_
double circumscribed_radius_
const std::vector< Node > motions
Additional Inherited Members
Public Types inherited from rmp::path_planner::PathPlanner
using Point2d = rmp::common::geometry::Point2d
using Point3d = rmp::common::geometry::Point3d
using Points2d = rmp::common::geometry::Points2d
using Points3d = rmp::common::geometry::Points3d
Protected Attributes inherited from rmp::path_planner::PathPlanner
int map_size_
float factor_
costmap_2d::Costmap2DROS * costmap_ros_
costmap_2d::Costmap2D * costmap_
Detailed Description
Class for objects that plan using the Voronoi-based planning algorithm.
Member Typedef Documentation
Node
using rmp::path_planner::VoronoiPathPlanner::Node = rmp::common::structure::Node<int> private
Constructor & Destructor Documentation
VoronoiPathPlanner()
rmp::path_planner::VoronoiPathPlanner::VoronoiPathPlanner (costmap_2d::Costmap2DROS * costmap_ros, double circumscribed_radius)
Construct a new Voronoi-based planning object.
Parameters
costmap the environment for path planning
circumscribed_radius the circumscribed radius of robot
   : PathPlanner(costmap_ros), circumscribed_radius_(circumscribed_radius)
 {
   voronoi_diagram_ = new VoronoiData*[costmap_->getSizeInCellsX()];
   for (unsigned int i = 0; i < costmap_->getSizeInCellsX(); i++)
     voronoi_diagram_[i] = new VoronoiData[costmap_->getSizeInCellsY()];
 }
References rmp::path_planner::PathPlanner::costmap_, and voronoi_diagram_.
~VoronoiPathPlanner()
rmp::path_planner::VoronoiPathPlanner::~VoronoiPathPlanner ()
 {
   for (unsigned int i = 0; i < costmap_->getSizeInCellsX(); i++)
     delete[] voronoi_diagram_[i];
   delete[] voronoi_diagram_;
 }
References rmp::path_planner::PathPlanner::costmap_, and voronoi_diagram_.
Member Function Documentation
_updateVoronoi()
void rmp::path_planner::VoronoiPathPlanner::_updateVoronoi () private
update voronoi object using costmap ROS wrapper
 {
   bool voronoi_layer_exist = false;
   for (auto layer = costmap_ros_->getLayeredCostmap()->getPlugins()->begin();
        layer != costmap_ros_->getLayeredCostmap()->getPlugins()->end(); ++layer)
   {
     boost::shared_ptr<costmap_2d::VoronoiLayer> voronoi_layer =
         boost::dynamic_pointer_cast<costmap_2d::VoronoiLayer>(*layer);
     if (voronoi_layer)
     {
       voronoi_layer_exist = true;
       boost::unique_lock<boost::mutex> lock(voronoi_layer->getMutex());
       voronoi_ = voronoi_layer->getVoronoi();
       break;
     }
   }
   if (!voronoi_layer_exist)
   {
     ROS_ERROR("Failed to get a Voronoi layer for potentional application.");
   }
 }
References rmp::path_planner::PathPlanner::costmap_ros_, and voronoi_.
Referenced by plan().
plan()
bool rmp::path_planner::VoronoiPathPlanner::plan (const Point3d & start, const Point3d & goal, Points3d & path, Points3d & expand) virtual
Voronoi-based planning implementation.
Parameters
start start node
goal goal node
path optimal path consists of Node
expand containing the node been search during the process
Returns
true if path found, else false
Implements rmp::path_planner::PathPlanner.
 {
   // update voronoi diagram
   _updateVoronoi();
   for (unsigned int j = 0; j < costmap_->getSizeInCellsY(); j++)
   {
     for (unsigned int i = 0; i < costmap_->getSizeInCellsX(); i++)
     {
       voronoi_diagram_[i][j].dist = voronoi_.getDistance(i, j) * costmap_->getResolution();
       voronoi_diagram_[i][j].is_voronoi = voronoi_.isVoronoi(i, j);
     }
   }
   Node start_node(start.x(), start.y());
   Node goal_node(goal.x(), goal.y());
   start_node.set_id(grid2Index(start_node.x(), start_node.y()));
   goal_node.set_id(grid2Index(goal_node.x(), goal_node.y()));
   // clear vector
   path.clear();
   expand.clear();
   // start/goal to Voronoi Diagram, shortest path in Voronoi Diagram
   std::vector<Node> path_s, path_g, path_v;
   // start/goal point in Voronoi Diagram
   Node v_start, v_goal;
   if (!searchPathWithVoronoi(start_node, goal_node, path_s, &v_start))
     return false;
   if (!searchPathWithVoronoi(goal_node, start_node, path_g, &v_goal))
     return false;
   std::reverse(path_g.begin(), path_g.end());
   if (!searchPathWithVoronoi(v_start, v_goal, path_v))
     return false;
   path_g.insert(path_g.end(), path_v.begin(), path_v.end());
   path_g.insert(path_g.end(), path_s.begin(), path_s.end());
   for (auto iter = path_g.rbegin(); iter != path_g.rend(); iter++)
   {
     path.emplace_back(iter->x(), iter->y());
   }
   return true;
 }
References _updateVoronoi(), rmp::path_planner::PathPlanner::costmap_, rmp::path_planner::VoronoiPathPlanner::VoronoiData::dist, DynamicVoronoi::getDistance(), rmp::path_planner::PathPlanner::grid2Index(), rmp::path_planner::VoronoiPathPlanner::VoronoiData::is_voronoi, DynamicVoronoi::isVoronoi(), searchPathWithVoronoi(), rmp::common::structure::Node< T >::set_id(), voronoi_, voronoi_diagram_, rmp::common::structure::Node< T >::x(), rmp::common::geometry::Point3_< T >::x(), rmp::common::structure::Node< T >::y(), and rmp::common::geometry::Point3_< T >::y().
searchPathWithVoronoi()
bool rmp::path_planner::VoronoiPathPlanner::searchPathWithVoronoi (const Node & start, const Node & goal, std::vector< Node > & path, Node * v_goal = nullptr) protected
search the shortest path from start to VD, or search the shortest path in VD
Parameters
start start node
goal goal node
v_goal the voronoi node in VD which is closest to start node
path shortest path from start to VD
Returns
true if path found, else false
 {
   path.clear();
   // open list and closed list
   std::priority_queue<Node, std::vector<Node>, Node::compare_cost> open_list;
   std::unordered_map<int, Node> closed_list;
   open_list.push(start);
   while (!open_list.empty())
   {
     // pop current node from open list
     auto current = open_list.top();
     open_list.pop();
     // current node does not exist in closed list
     if (closed_list.find(current.id()) != closed_list.end())
       continue;
     closed_list.insert(std::make_pair(current.id(), current));
     // goal found
     if ((current == goal) ||
         (v_goal == nullptr ?
              false :
              voronoi_diagram_[static_cast<unsigned int>(current.x())][static_cast<unsigned int>(current.y())]
                  .is_voronoi))
     {
       path = _convertClosedListToPath(closed_list, start, current);
       if (v_goal != nullptr)
       {
         v_goal->set_x(current.x());
         v_goal->set_y(current.y());
         v_goal->set_id(current.id());
       }
       return true;
     }
     // explore neighbor of current node
     for (const auto& m : motions)
     {
       auto node_new = current + m;
       // current node do not exist in closed list
       if (closed_list.find(node_new.id()) != closed_list.end())
         continue;
       // explore a new node
       node_new.set_g(current.g() + m.g());
       node_new.set_id(grid2Index(node_new.x(), node_new.y()));
       node_new.set_pid(current.id());
       // next node hit the boundary or obstacle
       if ((node_new.id() < 0) || (node_new.id() >= map_size_) ||
           (voronoi_diagram_[static_cast<unsigned int>(node_new.x())][static_cast<unsigned int>(node_new.y())].dist <
            circumscribed_radius_))
         continue;
       // search in VD
       if ((v_goal == nullptr) &&
           (!voronoi_diagram_[static_cast<unsigned int>(node_new.x())][static_cast<unsigned int>(node_new.y())]
                 .is_voronoi))
         continue;
       node_new.set_h(std::hypot(node_new.x() - goal.x(), node_new.y() - goal.y()));
       open_list.push(node_new);
     }
   }
   return false;
 }
References rmp::path_planner::PathPlanner::_convertClosedListToPath(), circumscribed_radius_, rmp::path_planner::VoronoiPathPlanner::VoronoiData::dist, rmp::path_planner::PathPlanner::grid2Index(), rmp::path_planner::VoronoiPathPlanner::VoronoiData::is_voronoi, rmp::path_planner::PathPlanner::map_size_, motions, rmp::common::structure::Node< T >::set_id(), rmp::common::structure::Node< T >::set_x(), rmp::common::structure::Node< T >::set_y(), voronoi_diagram_, rmp::common::structure::Node< T >::x(), and rmp::common::structure::Node< T >::y().
Referenced by plan().
Member Data Documentation
circumscribed_radius_
double rmp::path_planner::VoronoiPathPlanner::circumscribed_radius_ private
Referenced by searchPathWithVoronoi().
motions
const std::vector<Node> rmp::path_planner::VoronoiPathPlanner::motions private
Initial value:
= {
    { 0, 1, 1.0 },          { 1, 0, 1.0 },           { 0, -1, 1.0 },          { -1, 0, 1.0 },
    { 1, 1, std::sqrt(2) }, { 1, -1, std::sqrt(2) }, { -1, 1, std::sqrt(2) }, { -1, -1, std::sqrt(2) },
  }
Referenced by searchPathWithVoronoi().
voronoi_
DynamicVoronoi rmp::path_planner::VoronoiPathPlanner::voronoi_ private
Referenced by _updateVoronoi(), and plan().
voronoi_diagram_
VoronoiData** rmp::path_planner::VoronoiPathPlanner::voronoi_diagram_ private
Referenced by plan(), searchPathWithVoronoi(), VoronoiPathPlanner(), and ~VoronoiPathPlanner().
The documentation for this class was generated from the following files:
src/core/path_planner/path_planner/include/path_planner/graph_planner/voronoi_planner.h
src/core/path_planner/path_planner/src/graph_planner/voronoi_planner.cpp