ROS Motion Planning: rmp::common::geometry::BezierCurve Class Reference
rmp::common::geometry::BezierCurve Class Reference
#include <bezier_curve.h>
Public Member Functions
BezierCurve ()
Construct a new Bezier generation object.
BezierCurve (double step, double offset)
Construct a new Bezier generation object.
~BezierCurve ()
Destroy the Bezier generation object.
bool run (const Points2d points, Points2d &path)
Running trajectory generation.
bool run (const Points3d points, Points2d &path)
Running trajectory generation.
Point2d bezier (double t, Points2d control_pts)
Calculate the Bezier curve point.
Points2d getControlPoints (Point3d start, Point3d goal)
Calculate control points heuristically.
Points2d generation (Point3d start, Point3d goal)
Generate the path.
void setOffset (double offset)
Configure the offset of control points.
Public Member Functions inherited from rmp::common::geometry::Curve
Curve (double step)
Construct a new Curve object.
virtual ~Curve ()=default
Destroy the curve generation object.
double len (Points2d path)
Calculate length of given path.
void setStep (double step)
Configure the simulation step.
Protected Attributes
double offset_
Protected Attributes inherited from rmp::common::geometry::Curve
double step_
Private Member Functions
int _comb (int n, int r)
Constructor & Destructor Documentation
BezierCurve() [1/2]
rmp::common::geometry::BezierCurve::BezierCurve ()
Construct a new Bezier generation object.
Parameters
step Simulation or interpolation size (default: 0.1)
offset The offset of control points (default: 3.0)
                          : Curve(0.1), offset_(3)
 {
 }
BezierCurve() [2/2]
rmp::common::geometry::BezierCurve::BezierCurve (double step, double offset)
Construct a new Bezier generation object.
Parameters
step Simulation or interpolation size (default: 0.1)
offset The offset of control points (default: 3.0)
                                                    : Curve(step), offset_(offset)
 {
 }
~BezierCurve()
rmp::common::geometry::BezierCurve::~BezierCurve ()
Destroy the Bezier generation object.
 {
 }
Member Function Documentation
_comb()
int rmp::common::geometry::BezierCurve::_comb (int n, int r) private
 {
   if ((r == 0) || (r == n))
     return 1;
   else
     return _comb(n - 1, r - 1) + _comb(n - 1, r);
 }
References rviz_generate::r.
Referenced by bezier().
bezier()
Point2d rmp::common::geometry::BezierCurve::bezier (double t, Points2d control_pts)
Calculate the Bezier curve point.
Parameters
t scale factor
control_pts control points
Returns
point point in Bezier curve with t
 {
   size_t n = control_pts.size() - 1;
   double pt_x = 0, pt_y = 0;
   for (size_t i = 0; i < n + 1; i++)
   {
     pt_x += _comb(n, i) * std::pow(t, i) * std::pow(1 - t, n - i) * control_pts[i].x();
     pt_y += _comb(n, i) * std::pow(t, i) * std::pow(1 - t, n - i) * control_pts[i].y();
   }
   return { pt_x, pt_y };
 }
References _comb().
Referenced by generation().
generation()
Points2d rmp::common::geometry::BezierCurve::generation (Point3d start, Point3d goal)
Generate the path.
Parameters
start Initial pose (x, y, yaw)
goal Target pose (x, y, yaw)
Returns
path The smoothed trajectory points
 {
   double sx = start.x(), sy = start.y(), syaw = start.theta();
   double gx = goal.x(), gy = goal.y(), gyaw = goal.theta();
   int n_points = static_cast<int>(std::hypot(sx - gx, sy - gy) / step_);
   Points2d control_pts = getControlPoints(start, goal);
   Points2d points;
   for (size_t i = 0; i < n_points; i++)
   {
     double t = (double)(i) / (double)(n_points - 1);
     points.push_back(bezier(t, control_pts));
   }
   return points;
 }
References bezier(), getControlPoints(), rmp::common::geometry::Curve::step_, rmp::common::geometry::Point3_< T >::theta(), rmp::common::geometry::Point3_< T >::x(), and rmp::common::geometry::Point3_< T >::y().
Referenced by run().
getControlPoints()
Points2d rmp::common::geometry::BezierCurve::getControlPoints (Point3d start, Point3d goal)
Calculate control points heuristically.
Parameters
start Initial pose (x, y, yaw)
goal Target pose (x, y, yaw)
Returns
control_pts control points
 {
   double sx = start.x(), sy = start.y(), syaw = start.theta();
   double gx = goal.x(), gy = goal.y(), gyaw = goal.theta();
   double d = std::hypot(sx - gx, sy - gy) / offset_;
   Points2d control_pts;
   control_pts.emplace_back(sx, sy);
   control_pts.emplace_back(sx + d * cos(syaw), sy + d * sin(syaw));
   control_pts.emplace_back(gx - d * cos(gyaw), gy - d * sin(gyaw));
   control_pts.emplace_back(gx, gy);
   return control_pts;
 }
References rviz_generate::d, offset_, rmp::common::geometry::Point3_< T >::theta(), rmp::common::geometry::Point3_< T >::x(), and rmp::common::geometry::Point3_< T >::y().
Referenced by generation().
run() [1/2]
bool rmp::common::geometry::BezierCurve::run (const Points2d points, Points2d & path) virtual
Running trajectory generation.
Parameters
points path points <x, y>
path generated trajectory
Returns
true if generate successfully, else failed
Implements rmp::common::geometry::Curve.
 {
   if (points.size() < 4)
     return false;
   else
   {
     Points3d poses;
     poses.emplace_back(points.begin()->x(), points.begin()->y(), 0);
     for (size_t i = 1; i < points.size() - 1; i++)
     {
       double theta1 = std::atan2(points[i].y() - points[i - 1].y(), points[i].x() - points[i - 1].x());
       double theta2 = std::atan2(points[i + 1].y() - points[i].y(), points[i + 1].x() - points[i].x());
       poses.emplace_back(points[i].x(), points[i].y(), (theta1 + theta2) / 2);
     }
     poses.emplace_back(points.back().x(), points.back().y(), 0);
     return run(poses, path);
   }
 }
References FakeAMCL::x, and FakeAMCL::y.
run() [2/2]
bool rmp::common::geometry::BezierCurve::run (const Points3d points, Points2d & path) virtual
Running trajectory generation.
Parameters
points path points <x, y, theta>
path generated trajectory
Returns
true if generate successfully, else failed
Implements rmp::common::geometry::Curve.
 {
   if (points.size() < 4)
     return false;
   else
   {
     path.clear();
     for (size_t i = 0; i < points.size() - 1; i++)
     {
       Points2d path_i = generation(points[i], points[i + 1]);
       path.insert(path.end(), path_i.begin(), path_i.end());
     }
     return !path.empty();
   }
 }
References generation().
setOffset()
void rmp::common::geometry::BezierCurve::setOffset (double offset)
Configure the offset of control points.
Parameters
offset The offset of control points
 {
   assert(offset > 0);
   offset_ = offset;
 }
References offset_.
Member Data Documentation
offset_
double rmp::common::geometry::BezierCurve::offset_ protected
Referenced by getControlPoints(), and setOffset().
The documentation for this class was generated from the following files:
src/core/common/include/common/geometry/bezier_curve.h
src/core/common/src/geometry/bezier_curve.cpp