ROS Motion Planning: rmp::common::geometry::DubinsCurve Class Reference
rmp::common::geometry::DubinsCurve Class Reference
#include <dubins_curve.h>
Public Member Functions
DubinsCurve ()
Construct a new Dubins generation object.
DubinsCurve (double step, double max_curv)
Construct a new Dubins generation object.
~DubinsCurve ()
Destroy the Dubins generation object.
bool run (const Points2d points, Points2d &path)
Running trajectory generation.
bool run (const Points3d points, Points2d &path)
Running trajectory generation.
void LSL (double alpha, double beta, double dist, DubinsLength &length, DubinsMode &mode)
Left-Straight-Left generation mode.
void RSR (double alpha, double beta, double dist, DubinsLength &length, DubinsMode &mode)
Right-Straight-Right generation mode.
void LSR (double alpha, double beta, double dist, DubinsLength &length, DubinsMode &mode)
Left-Straight-Right generation mode.
void RSL (double alpha, double beta, double dist, DubinsLength &length, DubinsMode &mode)
Right-Straight-Left generation mode.
void RLR (double alpha, double beta, double dist, DubinsLength &length, DubinsMode &mode)
Right-Left-Right generation mode.
void LRL (double alpha, double beta, double dist, DubinsLength &length, DubinsMode &mode)
Left-Right-Left generation mode.
Point3d interpolate (int mode, double length, Point3d init_pose)
Planning path interpolation.
Points2d generation (Point3d start, Point3d goal)
Generate the path.
void setMaxCurv (double max_curv)
Configure the maximum curvature.
Public Member Functions inherited from rmp::common::geometry::Curve
Curve (double step)
Construct a new Curve object.
virtual ~Curve ()=default
Destroy the curve generation object.
double len (Points2d path)
Calculate length of given path.
void setStep (double step)
Configure the simulation step.
Protected Member Functions
void _update (DubinsLength length, DubinsMode mode, DubinsLength &best_length, DubinsMode &best_mode, double &best_cost)
Update the best motion mode.
Protected Attributes
double max_curv_
Protected Attributes inherited from rmp::common::geometry::Curve
double step_
Private Types
using DubinsMode = std::tuple< int, int, int >
using DubinsLength = std::tuple< double, double, double >
using DubinsSolver = std::function< void(double, double, double, DubinsLength &, DubinsMode &)>
Private Attributes
const std::array< DubinsSolver, 6 > dubins_solvers
Member Typedef Documentation
DubinsLength
using rmp::common::geometry::DubinsCurve::DubinsLength = std::tuple<double, double, double> private
DubinsMode
using rmp::common::geometry::DubinsCurve::DubinsMode = std::tuple<int, int, int> private
DubinsSolver
using rmp::common::geometry::DubinsCurve::DubinsSolver = std::function<void(double, double, double, DubinsLength&, DubinsMode&)> private
Constructor & Destructor Documentation
DubinsCurve() [1/2]
rmp::common::geometry::DubinsCurve::DubinsCurve ()
Construct a new Dubins generation object.
Parameters
step Simulation or interpolation size (default: 0.1)
max_curv The maximum curvature of the curve (default: 0.25)
                          : Curve(0.1), max_curv_(0.25)
 {
 }
DubinsCurve() [2/2]
rmp::common::geometry::DubinsCurve::DubinsCurve (double step, double max_curv)
Construct a new Dubins generation object.
Parameters
step Simulation or interpolation size (default: 0.1)
max_curv The maximum curvature of the curve (default: 0.25)
                                                      : Curve(step), max_curv_(max_curv)
 {
 }
~DubinsCurve()
rmp::common::geometry::DubinsCurve::~DubinsCurve ()
Destroy the Dubins generation object.
 {
 }
Member Function Documentation
_update()
void rmp::common::geometry::DubinsCurve::_update (DubinsLength length, DubinsMode mode, DubinsLength & best_length, DubinsMode & best_mode, double & best_cost) protected
Update the best motion mode.
Parameters
length the current motion length
mode the current motion mode
best_length the best motion length so far
best_mode the best motion mode so far
best_cost the best motion cost so far
 {
   if (std::get<0>(length) != DUBINS_NONE)
   {
     double t, p, q;
     std::tie(t, p, q) = length;
     double cost = fabs(t) + fabs(p) + fabs(q);
     if (best_cost > cost)
     {
       best_length = length;
       best_mode = mode;
       best_cost = cost;
     }
   }
 }
References rmp::common::geometry::DUBINS_NONE.
Referenced by generation().
generation()
Points2d rmp::common::geometry::DubinsCurve::generation (Point3d start, Point3d goal)
Generate the path.
Parameters
start Initial pose (x, y, yaw)
goal Target pose (x, y, yaw)
Returns
path The smoothed trajectory points
 {
   Points2d path;
   double sx = start.x(), sy = start.y(), syaw = start.theta();
   double gx = goal.x(), gy = goal.y(), gyaw = goal.theta();
   // coordinate transformation
   gx -= sx;
   gy -= sy;
   double theta = rmp::common::math::mod2pi(atan2(gy, gx));
   double dist = std::hypot(gx, gy) * max_curv_;
   double alpha = rmp::common::math::mod2pi(syaw - theta);
   double beta = rmp::common::math::mod2pi(gyaw - theta);
   // select the best motion
   DubinsMode best_mode;
   double best_cost = std::numeric_limits<double>::max();
   DubinsLength length;
   DubinsLength best_length = { DUBINS_NONE, DUBINS_NONE, DUBINS_NONE };
   DubinsMode mode;
   for (const auto solver : dubins_solvers)
   {
     solver(alpha, beta, dist, length, mode);
     _update(length, mode, best_length, best_mode, best_cost);
   }
   if (best_cost == std::numeric_limits<double>::max())
     return path;
   // interpolation
   int points_num = int(best_cost / step_) + 6;
   std::vector<double> path_x(points_num);
   std::vector<double> path_y(points_num);
   std::vector<double> path_yaw(points_num, alpha);
   std::vector<int> mode_v = { std::get<0>(best_mode), std::get<1>(best_mode), std::get<2>(best_mode) };
   std::vector<double> length_v = { std::get<0>(best_length), std::get<1>(best_length), std::get<2>(best_length) };
   int i = 0;
   for (int j = 0; j < 3; j++)
   {
     int m = mode_v[j];
     double seg_length = length_v[j];
     // path increment
     double d_l = seg_length > 0.0 ? step_ : -step_;
     double x = path_x[i];
     double y = path_y[i];
     double yaw = path_yaw[i];
     // current path length
     double l = d_l;
     while (fabs(l) <= fabs(seg_length))
     {
       i += 1;
       auto inter_pose = interpolate(m, l, { x, y, yaw });
       path_x[i] = inter_pose.x(), path_y[i] = inter_pose.y(), path_yaw[i] = inter_pose.theta();
       l += d_l;
     }
     i += 1;
     auto inter_pose = interpolate(m, seg_length, { x, y, yaw });
     path_x[i] = inter_pose.x(), path_y[i] = inter_pose.y(), path_yaw[i] = inter_pose.theta();
   }
   // remove unused data
   while ((path_x.size() >= 1) && (path_x.back() == 0.0))
   {
     path_x.pop_back();
     path_y.pop_back();
     path_yaw.pop_back();
   }
   // coordinate transformation
   Eigen::AngleAxisd r_vec(theta, Eigen::Vector3d(0, 0, 1));
   Eigen::Matrix3d R = r_vec.toRotationMatrix();
   Eigen::MatrixXd P = Eigen::MatrixXd::Ones(3, path_x.size());
   for (size_t i = 0; i < path_x.size(); i++)
   {
     P(0, i) = path_x[i];
     P(1, i) = path_y[i];
   }
   P = R * P;
   for (size_t i = 0; i < path_x.size(); i++)
     path.push_back({ P(0, i) + sx, P(1, i) + sy });
   return path;
 }
References _update(), rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::alpha, rmp::common::geometry::DUBINS_NONE, dubins_solvers, Trans_DDQN_play::int, interpolate(), max_curv_, rmp::common::math::mod2pi(), rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::R, rmp::common::geometry::Curve::step_, rmp::common::geometry::Point3_< T >::theta(), FakeAMCL::x, rmp::common::geometry::Point3_< T >::x(), FakeAMCL::y, and rmp::common::geometry::Point3_< T >::y().
Referenced by run().
interpolate()
Point3d rmp::common::geometry::DubinsCurve::interpolate (int mode, double length, Point3d init_pose)
Planning path interpolation.
Parameters
mode motion, i.e., DUBINS_L, DUBINS_S, DUBINS_R
length Single step motion path length
init_pose Initial pose (x, y, yaw)
Returns
new_pose New pose (new_x, new_y, new_yaw) after moving
 {
   double x = init_pose.x(), y = init_pose.y(), yaw = init_pose.theta();
   double new_x, new_y, new_yaw;
   if (mode == DUBINS_S)
   {
     new_x = x + length / max_curv_ * cos(yaw);
     new_y = y + length / max_curv_ * sin(yaw);
     new_yaw = yaw;
   }
   else if (mode == DUBINS_L)
   {
     new_x = x + (sin(yaw + length) - sin(yaw)) / max_curv_;
     new_y = y - (cos(yaw + length) - cos(yaw)) / max_curv_;
     new_yaw = yaw + length;
   }
   else if (mode == DUBINS_R)
   {
     new_x = x - (sin(yaw - length) - sin(yaw)) / max_curv_;
     new_y = y + (cos(yaw - length) - cos(yaw)) / max_curv_;
     new_yaw = yaw - length;
   }
   else
     std::cerr << "Error mode" << std::endl;
   return { new_x, new_y, new_yaw };
 }
References rmp::common::geometry::DUBINS_L, rmp::common::geometry::DUBINS_R, rmp::common::geometry::DUBINS_S, max_curv_, rmp::common::geometry::Point3_< T >::theta(), FakeAMCL::x, rmp::common::geometry::Point3_< T >::x(), FakeAMCL::y, and rmp::common::geometry::Point3_< T >::y().
Referenced by generation().
LRL()
void rmp::common::geometry::DubinsCurve::LRL (double alpha, double beta, double dist, DubinsLength & length, DubinsMode & mode)
Left-Right-Left generation mode.
Parameters
alpha Initial pose of (0, 0, alpha)
beta Goal pose of (dist, 0, beta)
dist Goal pose of (dist, 0, beta)
length Moving lenght of segments (t, s, p)
mode Motion mode
 {
   UNPACK_DUBINS_INPUTS(alpha, beta);
   double p_lrl = (6.0 - std::pow(dist, 2) + 2.0 * cos_a_b + 2.0 * dist * (sin_a - sin_b)) / 8.0;
   if (fabs(p_lrl) > 1.0)
   {
     length = { DUBINS_NONE, DUBINS_NONE, DUBINS_NONE };
     mode = { DUBINS_L, DUBINS_R, DUBINS_L };
   }
   else
   {
     p_lrl = rmp::common::math::mod2pi(2 * M_PI - acos(p_lrl));
     double t_lrl = rmp::common::math::mod2pi(-alpha + atan2(-cos_a + cos_b, dist + sin_a - sin_b) + p_lrl / 2.0);
     double q_lrl = rmp::common::math::mod2pi(beta - alpha - t_lrl + p_lrl);
     length = { t_lrl, p_lrl, q_lrl };
     mode = { DUBINS_L, DUBINS_R, DUBINS_L };
   }
 }
References rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::alpha, rmp::common::geometry::DUBINS_L, rmp::common::geometry::DUBINS_NONE, rmp::common::geometry::DUBINS_R, rmp::common::math::mod2pi(), and UNPACK_DUBINS_INPUTS.
LSL()
void rmp::common::geometry::DubinsCurve::LSL (double alpha, double beta, double dist, DubinsLength & length, DubinsMode & mode)
Left-Straight-Left generation mode.
Parameters
alpha Initial pose of (0, 0, alpha)
beta Goal pose of (dist, 0, beta)
dist Goal pose of (dist, 0, beta)
length Moving lenght of segments (t, s, p)
mode Motion mode
 {
   UNPACK_DUBINS_INPUTS(alpha, beta);
   double p_lsl = 2 + std::pow(dist, 2) - 2 * cos_a_b + 2 * dist * (sin_a - sin_b);
   if (p_lsl < 0)
   {
     length = { DUBINS_NONE, DUBINS_NONE, DUBINS_NONE };
     mode = { DUBINS_L, DUBINS_S, DUBINS_L };
   }
   else
   {
     p_lsl = sqrt(p_lsl);
     double t_lsl = rmp::common::math::mod2pi(-alpha + atan2(cos_b - cos_a, dist + sin_a - sin_b));
     double q_lsl = rmp::common::math::mod2pi(beta - atan2(cos_b - cos_a, dist + sin_a - sin_b));
     length = { t_lsl, p_lsl, q_lsl };
     mode = { DUBINS_L, DUBINS_S, DUBINS_L };
   }
 }
References rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::alpha, rmp::common::geometry::DUBINS_L, rmp::common::geometry::DUBINS_NONE, rmp::common::geometry::DUBINS_S, rmp::common::math::mod2pi(), and UNPACK_DUBINS_INPUTS.
LSR()
void rmp::common::geometry::DubinsCurve::LSR (double alpha, double beta, double dist, DubinsLength & length, DubinsMode & mode)
Left-Straight-Right generation mode.
Parameters
alpha Initial pose of (0, 0, alpha)
beta Goal pose of (dist, 0, beta)
dist Goal pose of (dist, 0, beta)
length Moving lenght of segments (t, s, p)
mode Motion mode
 {
   UNPACK_DUBINS_INPUTS(alpha, beta);
   double p_lsr = -2 + std::pow(dist, 2) + 2 * cos_a_b + 2 * dist * (sin_a + sin_b);
   if (p_lsr < 0)
   {
     length = { DUBINS_NONE, DUBINS_NONE, DUBINS_NONE };
     mode = { DUBINS_L, DUBINS_S, DUBINS_R };
   }
   else
   {
     p_lsr = sqrt(p_lsr);
     double t_lsr = rmp::common::math::mod2pi(-alpha + atan2(-cos_a - cos_b, dist + sin_a + sin_b) - atan2(-2.0, p_lsr));
     double q_lsr = rmp::common::math::mod2pi(-beta + atan2(-cos_a - cos_b, dist + sin_a + sin_b) - atan2(-2.0, p_lsr));
     length = { t_lsr, p_lsr, q_lsr };
     mode = { DUBINS_L, DUBINS_S, DUBINS_R };
   }
 }
References rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::alpha, rmp::common::geometry::DUBINS_L, rmp::common::geometry::DUBINS_NONE, rmp::common::geometry::DUBINS_R, rmp::common::geometry::DUBINS_S, rmp::common::math::mod2pi(), and UNPACK_DUBINS_INPUTS.
RLR()
void rmp::common::geometry::DubinsCurve::RLR (double alpha, double beta, double dist, DubinsLength & length, DubinsMode & mode)
Right-Left-Right generation mode.
Parameters
alpha Initial pose of (0, 0, alpha)
beta Goal pose of (dist, 0, beta)
dist Goal pose of (dist, 0, beta)
length Moving lenght of segments (t, s, p)
mode Motion mode
 {
   UNPACK_DUBINS_INPUTS(alpha, beta);
   double p_rlr = (6.0 - std::pow(dist, 2) + 2.0 * cos_a_b + 2.0 * dist * (sin_a - sin_b)) / 8.0;
   if (fabs(p_rlr) > 1.0)
   {
     length = { DUBINS_NONE, DUBINS_NONE, DUBINS_NONE };
     mode = { DUBINS_R, DUBINS_L, DUBINS_R };
   }
   else
   {
     p_rlr = rmp::common::math::mod2pi(2 * M_PI - acos(p_rlr));
     double t_rlr = rmp::common::math::mod2pi(alpha - atan2(cos_a - cos_b, dist - sin_a + sin_b) + p_rlr / 2.0);
     double q_rlr = rmp::common::math::mod2pi(alpha - beta - t_rlr + p_rlr);
     length = { t_rlr, p_rlr, q_rlr };
     mode = { DUBINS_R, DUBINS_L, DUBINS_R };
   }
 }
References rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::alpha, rmp::common::geometry::DUBINS_L, rmp::common::geometry::DUBINS_NONE, rmp::common::geometry::DUBINS_R, rmp::common::math::mod2pi(), and UNPACK_DUBINS_INPUTS.
RSL()
void rmp::common::geometry::DubinsCurve::RSL (double alpha, double beta, double dist, DubinsLength & length, DubinsMode & mode)
Right-Straight-Left generation mode.
Parameters
alpha Initial pose of (0, 0, alpha)
beta Goal pose of (dist, 0, beta)
dist Goal pose of (dist, 0, beta)
length Moving lenght of segments (t, s, p)
mode Motion mode
 {
   UNPACK_DUBINS_INPUTS(alpha, beta);
   double p_rsl = -2 + std::pow(dist, 2) + 2 * cos_a_b - 2 * dist * (sin_a + sin_b);
   if (p_rsl < 0)
   {
     length = { DUBINS_NONE, DUBINS_NONE, DUBINS_NONE };
     mode = { DUBINS_R, DUBINS_S, DUBINS_L };
   }
   else
   {
     p_rsl = sqrt(p_rsl);
     double t_rsl = rmp::common::math::mod2pi(alpha - atan2(cos_a + cos_b, dist - sin_a - sin_b) + atan2(2.0, p_rsl));
     double q_rsl = rmp::common::math::mod2pi(beta - atan2(cos_a + cos_b, dist - sin_a - sin_b) + atan2(2.0, p_rsl));
     length = { t_rsl, p_rsl, q_rsl };
     mode = { DUBINS_R, DUBINS_S, DUBINS_L };
   }
 }
References rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::alpha, rmp::common::geometry::DUBINS_L, rmp::common::geometry::DUBINS_NONE, rmp::common::geometry::DUBINS_R, rmp::common::geometry::DUBINS_S, rmp::common::math::mod2pi(), and UNPACK_DUBINS_INPUTS.
RSR()
void rmp::common::geometry::DubinsCurve::RSR (double alpha, double beta, double dist, DubinsLength & length, DubinsMode & mode)
Right-Straight-Right generation mode.
Parameters
alpha Initial pose of (0, 0, alpha)
beta Goal pose of (dist, 0, beta)
dist Goal pose of (dist, 0, beta)
length Moving lenght of segments (t, s, p)
mode Motion mode
 {
   UNPACK_DUBINS_INPUTS(alpha, beta);
   double p_rsr = 2 + std::pow(dist, 2) - 2 * cos_a_b + 2 * dist * (sin_b - sin_a);
   if (p_rsr < 0)
   {
     length = { DUBINS_NONE, DUBINS_NONE, DUBINS_NONE };
     mode = { DUBINS_R, DUBINS_S, DUBINS_R };
   }
   else
   {
     p_rsr = sqrt(p_rsr);
     double t_rsr = rmp::common::math::mod2pi(alpha - atan2(cos_a - cos_b, dist - sin_a + sin_b));
     double q_rsr = rmp::common::math::mod2pi(-beta + atan2(cos_a - cos_b, dist - sin_a + sin_b));
     length = { t_rsr, p_rsr, q_rsr };
     mode = { DUBINS_R, DUBINS_S, DUBINS_R };
   }
 }
References rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::alpha, rmp::common::geometry::DUBINS_NONE, rmp::common::geometry::DUBINS_R, rmp::common::geometry::DUBINS_S, rmp::common::math::mod2pi(), and UNPACK_DUBINS_INPUTS.
run() [1/2]
bool rmp::common::geometry::DubinsCurve::run (const Points2d points, Points2d & path) virtual
Running trajectory generation.
Parameters
points path points <x, y>
path generated trajectory
Returns
true if generate successfully, else failed
Implements rmp::common::geometry::Curve.
 {
   if (points.size() < 2)
     return false;
   else
   {
     Points3d poses;
     poses.emplace_back(points.begin()->x(), points.begin()->y());
     for (size_t i = 1; i < points.size() - 1; i++)
     {
       double theta1 = std::atan2(points[i].y() - points[i - 1].y(), points[i].x() - points[i - 1].x());
       double theta2 = std::atan2(points[i + 1].y() - points[i].y(), points[i + 1].x() - points[i].x());
       poses.emplace_back(points[i].x(), points[i].y(), (theta1 + theta2) / 2);
     }
     poses.emplace_back(points.back().x(), points.back().y(), 0);
     return run(poses, path);
   }
 }
References FakeAMCL::x, and FakeAMCL::y.
run() [2/2]
bool rmp::common::geometry::DubinsCurve::run (const Points3d points, Points2d & path) virtual
Running trajectory generation.
Parameters
points path points <x, y, theta>
path generated trajectory
Returns
true if generate successfully, else failed
Implements rmp::common::geometry::Curve.
 {
   if (points.size() < 2)
     return false;
   else
   {
     path.clear();
     for (size_t i = 0; i < points.size() - 1; i++)
     {
       Points2d path_i = generation(points[i], points[i + 1]);
       if (!path_i.empty())
         path.insert(path.end(), path_i.begin(), path_i.end());
     }
     return !path.empty();
   }
 }
References generation().
setMaxCurv()
void rmp::common::geometry::DubinsCurve::setMaxCurv (double max_curv)
Configure the maximum curvature.
Parameters
max_curv the maximum curvature
 {
   assert(max_curv > 0);
   max_curv_ = max_curv;
 }
References max_curv_.
Member Data Documentation
dubins_solvers
const std::array<DubinsSolver, 6> rmp::common::geometry::DubinsCurve::dubins_solvers private
Initial value:
= {
    std::bind(&DubinsCurve::LRL, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3,
              std::placeholders::_4, std::placeholders::_5),
    std::bind(&DubinsCurve::LSL, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3,
              std::placeholders::_4, std::placeholders::_5),
    std::bind(&DubinsCurve::LSR, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3,
              std::placeholders::_4, std::placeholders::_5),
    std::bind(&DubinsCurve::RLR, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3,
              std::placeholders::_4, std::placeholders::_5),
    std::bind(&DubinsCurve::RSL, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3,
              std::placeholders::_4, std::placeholders::_5),
    std::bind(&DubinsCurve::RSR, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3,
              std::placeholders::_4, std::placeholders::_5),
  }
Referenced by generation().
max_curv_
double rmp::common::geometry::DubinsCurve::max_curv_ protected
Referenced by generation(), interpolate(), and setMaxCurv().
The documentation for this class was generated from the following files:
src/core/common/include/common/geometry/dubins_curve.h
src/core/common/src/geometry/dubins_curve.cpp