ROS Motion Planning: rmp::controller::MPCController Class Reference
rmp::controller::MPCController Class Reference
A class implementing a local planner using the MPC.
#include <mpc_controller.h>
Public Member Functions
MPCController ()
Construct a new MPC planner object.
MPCController (std::string name, tf2_ros::Buffer *tf, costmap_2d::Costmap2DROS *costmap_ros)
Construct a new MPC planner object.
~MPCController ()
Destroy the MPC planner object.
void initialize (std::string name, tf2_ros::Buffer *tf, costmap_2d::Costmap2DROS *costmap_ros)
Initialization of the local planner.
bool setPlan (const std::vector< geometry_msgs::PoseStamped > &orig_global_plan)
Set the plan that the controller is following.
bool isGoalReached ()
Check if the goal pose has been achieved.
bool computeVelocityCommands (geometry_msgs::Twist &cmd_vel)
Given the current position, orientation, and velocity of the robot, compute the velocity commands.
Private Member Functions
Eigen::Vector2d _mpcControl (Eigen::Vector3d s, Eigen::Vector3d s_d, Eigen::Vector2d u_r, Eigen::Vector2d du_p)
Execute MPC control process.
Private Member Functions inherited from rmp::controller::Controller
Controller ()
Construct a new Controller object.
~Controller ()
Destroy the Local Planner object.
void setFactor (double factor)
Set or reset obstacle factor.
void setBaseFrame (std::string base_frame)
Set or reset frame name.
void setMapFrame (std::string map_frame)
double regularizeAngle (double angle)
Regularize angle to [-pi, pi].
double getYawAngle (geometry_msgs::PoseStamped &ps)
Get the Yaw Angles from PoseStamped.
bool shouldRotateToGoal (const geometry_msgs::PoseStamped &cur, const geometry_msgs::PoseStamped &goal)
Whether to reach the target pose through rotation operation.
bool shouldRotateToPath (double angle_to_path, double tolerance=0.0)
Whether to correct the tracking path with rotation operation.
double linearRegularization (nav_msgs::Odometry &base_odometry, double v_d)
linear velocity regularization
double angularRegularization (nav_msgs::Odometry &base_odometry, double w_d)
angular velocity regularization
void transformPose (tf2_ros::Buffer *tf, const std::string out_frame, const geometry_msgs::PoseStamped &in_pose, geometry_msgs::PoseStamped &out_pose) const
Tranform from in_pose to out_pose with out frame using tf.
bool worldToMap (double wx, double wy, int &mx, int &my)
Tranform from world map(x, y) to costmap(x, y)
std::vector< geometry_msgs::PoseStamped > prune (const geometry_msgs::PoseStamped robot_pose_global)
Prune the path, removing the waypoints that the robot has already passed and distant waypoints.
double getLookAheadDistance (double vt)
Calculate the look-ahead distance with current speed dynamically.
void getLookAheadPoint (double lookahead_dist, geometry_msgs::PoseStamped robot_pose_global, const std::vector< geometry_msgs::PoseStamped > &prune_plan, geometry_msgs::PointStamped &pt, double &theta, double &kappa)
find the point on the path that is exactly the lookahead distance away from the robot
Private Attributes
bool initialized_
bool goal_reached_
tf2_ros::Buffer * tf_
double d_t_
Eigen::Matrix3d Q_
Eigen::Matrix2d R_
int p_
int m_
Eigen::Vector2d du_p_
ros::Publisher target_pt_pub_
ros::Publisher current_pose_pub_
double goal_x_
double goal_y_
double goal_theta_
Private Attributes inherited from rmp::controller::Controller
double factor_
double max_v_
double min_v_
double max_v_inc_
double max_w_
double min_w_
double max_w_inc_
double goal_dist_tol_
double rotate_tol_
std::string base_frame_
std::string map_frame_
std::string odom_frame_
std::shared_ptr< base_local_planner::OdometryHelperRos > odom_helper_
costmap_2d::Costmap2DROS * costmap_ros_
std::vector< geometry_msgs::PoseStamped > global_plan_
double lookahead_time_
double min_lookahead_dist_
double max_lookahead_dist_
Detailed Description
A class implementing a local planner using the MPC.
Constructor & Destructor Documentation
MPCController() [1/2]
rmp::controller::MPCController::MPCController ()
Construct a new MPC planner object.
Construct a new MPC Controller object.
                              : initialized_(false), goal_reached_(false), tf_(nullptr)  //, costmap_ros_(nullptr)
 {
 }
MPCController() [2/2]
rmp::controller::MPCController::MPCController (std::string name, tf2_ros::Buffer * tf, costmap_2d::Costmap2DROS * costmap_ros)
Construct a new MPC planner object.
Construct a new MPC Controller object.
   : MPCController()
 {
   initialize(name, tf, costmap_ros);
 }
References initialize(), and rviz_generate::name.
~MPCController()
rmp::controller::MPCController::~MPCController ()
Destroy the MPC planner object.
Destroy the MPC Controller object.
 {
 }
Member Function Documentation
_mpcControl()
Eigen::Vector2d rmp::controller::MPCController::_mpcControl (Eigen::Vector3d s, Eigen::Vector3d s_d, Eigen::Vector2d u_r, Eigen::Vector2d du_p) private
Execute MPC control process.
Parameters
s current state
s_d desired state
u_r refered control
du_p previous control error
Returns
u control vector
 {
   int dim_u = 2;
   int dim_x = 3;
   // state vector (5 x 1)
   Eigen::VectorXd x = Eigen::VectorXd(dim_x + dim_u);
   x.topLeftCorner(dim_x, 1) = s - s_d;
   x[2] = regularizeAngle(x[2]);
   x.bottomLeftCorner(dim_u, 1) = du_p;
   // original state matrix
   Eigen::Matrix3d A_o = Eigen::Matrix3d::Identity();
   A_o(0, 2) = -u_r[0] * sin(s_d[2]) * d_t_;
   A_o(1, 2) = u_r[0] * cos(s_d[2]) * d_t_;
   // original control matrix
   Eigen::MatrixXd B_o = Eigen::MatrixXd::Zero(dim_x, dim_u);
   B_o(0, 0) = cos(s_d[2]) * d_t_;
   B_o(1, 0) = sin(s_d[2]) * d_t_;
   B_o(2, 1) = d_t_;
   // state matrix (5 x 5)
   Eigen::MatrixXd A = Eigen::MatrixXd::Zero(dim_x + dim_u, dim_x + dim_u);
   A.topLeftCorner(dim_x, dim_x) = A_o;
   A.topRightCorner(dim_x, dim_u) = B_o;
   A.bottomLeftCorner(dim_u, dim_x) = Eigen::MatrixXd::Zero(dim_u, dim_x);
   A.bottomRightCorner(dim_u, dim_u) = Eigen::Matrix2d::Identity();
   // control matrix (5 x 2)
   Eigen::MatrixXd B = Eigen::MatrixXd::Zero(dim_x + dim_u, dim_u);
   B.topLeftCorner(dim_x, dim_u) = B_o;
   B.bottomLeftCorner(dim_u, dim_u) = Eigen::Matrix2d::Identity();
   // output matrix(3 x 5)
   Eigen::MatrixXd C = Eigen::MatrixXd::Zero(dim_x, dim_x + dim_u);
   C.topLeftCorner(dim_x, dim_x) = Eigen::Matrix3d::Identity();
   C.topRightCorner(dim_x, dim_u) = Eigen::MatrixXd::Zero(dim_x, dim_u);
   // mpc state matrix(3p x 5)
   Eigen::MatrixPower<Eigen::MatrixXd> A_pow(A);
   Eigen::MatrixXd S_x = Eigen::MatrixXd::Zero(dim_x * p_, dim_x + dim_u);
   for (int i = 0; i < p_; i++)
     S_x.middleRows(dim_x * i, dim_x) = C * A_pow(i + 1);
   // mpc control matrix(3p x 2m)
   Eigen::MatrixXd S_u = Eigen::MatrixXd::Zero(dim_x * p_, dim_u * m_);
   for (int i = 0; i < p_; i++)
   {
     for (int j = 0; j < m_; j++)
     {
       if (j <= i)
         S_u.block(dim_x * i, dim_u * j, dim_x, dim_u) = C * A_pow(i - j) * B;
       else
         S_u.block(dim_x * i, dim_u * j, dim_x, dim_u) = Eigen::MatrixXd::Zero(dim_x, dim_u);
     }
   }
   // optimization
   // min 1/2 * x.T * P * x + q.T * x
   // s.t. l <= Ax <= u
   Eigen::VectorXd Yr = Eigen::VectorXd::Zero(dim_x * p_);                              // (3p x 1)
   Eigen::MatrixXd Q = Eigen::kroneckerProduct(Eigen::MatrixXd::Identity(p_, p_), Q_);  // (3p x 3p)
   Eigen::MatrixXd R = Eigen::kroneckerProduct(Eigen::MatrixXd::Identity(m_, m_), R_);  // (2m x 2m)
   Eigen::MatrixXd P = S_u.transpose() * Q * S_u + R;                                   // (2m x 2m)
   Eigen::VectorXd q = S_u.transpose() * Q * (S_x * x - Yr);                            // (2m x 1)
   // boundary
   Eigen::Vector2d u_min(min_v_, -max_w_);
   Eigen::Vector2d u_max(max_v_, max_w_);
   Eigen::Vector2d u_k_1(du_p[0], du_p[1]);
   Eigen::Vector2d du_min(-0.2, -0.2);
   Eigen::Vector2d du_max(0.2, M_PI);
   Eigen::VectorXd U_min = Eigen::kroneckerProduct(Eigen::VectorXd::Ones(m_), u_min);    // (2m x 1)
   Eigen::VectorXd U_max = Eigen::kroneckerProduct(Eigen::VectorXd::Ones(m_), u_max);    // (2m x 1)
   Eigen::VectorXd U_r = Eigen::kroneckerProduct(Eigen::VectorXd::Ones(m_), u_r);        // (2m x 1)
   Eigen::VectorXd U_k_1 = Eigen::kroneckerProduct(Eigen::VectorXd::Ones(m_), u_k_1);    // (2m x 1)
   Eigen::VectorXd dU_min = Eigen::kroneckerProduct(Eigen::VectorXd::Ones(m_), du_min);  // (2m x 1)
   Eigen::VectorXd dU_max = Eigen::kroneckerProduct(Eigen::VectorXd::Ones(m_), du_max);  // (2m x 1)
   // constriants
   Eigen::VectorXd lower = Eigen::VectorXd::Zero(2 * dim_u * m_);  // (4m x 1)
   Eigen::VectorXd upper = Eigen::VectorXd::Zero(2 * dim_u * m_);  // (4m x 1)
   lower.topRows(dim_u * m_) = U_min - U_k_1 - U_r;
   lower.bottomRows(dim_u * m_) = dU_min;
   upper.topRows(dim_u * m_) = U_max - U_k_1 - U_r;
   upper.bottomRows(dim_u * m_) = dU_max;
   // Calculate kernel
   std::vector<c_float> P_data;
   std::vector<c_int> P_indices;
   std::vector<c_int> P_indptr;
   int ind_P = 0;
   for (int col = 0; col < dim_u * m_; ++col)
   {
     P_indptr.push_back(ind_P);
     for (int row = 0; row <= col; ++row)
     {
       P_data.push_back(P(row, col));
       // P_data.push_back(P(row, col) * 2.0);
       P_indices.push_back(row);
       ind_P++;
     }
   }
   P_indptr.push_back(ind_P);
   // Calculate affine constraints (4m x 2m)
   std::vector<c_float> A_data;
   std::vector<c_int> A_indices;
   std::vector<c_int> A_indptr;
   int ind_A = 0;
   A_indptr.push_back(ind_A);
   for (int j = 0; j < m_; ++j)
   {
     for (int n = 0; n < dim_u; ++n)
     {
       for (int row = dim_u * j + n; row < dim_u * m_; row += dim_u)
       {
         A_data.push_back(1.0);
         A_indices.push_back(row);
         ++ind_A;
       }
       A_data.push_back(1.0);
       A_indices.push_back(dim_u * m_ + dim_u * j + n);
       ++ind_A;
       A_indptr.push_back(ind_A);
     }
   }
   // Calculate offset
   std::vector<c_float> q_data;
   for (int row = 0; row < dim_u * m_; ++row)
   {
     q_data.push_back(q(row, 0));
   }
   // Calculate constraints
   std::vector<c_float> lower_bounds;
   std::vector<c_float> upper_bounds;
   for (int row = 0; row < 2 * dim_u * m_; row++)
   {
     lower_bounds.push_back(lower(row, 0));
     upper_bounds.push_back(upper(row, 0));
   }
   // solve
   OSQPWorkspace* work = nullptr;
   OSQPData* data = reinterpret_cast<OSQPData*>(c_malloc(sizeof(OSQPData)));
   OSQPSettings* settings = reinterpret_cast<OSQPSettings*>(c_malloc(sizeof(OSQPSettings)));
   osqp_set_default_settings(settings);
   settings->verbose = false;
   settings->warm_start = true;
   data->n = dim_u * m_;
   data->m = 2 * dim_u * m_;
   data->P = csc_matrix(data->n, data->n, P_data.size(), P_data.data(), P_indices.data(), P_indptr.data());
   data->q = q.data();
   data->A = csc_matrix(data->m, data->n, A_data.size(), A_data.data(), A_indices.data(), A_indptr.data());
   data->l = lower_bounds.data();
   data->u = upper_bounds.data();
   osqp_setup(&work, data, settings);
   osqp_solve(work);
   auto status = work->info->status_val;
   if (status < 0)
   {
     std::cout << "failed optimization status:\t" << work->info->status;
     return Eigen::Vector2d::Zero();
   }
   if (status != 1 && status != 2)
   {
     std::cout << "failed optimization status:\t" << work->info->status;
     return Eigen::Vector2d::Zero();
   }
   Eigen::Vector2d u(work->solution->x[0] + du_p[0] + u_r[0], regularizeAngle(work->solution->x[1] + du_p[1] + u_r[1]));
   // Cleanup
   osqp_cleanup(work);
   c_free(data->A);
   c_free(data->P);
   c_free(data);
   c_free(settings);
   return u;
 }
References d_t_, m_, rmp::controller::Controller::max_v_, rmp::controller::Controller::max_w_, rmp::controller::Controller::min_v_, p_, Q_, rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::R, R_, rmp::controller::Controller::regularizeAngle(), key_ctrl::s, multi_teleop_twist_keyboard::settings, multi_teleop_twist_keyboard::status, and FakeAMCL::x.
Referenced by computeVelocityCommands().
computeVelocityCommands()
bool rmp::controller::MPCController::computeVelocityCommands (geometry_msgs::Twist & cmd_vel)
Given the current position, orientation, and velocity of the robot, compute the velocity commands.
Parameters
cmd_vel will be filled with the velocity command to be passed to the robot base
Returns
true if a valid trajectory was found, else false
 {
   if (!initialized_)
   {
     ROS_ERROR("MPC Controller has not been initialized");
     return false;
   }
   // odometry observation - getting robot velocities in robot frame
   nav_msgs::Odometry base_odom;
   odom_helper_->getOdom(base_odom);
   // get robot position in global frame
   geometry_msgs::PoseStamped robot_pose_odom, robot_pose_map;
   costmap_ros_->getRobotPose(robot_pose_odom);
   transformPose(tf_, map_frame_, robot_pose_odom, robot_pose_map);
   // transform global plan to robot frame
   std::vector<geometry_msgs::PoseStamped> prune_plan = prune(robot_pose_map);
   // calculate look-ahead distance
   double vt = std::hypot(base_odom.twist.twist.linear.x, base_odom.twist.twist.linear.y);
   double wt = base_odom.twist.twist.angular.z;
   double L = getLookAheadDistance(vt);
   // get the particular point on the path at the lookahead distance
   geometry_msgs::PointStamped lookahead_pt;
   double theta_trj, kappa;
   getLookAheadPoint(L, robot_pose_map, prune_plan, lookahead_pt, theta_trj, kappa);
   // current angle
   double theta = tf2::getYaw(robot_pose_map.pose.orientation);  // [-pi, pi]
   // calculate commands
   if (shouldRotateToGoal(robot_pose_map, global_plan_.back()))
   {
     du_p_ = Eigen::Vector2d(0, 0);
     double e_theta = regularizeAngle(goal_theta_ - theta);
     // orientation reached
     if (!shouldRotateToPath(std::fabs(e_theta)))
     {
       cmd_vel.linear.x = 0.0;
       cmd_vel.angular.z = 0.0;
       goal_reached_ = true;
     }
     // orientation not reached
     else
     {
       cmd_vel.linear.x = 0.0;
       cmd_vel.angular.z = angularRegularization(base_odom, e_theta / d_t_);
     }
   }
   else
   {
     Eigen::Vector3d s(robot_pose_map.pose.position.x, robot_pose_map.pose.position.y, theta);  // current state
     Eigen::Vector3d s_d(lookahead_pt.point.x, lookahead_pt.point.y, theta_trj);                // desired state
     Eigen::Vector2d u_r(vt, regularizeAngle(vt * kappa));                                      // refered input
     Eigen::Vector2d u = _mpcControl(s, s_d, u_r, du_p_);
     double u_v = linearRegularization(base_odom, u[0]);
     double u_w = angularRegularization(base_odom, u[1]);
     du_p_ = Eigen::Vector2d(u_v - u_r[0], regularizeAngle(u_w - u_r[1]));
     cmd_vel.linear.x = u_v;
     cmd_vel.angular.z = u_w;
   }
   // publish lookahead pose
   target_pt_pub_.publish(lookahead_pt);
   // publish robot pose
   current_pose_pub_.publish(robot_pose_map);
   return true;
 }
References _mpcControl(), rmp::controller::Controller::angularRegularization(), rmp::controller::Controller::costmap_ros_, current_pose_pub_, d_t_, du_p_, rmp::controller::Controller::getLookAheadDistance(), rmp::controller::Controller::getLookAheadPoint(), rmp::controller::Controller::global_plan_, goal_reached_, goal_theta_, initialized_, rmp::controller::Controller::linearRegularization(), rmp::controller::Controller::map_frame_, rmp::controller::Controller::odom_helper_, rmp::controller::Controller::prune(), rmp::controller::Controller::regularizeAngle(), key_ctrl::s, rmp::controller::Controller::shouldRotateToGoal(), rmp::controller::Controller::shouldRotateToPath(), target_pt_pub_, tf_, and rmp::controller::Controller::transformPose().
initialize()
void rmp::controller::MPCController::initialize (std::string name, tf2_ros::Buffer * tf, costmap_2d::Costmap2DROS * costmap_ros)
Initialization of the local planner.
Parameters
name the name to give this instance of the trajectory planner
tf a pointer to a transform listener
costmap_ros the cost map to use for assigning costs to trajectories
 {
   if (!initialized_)
   {
     initialized_ = true;
     tf_ = tf;
     costmap_ros_ = costmap_ros;
     ros::NodeHandle nh = ros::NodeHandle("~/" + name);
     // base
     nh.param("goal_dist_tolerance", goal_dist_tol_, 0.2);
     nh.param("rotate_tolerance", rotate_tol_, 0.5);
     nh.param("base_frame", base_frame_, base_frame_);
     nh.param("map_frame", map_frame_, map_frame_);
     // lookahead
     nh.param("lookahead_time", lookahead_time_, 1.5);
     nh.param("min_lookahead_dist", min_lookahead_dist_, 0.3);
     nh.param("max_lookahead_dist", max_lookahead_dist_, 0.9);
     // linear velocity
     nh.param("max_v", max_v_, 0.5);
     nh.param("min_v", min_v_, 0.0);
     nh.param("max_v_inc", max_v_inc_, 0.5);
     // angular velocity
     nh.param("max_w", max_w_, 1.57);
     nh.param("min_w", min_w_, 0.0);
     nh.param("max_w_inc", max_w_inc_, 1.57);
     // iteration for ricatti solution
     nh.param("predicting_time_domain", p_, 4);
     nh.param("control_time_domain", m_, 4);
     // weight matrix for penalizing state error while tracking [x,y,theta]
     std::vector<double> diag_vec;
     Q_ = Eigen::Matrix3d::Zero();
     nh.getParam("Q_matrix_diag", diag_vec);
     for (size_t i = 0; i < diag_vec.size(); ++i)
       Q_(i, i) = diag_vec[i];
     // weight matrix for penalizing input error while tracking[v, w]
     nh.getParam("R_matrix_diag", diag_vec);
     R_ = Eigen::Matrix2d::Zero();
     for (size_t i = 0; i < diag_vec.size(); ++i)
       R_(i, i) = diag_vec[i];
     double controller_freqency;
     nh.param("/move_base/controller_frequency", controller_freqency, 10.0);
     d_t_ = 1 / controller_freqency;
     target_pt_pub_ = nh.advertise<geometry_msgs::PointStamped>("/target_point", 10);
     current_pose_pub_ = nh.advertise<geometry_msgs::PoseStamped>("/current_pose", 10);
     ROS_INFO("MPC Controller initialized!");
   }
   else
   {
     ROS_WARN("MPC Controller has already been initialized.");
   }
 }
References rmp::controller::Controller::base_frame_, rmp::controller::Controller::costmap_ros_, current_pose_pub_, d_t_, rmp::controller::Controller::goal_dist_tol_, initialized_, rmp::controller::Controller::lookahead_time_, m_, rmp::controller::Controller::map_frame_, rmp::controller::Controller::max_lookahead_dist_, rmp::controller::Controller::max_v_, rmp::controller::Controller::max_v_inc_, rmp::controller::Controller::max_w_, rmp::controller::Controller::max_w_inc_, rmp::controller::Controller::min_lookahead_dist_, rmp::controller::Controller::min_v_, rmp::controller::Controller::min_w_, rviz_generate::name, p_, Q_, R_, rmp::controller::Controller::rotate_tol_, target_pt_pub_, and tf_.
Referenced by MPCController().
isGoalReached()
bool rmp::controller::MPCController::isGoalReached ()
Check if the goal pose has been achieved.
Returns
true if achieved, false otherwise
 {
   if (!initialized_)
   {
     ROS_ERROR("MPC Controller has not been initialized");
     return false;
   }
   if (goal_reached_)
   {
     ROS_INFO("GOAL Reached!");
     return true;
   }
   return false;
 }
References goal_reached_, and initialized_.
setPlan()
bool rmp::controller::MPCController::setPlan (const std::vector< geometry_msgs::PoseStamped > & orig_global_plan)
Set the plan that the controller is following.
Parameters
orig_global_plan the plan to pass to the controller
Returns
true if the plan was updated successfully, else false
 {
   if (!initialized_)
   {
     ROS_ERROR("This planner has not been initialized, please call initialize() before using this planner");
     return false;
   }
   ROS_INFO("Got new plan");
   // set new plan
   global_plan_.clear();
   global_plan_ = orig_global_plan;
   // reset plan parameters
   if (goal_x_ != global_plan_.back().pose.position.x || goal_y_ != global_plan_.back().pose.position.y)
   {
     goal_x_ = global_plan_.back().pose.position.x;
     goal_y_ = global_plan_.back().pose.position.y;
     goal_theta_ = getYawAngle(global_plan_.back());
     goal_reached_ = false;
   }
   return true;
 }
References rmp::controller::Controller::getYawAngle(), rmp::controller::Controller::global_plan_, goal_reached_, goal_theta_, goal_x_, goal_y_, and initialized_.
Member Data Documentation
current_pose_pub_
ros::Publisher rmp::controller::MPCController::current_pose_pub_ private
Referenced by computeVelocityCommands(), and initialize().
d_t_
double rmp::controller::MPCController::d_t_ private
Referenced by _mpcControl(), computeVelocityCommands(), and initialize().
du_p_
Eigen::Vector2d rmp::controller::MPCController::du_p_ private
Referenced by computeVelocityCommands().
goal_reached_
bool rmp::controller::MPCController::goal_reached_ private
Referenced by computeVelocityCommands(), isGoalReached(), and setPlan().
goal_theta_
double rmp::controller::MPCController::goal_theta_ private
Referenced by computeVelocityCommands(), and setPlan().
goal_x_
double rmp::controller::MPCController::goal_x_ private
Referenced by setPlan().
goal_y_
double rmp::controller::MPCController::goal_y_ private
Referenced by setPlan().
initialized_
bool rmp::controller::MPCController::initialized_ private
Referenced by computeVelocityCommands(), initialize(), isGoalReached(), and setPlan().
m_
int rmp::controller::MPCController::m_ private
Referenced by _mpcControl(), and initialize().
p_
int rmp::controller::MPCController::p_ private
Referenced by _mpcControl(), and initialize().
Q_
Eigen::Matrix3d rmp::controller::MPCController::Q_ private
Referenced by _mpcControl(), and initialize().
R_
Eigen::Matrix2d rmp::controller::MPCController::R_ private
Referenced by _mpcControl(), and initialize().
target_pt_pub_
ros::Publisher rmp::controller::MPCController::target_pt_pub_ private
Referenced by computeVelocityCommands(), and initialize().
tf_
tf2_ros::Buffer* rmp::controller::MPCController::tf_ private
Referenced by computeVelocityCommands(), and initialize().
The documentation for this class was generated from the following files:
src/core/controller/mpc_controller/include/controller/mpc_controller.h
src/core/controller/mpc_controller/src/mpc_controller.cpp