ROS Motion Planning: rmp::path_planner::ACOPathPlanner Class Reference
rmp::path_planner::ACOPathPlanner Class Reference
Class for objects that plan using the GA algorithm.
#include <aco_planner.h>
Classes
struct Ant
Public Types
enum GEN_MODE { RANDOM = 1, CIRCLE = 2 }
Public Types inherited from rmp::path_planner::PathPlanner
using Point2d = rmp::common::geometry::Point2d
using Point3d = rmp::common::geometry::Point3d
using Points2d = rmp::common::geometry::Points2d
using Points3d = rmp::common::geometry::Points3d
Public Member Functions
ACOPathPlanner (costmap_2d::Costmap2DROS *costmap_ros, int n_ants, int n_inherited, int point_num, double alpha, double beta, double rho, double Q, int init_mode, int max_iter)
Construct a new ACO object.
~ACOPathPlanner ()
bool plan (const Point3d &start, const Point3d &goal, Points3d &path, Points3d &expand)
ACO implementation.
void initializePositions (PositionSequence &initial_positions, const Point2d &start, const Point2d &goal, int gen_mode=GEN_MODE::CIRCLE)
Generate n ants with pointNum_ positions each within the map range.
double calFitnessValue (const Points2d &position)
Calculate the value of fitness function.
void optimizeAnt (Ant &ant, Ant &best_ant, std::mt19937 &gen, Points3d &expand)
Ant update optimization iteration.
void updateAnts (std::vector< Ant > &ants, const Point2d &start, const Point2d &goal, Ant &best_ant)
Public Member Functions inherited from rmp::path_planner::PathPlanner
PathPlanner (costmap_2d::Costmap2DROS *costmap_ros)
Construct a new Global PathPlanner object.
virtual ~PathPlanner ()=default
Destroy the Global PathPlanner object.
void setFactor (float factor)
Set or reset obstacle factor.
costmap_2d::Costmap2D * getCostMap () const
get the costmap
int getMapSize () const
get the size of costmap
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap ()
Inflate the boundary of costmap into obstacles to prevent cross planning.
Protected Attributes
int point_num_
int n_ants_
int n_inherited_
double alpha_
double beta_
double rho_
double Q_
int max_iter_
int init_mode_
Point2d start_
Point2d goal_
double * pheromone_mat_
Protected Attributes inherited from rmp::path_planner::PathPlanner
int map_size_
float factor_
costmap_2d::Costmap2DROS * costmap_ros_
costmap_2d::Costmap2D * costmap_
Private Types
using PositionSequence = std::vector< Points2d >
Private Attributes
std::mutex mutex_
std::vector< Ant > inherited_ants_
std::unique_ptr< rmp::common::geometry::BSplineCurve > bspline_gen_
Additional Inherited Members
Protected Member Functions inherited from rmp::path_planner::PathPlanner
template<typename Node >
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
template<typename Node >
std::vector< Node > _convertBiClosedListToPath (std::unordered_map< int, Node > &f_closed_list, std::unordered_map< int, Node > &b_closed_list, const Node &start, const Node &goal, const Node &boundary)
Detailed Description
Class for objects that plan using the GA algorithm.
Member Typedef Documentation
PositionSequence
using rmp::path_planner::ACOPathPlanner::PositionSequence = std::vector<Points2d> private
Member Enumeration Documentation
GEN_MODE
enum rmp::path_planner::ACOPathPlanner::GEN_MODE
Enumerator
RANDOM
CIRCLE
   {
     RANDOM = 1,
     CIRCLE = 2,
   };
Constructor & Destructor Documentation
ACOPathPlanner()
rmp::path_planner::ACOPathPlanner::ACOPathPlanner (costmap_2d::Costmap2DROS * costmap_ros, int n_ants, int n_inherited, int point_num, double alpha, double beta, double rho, double Q, int init_mode, int max_iter)
Construct a new ACO object.
Parameters
costmap the environment for path planning
n_ants number of ants
alpha pheromone weight coefficient
beta heuristic factor weight coefficient
rho evaporation coefficient
Q pheromone gain
max_iter maximum iterations
   : PathPlanner(costmap_ros)
   , n_ants_(n_ants)
   , n_inherited_(n_inherited)
   , point_num_(point_num)
   , alpha_(alpha)
   , beta_(beta)
   , rho_(rho)
   , Q_(Q)
   , init_mode_(init_mode)
   , max_iter_(max_iter)
 {
   bspline_gen_ = std::make_unique<rmp::common::geometry::BSplineCurve>();
   inherited_ants_.emplace_back(Points2d(point_num), 0.0);
   pheromone_mat_ = new double[map_size_];
 }
References bspline_gen_, inherited_ants_, rmp::path_planner::PathPlanner::map_size_, and pheromone_mat_.
~ACOPathPlanner()
rmp::path_planner::ACOPathPlanner::~ACOPathPlanner ()
 {
   delete[] pheromone_mat_;
 }
References pheromone_mat_.
Member Function Documentation
calFitnessValue()
double rmp::path_planner::ACOPathPlanner::calFitnessValue (const Points2d & position)
Calculate the value of fitness function.
Parameters
position the control points calculated by PSO
Returns
fitness the value of fitness function
 {
   Points2d points, b_path;
   points.push_back(start_);
   for (const auto& pos : position)
     points.emplace_back(pos.x(), pos.y());
   points.push_back(goal_);
   points.erase(std::unique(std::begin(points), std::end(points)), std::end(points));
   bspline_gen_->run(points, b_path);
   // collision detection
   int point_index;
   double obs_cost = 1;
   for (size_t i = 1; i < b_path.size(); ++i)
   {
     point_index = grid2Index(static_cast<int>(b_path[i].x()), static_cast<int>(b_path[i].y()));
     // next node hit the boundary or obstacle
     if ((point_index < 0) || (point_index >= map_size_) ||
         (costmap_->getCharMap()[point_index] >= costmap_2d::LETHAL_OBSTACLE * factor_))
       obs_cost++;
   }
   // Calculate particle fitness
   double b_path_length = bspline_gen_->len(b_path);
   if (b_path_length > 0)
     return 100000.0 / (b_path_length + 1000 * obs_cost);
   else
     return 0;
 }
References bspline_gen_, rmp::path_planner::PathPlanner::costmap_, rmp::path_planner::PathPlanner::factor_, goal_, rmp::path_planner::PathPlanner::grid2Index(), rmp::path_planner::PathPlanner::map_size_, start_, FakeAMCL::x, and FakeAMCL::y.
Referenced by optimizeAnt(), and updateAnts().
initializePositions()
void rmp::path_planner::ACOPathPlanner::initializePositions (PositionSequence & initial_positions, const Point2d & start, const Point2d & goal, int gen_mode = GEN_MODE::CIRCLE)
Generate n ants with pointNum_ positions each within the map range.
Parameters
initial_positions The initial position sequence of ants
start start node
goal goal node
gen_mode generation mode
 {
   // Use a random device and engine to generate random numbers
   std::random_device rd;
   std::mt19937 gen(rd());
   int x[point_num_], y[point_num_];
   int point_id, pos_id;
   // Calculate sequence direction
   bool x_order = (goal.x() > start.x());
   bool y_order = (goal.y() > start.y());
   // circle generation
   int center_x, center_y;
   double radius;
   if (gen_mode == GEN_MODE::CIRCLE)
   {
     // Calculate the center and the radius of the circle (midpoint between start and goal)
     center_x = (start.x() + goal.x()) / 2;
     center_y = (start.y() + goal.y()) / 2;
     double dist = 0.5 * std::hypot(start.x() - goal.x(), start.y() - goal.y());
     radius = dist < 5 ? 5 : dist;
   }
   // initialize n_particles positions
   for (size_t i = 0; i < n_ants_; ++i)
   {
     Points2d ant_positions;
     std::unordered_set<int> visited;
     std::vector<double> probabilities;
     double prob_sum = 0.0;
     point_id = 0;
     // Generate k * point_num_ unique coordinates
     int temp_size = 3 * point_num_;
     int temp_x[temp_size], temp_y[temp_size];
     while (point_id < temp_size)
     {
       if (gen_mode == GEN_MODE::RANDOM)
       {
         temp_x[point_id] = std::uniform_int_distribution<int>(0, costmap_->getSizeInCellsX() - 1)(gen);
         temp_y[point_id] = std::uniform_int_distribution<int>(0, costmap_->getSizeInCellsY() - 1)(gen);
         pos_id = grid2Index(temp_x[point_id], temp_y[point_id]);
       }
       else
       {
         // Generate random angle in radians
         double angle = std::uniform_real_distribution<double>(0, 2 * M_PI)(gen);
         // Generate random distance from the center within the circle
         double r = std::sqrt(std::uniform_real_distribution<double>(0, 1)(gen)) * radius;
         // Convert polar coordinates to Cartesian coordinates
         temp_x[point_id] = static_cast<int>(std::round(center_x + r * std::cos(angle)));
         temp_y[point_id] = static_cast<int>(std::round(center_y + r * std::sin(angle)));
         // Check if the coordinates are within the map range
         if (temp_x[point_id] >= 0 && temp_x[point_id] < costmap_->getSizeInCellsX() && temp_y[point_id] >= 0 &&
             temp_y[point_id] < costmap_->getSizeInCellsY())
           pos_id = grid2Index(temp_x[point_id], temp_y[point_id]);
         else
           continue;
       }
       // Check if the coordinates have already been used
       if (visited.find(pos_id) == visited.end())
       {
         point_id++;
         visited.insert(pos_id);
         double prob_new = std::pow(pheromone_mat_[pos_id], alpha_) *
                           std::pow(1.0 / hypot(temp_x[point_id] - goal.x(), temp_y[point_id] - goal.y()), beta_);
         probabilities.push_back(prob_new);
         prob_sum += prob_new;
       }
     }
     // roulette selection
     std::for_each(probabilities.begin(), probabilities.end(), [&](double& p) { p /= prob_sum; });
     std::random_device device;
     std::mt19937 engine(device());
     std::discrete_distribution<> dist(probabilities.begin(), probabilities.end());
     for (size_t j = 0; j < point_num_; j++)
     {
       int idx = dist(engine);
       x[j] = temp_x[idx];
       y[j] = temp_y[idx];
     }
     // sort
     if (x_order)
       std::sort(x, x + point_num_, [](int a, int b) { return a < b; });
     else
       std::sort(x, x + point_num_, [](int a, int b) { return a > b; });
     if (y_order)
       std::sort(y, y + point_num_, [](int a, int b) { return a < b; });
     else
       std::sort(y, y + point_num_, [](int a, int b) { return a > b; });
     // Store elements from x and y in particle_positions
     for (int j = 0; j < point_num_; ++j)
       ant_positions.emplace_back(x[j], y[j]);
     initial_positions.push_back(ant_positions);
   }
 }
References key_ctrl::a, alpha_, OkayPlan_main::b, beta_, rmp::path_planner::PathPlanner::costmap_, rmp::path_planner::PathPlanner::grid2Index(), Layer2_RandomPlanner_laser::idx, n_ants_, pheromone_mat_, point_num_, rviz_generate::r, FakeAMCL::x, rmp::common::geometry::Point2_< T >::x(), FakeAMCL::y, and rmp::common::geometry::Point2_< T >::y().
Referenced by updateAnts().
optimizeAnt()
void rmp::path_planner::ACOPathPlanner::optimizeAnt (Ant & ant, Ant & best_ant, std::mt19937 & gen, Points3d & expand)
Ant update optimization iteration.
Parameters
ant Ants to be updated for velocity
best_ant Global optimal ant
gen randomizer
expand containing the node been search during the process
 {
   // Calculate fitness
   ant.fitness = calFitnessValue(ant.position);
   // reward here, increased pheromone
   double c = Q_ / static_cast<double>(ant.fitness);
   // Update expand points
   std::lock_guard<std::mutex> lock(mutex_);
   for (const auto& pos : ant.position)
   {
     pheromone_mat_[grid2Index(static_cast<int>(pos.x()), static_cast<int>(pos.y()))] += c;
     expand.emplace_back(pos.x(), pos.y());
   }
   if (ant.best_fitness > best_ant.fitness)
   {
     best_ant.fitness = ant.best_fitness;
     best_ant.position = ant.position;
   }
 }
References rmp::path_planner::ACOPathPlanner::Ant::best_fitness, calFitnessValue(), rmp::path_planner::ACOPathPlanner::Ant::fitness, rmp::path_planner::PathPlanner::grid2Index(), mutex_, pheromone_mat_, rmp::path_planner::ACOPathPlanner::Ant::position, and Q_.
Referenced by plan().
plan()
bool rmp::path_planner::ACOPathPlanner::plan (const Point3d & start, const Point3d & goal, Points3d & path, Points3d & expand) virtual
ACO implementation.
Parameters
start start node
goal goal node
path optimal path consists of Node
expand containing the node been search during the process
Returns
true if path found, else false
Parameters
start start node
goal goal node
path optimal path consists of Node
expand containing the node been search during the process(unused)
Returns
true if path found, else false
Implements rmp::path_planner::PathPlanner.
 {
   start_.setX(start.x());
   start_.setY(start.y());
   goal_.setX(goal.x());
   goal_.setY(goal.y());
   expand.clear();
   for (size_t i = 0; i < map_size_; i++)
     pheromone_mat_[i] = 1.0;
   // variable initialization
   Ant best_ant;
   best_ant.fitness = -1;
   std::vector<Ant> ants(n_ants_);
   updateAnts(ants, start_, goal_, best_ant);
   // random data
   std::random_device rd;
   std::mt19937 gen(rd());
   // Iterative optimization
   for (size_t iter = 0; iter < max_iter_; iter++)
   {
     updateAnts(ants, start_, goal_, best_ant);
     std::vector<std::thread> ants_list = std::vector<std::thread>(n_ants_);
     for (size_t i = 0; i < n_ants_; ++i)
       ants_list[i] = std::thread(&ACOPathPlanner::optimizeAnt, this, std::ref(ants[i]), std::ref(best_ant),
                                  std::ref(gen), std::ref(expand));
     for (size_t i = 0; i < n_ants_; ++i)
       ants_list[i].join();
     // best_ant.position = ants[best_ant_idx_].best_pos;
     // pheromone deterioration
     for (size_t i = 0; i < map_size_; i++)
       pheromone_mat_[i] *= (1 - rho_);
   }
   // Generating Paths from Optimal Particles
   Points2d points, b_path;
   points.emplace_back(start.x(), start.y());
   for (const auto& pos : best_ant.position)
     points.emplace_back(pos.x(), pos.y());
   points.emplace_back(goal.x(), goal.y());
   points.erase(std::unique(std::begin(points), std::end(points)), std::end(points));
   bspline_gen_->run(points, b_path);
   // Path data structure conversion
   path.clear();
   for (const auto& pt : b_path)
   {
     path.emplace_back(pt.x(), pt.y());
   }
   // Update inheritance ants based on optimal fitness
   std::sort(ants.begin(), ants.end(), [](const Ant& a, const Ant& b) { return a.best_fitness > b.best_fitness; });
   inherited_ants_.clear();
   for (size_t inherit = 0; inherit < n_inherited_; ++inherit)
     inherited_ants_.emplace_back(ants[inherit]);
   return !path.empty();
 }
References key_ctrl::a, OkayPlan_main::b, bspline_gen_, rmp::path_planner::ACOPathPlanner::Ant::fitness, goal_, inherited_ants_, rmp::path_planner::PathPlanner::map_size_, max_iter_, n_ants_, n_inherited_, optimizeAnt(), pheromone_mat_, rmp::path_planner::ACOPathPlanner::Ant::position, rho_, rmp::common::geometry::Point2_< T >::setX(), rmp::common::geometry::Point2_< T >::setY(), start_, updateAnts(), rmp::common::geometry::Point3_< T >::x(), and rmp::common::geometry::Point3_< T >::y().
updateAnts()
void rmp::path_planner::ACOPathPlanner::updateAnts (std::vector< Ant > & ants, const Point2d & start, const Point2d & goal, Ant & best_ant)
 {
   double init_fitness;
   PositionSequence init_positions;
   // Generate initial position of particle swarm
   initializePositions(init_positions, start, goal, init_mode_);
   // Ant initialization
   for (int i = 0; i < n_ants_; ++i)
   {
     Points2d init_position;
     if ((i < n_inherited_) && (inherited_ants_.size() == n_inherited_))
       init_position = inherited_ants_[i].best_pos;
     else
       init_position = init_positions[i];
     // Calculate fitness
     init_fitness = calFitnessValue(init_position);
     if (init_fitness > best_ant.fitness)
     {
       best_ant.position = init_position;
       best_ant.fitness = init_fitness;
     }
     // Create and add particle objects to containers
     ants[i] = { init_position, init_fitness };
   }
 }
References calFitnessValue(), rmp::path_planner::ACOPathPlanner::Ant::fitness, inherited_ants_, init_mode_, initializePositions(), n_ants_, n_inherited_, and rmp::path_planner::ACOPathPlanner::Ant::position.
Referenced by plan().
Member Data Documentation
alpha_
double rmp::path_planner::ACOPathPlanner::alpha_ protected
Referenced by initializePositions().
beta_
double rmp::path_planner::ACOPathPlanner::beta_ protected
Referenced by initializePositions().
bspline_gen_
std::unique_ptr<rmp::common::geometry::BSplineCurve> rmp::path_planner::ACOPathPlanner::bspline_gen_ private
Referenced by ACOPathPlanner(), calFitnessValue(), and plan().
goal_
Point2d rmp::path_planner::ACOPathPlanner::goal_ protected
Referenced by calFitnessValue(), and plan().
inherited_ants_
std::vector<Ant> rmp::path_planner::ACOPathPlanner::inherited_ants_ private
Referenced by ACOPathPlanner(), plan(), and updateAnts().
init_mode_
int rmp::path_planner::ACOPathPlanner::init_mode_ protected
Referenced by updateAnts().
max_iter_
int rmp::path_planner::ACOPathPlanner::max_iter_ protected
Referenced by plan().
mutex_
std::mutex rmp::path_planner::ACOPathPlanner::mutex_ private
Referenced by optimizeAnt().
n_ants_
int rmp::path_planner::ACOPathPlanner::n_ants_ protected
Referenced by initializePositions(), plan(), and updateAnts().
n_inherited_
int rmp::path_planner::ACOPathPlanner::n_inherited_ protected
Referenced by plan(), and updateAnts().
pheromone_mat_
double* rmp::path_planner::ACOPathPlanner::pheromone_mat_ protected
Referenced by ACOPathPlanner(), initializePositions(), optimizeAnt(), plan(), and ~ACOPathPlanner().
point_num_
int rmp::path_planner::ACOPathPlanner::point_num_ protected
Referenced by initializePositions().
Q_
double rmp::path_planner::ACOPathPlanner::Q_ protected
Referenced by optimizeAnt().
rho_
double rmp::path_planner::ACOPathPlanner::rho_ protected
Referenced by plan().
start_
Point2d rmp::path_planner::ACOPathPlanner::start_ protected
Referenced by calFitnessValue(), and plan().
The documentation for this class was generated from the following files:
src/core/path_planner/path_planner/include/path_planner/evolutionary_planner/aco_planner.h
src/core/path_planner/path_planner/src/evolutionary_planner/aco_planner.cpp