ROS Motion Planning: rmp::common::geometry::CubicSplineCurve Class Reference
rmp::common::geometry::CubicSplineCurve Class Reference
#include <cubic_spline_curve.h>
Public Member Functions
CubicSplineCurve ()
Construct a new Cubic spline generation object.
CubicSplineCurve (double step)
Construct a new Cubic spline generation object.
~CubicSplineCurve ()
Destroy the Cubic spline generation object.
bool run (const Points2d points, Points2d &path)
Running trajectory generation.
bool run (const Points3d points, Points2d &path)
Running trajectory generation.
std::vector< double > spline (std::vector< double > s_list, std::vector< double > dir_list, std::vector< double > t)
Calculate the spline curve value in a certain direction.
Public Member Functions inherited from rmp::common::geometry::Curve
Curve (double step)
Construct a new Curve object.
virtual ~Curve ()=default
Destroy the curve generation object.
double len (Points2d path)
Calculate length of given path.
void setStep (double step)
Configure the simulation step.
Additional Inherited Members
Protected Attributes inherited from rmp::common::geometry::Curve
double step_
Constructor & Destructor Documentation
CubicSplineCurve() [1/2]
rmp::common::geometry::CubicSplineCurve::CubicSplineCurve ()
Construct a new Cubic spline generation object.
Parameters
step Simulation or interpolation size (default: 0.1)
                                    : Curve(0.1)
 {
 }
CubicSplineCurve() [2/2]
rmp::common::geometry::CubicSplineCurve::CubicSplineCurve (double step)
Construct a new Cubic spline generation object.
Parameters
step Simulation or interpolation size (default: 0.1)
offset The offset of control points (default: 3.0)
                                               : Curve(step)
 {
 }
~CubicSplineCurve()
rmp::common::geometry::CubicSplineCurve::~CubicSplineCurve ()
Destroy the Cubic spline generation object.
 {
 }
Member Function Documentation
run() [1/2]
bool rmp::common::geometry::CubicSplineCurve::run (const Points2d points, Points2d & path) virtual
Running trajectory generation.
Parameters
points path points <x, y>
path generated trajectory
Returns
true if generate successfully, else failed
Implements rmp::common::geometry::Curve.
 {
   if (points.size() < 4)
     return false;
   else
   {
     std::vector<double> x_list, y_list;
     for (const auto& p : points)
     {
       x_list.push_back(p.x());
       y_list.push_back(p.y());
     }
     std::vector<double> s;
     s.push_back(0.0);
     double d_cumsum = 0.0;
     for (size_t i = 0; i < points.size() - 1; i++)
     {
       double d = std::hypot(points[i].x() - points[i + 1].x(), points[i].y() - points[i + 1].y());
       d_cumsum += d;
       s.push_back(d_cumsum);
     }
     double ds = 0.0;
     std::vector<double> t;
     while (ds < s.back())
     {
       t.push_back(ds);
       ds += step_;
     }
     std::vector<double> path_x = spline(s, x_list, t);
     std::vector<double> path_y = spline(s, y_list, t);
     path.clear();
     for (size_t i = 0; i < path_x.size(); i++)
       path.emplace_back(path_x[i], path_y[i]);
     return !path.empty();
   }
 }
References rviz_generate::d, key_ctrl::s, spline(), rmp::common::geometry::Curve::step_, FakeAMCL::x, and FakeAMCL::y.
Referenced by run().
run() [2/2]
bool rmp::common::geometry::CubicSplineCurve::run (const Points3d points, Points2d & path) virtual
Running trajectory generation.
Parameters
points path points <x, y, theta>
path generated trajectory
Returns
true if generate successfully, else failed
Implements rmp::common::geometry::Curve.
 {
   if (points.size() < 4)
   {
     return false;
   }
   else
   {
     Points2d points_;
     for (const auto& p : points)
       points_.emplace_back(p.x(), p.y());
     return run(points_, path);
   }
 }
References run().
spline()
std::vector< double > rmp::common::geometry::CubicSplineCurve::spline (std::vector< double > s_list, std::vector< double > dir_list, std::vector< double > t)
Calculate the spline curve value in a certain direction.
Parameters
s_list distance vector
dir_list direction vector (-x or -y)
t scale factor
Returns
spline_val_dir the spline curve value in a certain direction
 {
   // cubic polynomial functions
   std::vector<double> a = dir_list;
   std::vector<double> b, d;
   size_t num = s_list.size();
   std::vector<double> h;
   for (size_t i = 0; i < num - 1; i++)
     h.push_back(s_list[i + 1] - s_list[i]);
   // calculate coefficient matrix
   Eigen::MatrixXd A = Eigen::MatrixXd::Zero(num, num);
   for (size_t i = 1; i < num - 1; i++)
   {
     A(i, i - 1) = h[i - 1];
     A(i, i) = 2.0 * (h[i - 1] + h[i]);
     A(i, i + 1) = h[i];
   }
   A(0, 0) = 1.0;
   A(num - 1, num - 1) = 1.0;
   Eigen::MatrixXd B = Eigen::MatrixXd::Zero(num, 1);
   for (size_t i = 1; i < num - 1; i++)
     B(i, 0) = 3.0 * (a[i + 1] - a[i]) / h[i] - 3.0 * (a[i] - a[i - 1]) / h[i - 1];
   Eigen::MatrixXd c = A.lu().solve(B);
   for (size_t i = 0; i < num - 1; i++)
   {
     b.push_back((a[i + 1] - a[i]) / h[i] - h[i] * (c(i + 1) + 2.0 * c(i)) / 3.0);
     d.push_back((c(i + 1) - c(i)) / (3.0 * h[i]));
   }
   // calculate spline value and its derivative
   std::vector<double> p;
   for (const auto it : t)
   {
     auto iter = std::find_if(s_list.begin(), s_list.end(), [it](double val) { return val > it; });
     if (iter != s_list.end())
     {
       size_t idx = std::distance(s_list.begin(), iter) - 1;
       double ds = it - s_list[idx];
       p.push_back(a[idx] + b[idx] * ds + c(idx) * std::pow(ds, 2) + d[idx] * std::pow(ds, 3));
     }
   }
   return p;
 }
References key_ctrl::a, OkayPlan_main::b, rviz_generate::d, and Layer2_RandomPlanner_laser::idx.
Referenced by run().
The documentation for this class was generated from the following files:
src/core/common/include/common/geometry/cubic_spline_curve.h
src/core/common/src/geometry/cubic_spline_curve.cpp