ROS Motion Planning: rmp::path_planner::RRTConnectPathPlanner Class Reference
rmp::path_planner::RRTConnectPathPlanner Class Reference
Class for objects that plan using the RRT Connect algorithm.
#include <rrt_connect_planner.h>
Public Member Functions
RRTConnectPathPlanner (costmap_2d::Costmap2DROS *costmap_ros, int sample_num, double max_dist)
Constructor.
bool plan (const Point3d &start, const Point3d &goal, Points3d &path, Points3d &expand)
RRT implementation.
Public Member Functions inherited from rmp::path_planner::RRTPathPlanner
RRTPathPlanner (costmap_2d::Costmap2DROS *costmap_ros, int sample_num, double max_dist)
Constructor.
bool plan (const Point3d &start, const Point3d &goal, Points3d &path, Points3d &expand)
RRT implementation.
Public Member Functions inherited from rmp::path_planner::PathPlanner
PathPlanner (costmap_2d::Costmap2DROS *costmap_ros)
Construct a new Global PathPlanner object.
virtual ~PathPlanner ()=default
Destroy the Global PathPlanner object.
void setFactor (float factor)
Set or reset obstacle factor.
costmap_2d::Costmap2D * getCostMap () const
get the costmap
int getMapSize () const
get the size of costmap
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap ()
Inflate the boundary of costmap into obstacles to prevent cross planning.
Protected Member Functions
std::vector< Node > _convertClosedListToPath (const Node &boundary)
convert closed list to path
Protected Member Functions inherited from rmp::path_planner::RRTPathPlanner
Node _findNearestPoint (std::unordered_map< int, Node > &list, const Node &node)
Regular the sample node by the nearest node in the sample list.
Node _generateRandomNode ()
Generates a random node.
bool _checkGoal (const Node &new_node)
Check if goal is reachable from current node.
Protected Member Functions inherited from rmp::path_planner::PathPlanner
template<typename Node >
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
template<typename Node >
std::vector< Node > _convertBiClosedListToPath (std::unordered_map< int, Node > &f_closed_list, std::unordered_map< int, Node > &b_closed_list, const Node &start, const Node &goal, const Node &boundary)
Protected Attributes
std::unordered_map< int, Node > sample_list_f_
std::unordered_map< int, Node > sample_list_b_
Protected Attributes inherited from rmp::path_planner::RRTPathPlanner
Node start_
Node goal_
std::unordered_map< int, Node > sample_list_
int sample_num_
double max_dist_
double opti_sample_p_ = 0.05
Protected Attributes inherited from rmp::path_planner::PathPlanner
int map_size_
float factor_
costmap_2d::Costmap2DROS * costmap_ros_
costmap_2d::Costmap2D * costmap_
Private Types
using Node = rmp::common::structure::Node< int >
Additional Inherited Members
Public Types inherited from rmp::path_planner::PathPlanner
using Point2d = rmp::common::geometry::Point2d
using Point3d = rmp::common::geometry::Point3d
using Points2d = rmp::common::geometry::Points2d
using Points3d = rmp::common::geometry::Points3d
Detailed Description
Class for objects that plan using the RRT Connect algorithm.
Member Typedef Documentation
Node
using rmp::path_planner::RRTConnectPathPlanner::Node = rmp::common::structure::Node<int> private
Constructor & Destructor Documentation
RRTConnectPathPlanner()
rmp::path_planner::RRTConnectPathPlanner::RRTConnectPathPlanner (costmap_2d::Costmap2DROS * costmap_ros, int sample_num, double max_dist)
Constructor.
Parameters
costmap the environment for path planning
sample_num andom sample points
max_dist max distance between sample points
   : RRTPathPlanner(costmap_ros, sample_num, max_dist)
 {
 }
Member Function Documentation
_convertClosedListToPath()
std::vector<Node> rmp::path_planner::RRTConnectPathPlanner::_convertClosedListToPath (const Node & boundary) protected
convert closed list to path
Parameters
boundary connected node that the boudary of forward and backward
Returns
ector containing path nodes
plan()
bool rmp::path_planner::RRTConnectPathPlanner::plan (const Point3d & start, const Point3d & goal, Points3d & path, Points3d & expand) virtual
RRT implementation.
RRT-Connect implementation.
Parameters
start start node
goal goal node
expand containing the node been search during the process
Returns
tuple contatining a bool as to whether a path was found, and the path
Implements rmp::path_planner::PathPlanner.
 {
   path.clear();
   expand.clear();
   sample_list_f_.clear();
   sample_list_b_.clear();
   // copy
   start_.set_x(start.x());
   start_.set_y(start.y());
   start_.set_id(grid2Index(start_.x(), start_.y()));
   goal_.set_x(goal.x());
   goal_.set_y(goal.y());
   goal_.set_id(grid2Index(goal_.x(), goal_.y()));
   sample_list_f_.insert(std::make_pair(start_.id(), start_));
   sample_list_b_.insert(std::make_pair(goal_.id(), goal_));
   expand.emplace_back(start.x(), start.y(), 0);
   expand.emplace_back(goal.x(), goal.y(), 0);
   // main loop
   int iteration = 0;
   while (iteration < sample_num_)
   {
     // generate a random node in the map
     Node sample_node = _generateRandomNode();
     // obstacle
     if (costmap_->getCharMap()[sample_node.id()] >= costmap_2d::LETHAL_OBSTACLE * factor_)
       continue;
     // visited
     if (sample_list_.find(sample_node.id()) != sample_list_.end())
       continue;
     // regular the sample node
     Node new_node = _findNearestPoint(sample_list_f_, sample_node);
     if (new_node.id() == -1)
     {
       continue;
     }
     else
     {
       sample_list_f_.insert(std::make_pair(new_node.id(), new_node));
       expand.emplace_back(new_node.x(), new_node.y(), new_node.pid());
       // backward exploring
       Node new_node_b = _findNearestPoint(sample_list_b_, new_node);
       if (new_node_b.id() != -1)
       {
         sample_list_b_.insert(std::make_pair(new_node_b.id(), new_node_b));
         expand.emplace_back(new_node_b.x(), new_node_b.y(), new_node_b.pid());
         // greedy extending
         while (true)
         {
           double dist_ = std::min(max_dist_, std::hypot(new_node.x() - new_node_b.x(), new_node.y() - new_node_b.y()));
           double theta = std::atan2(new_node.y() - new_node_b.y(), new_node.x() - new_node_b.x());
           Node new_node_b2;
           new_node_b2.set_x(new_node_b.x() + static_cast<int>(dist_ * cos(theta)));
           new_node_b2.set_y(new_node_b.y() + static_cast<int>(dist_ * sin(theta)));
           new_node_b2.set_id(grid2Index(new_node_b2.x(), new_node_b2.y()));
           new_node_b2.set_pid(new_node_b.id());
           new_node_b2.set_g(dist_ + new_node_b.g());
           auto isCollision = [&](const Node& node1, const Node& node2) {
             return CollisionChecker::BresenhamCollisionDetection(node1, node2, [&](const Node& node) {
               return costmap_->getCharMap()[grid2Index(node.x(), node.y())] >= costmap_2d::LETHAL_OBSTACLE * factor_;
             });
           };
           if (!isCollision(new_node_b, new_node_b2))
           {
             sample_list_b_.insert(std::make_pair(new_node_b2.id(), new_node_b2));
             expand.emplace_back(new_node_b2.x(), new_node_b2.y(), new_node_b2.pid());
             new_node_b = new_node_b2;
           }
           else
             break;
           // connected -> goal found
           if (new_node_b == new_node)
           {
             const auto& backtrace =
                 _convertBiClosedListToPath<Node>(sample_list_f_, sample_list_b_, start_, goal_, new_node_b);
             for (auto iter = backtrace.rbegin(); iter != backtrace.rend(); ++iter)
             {
               path.emplace_back(iter->x(), iter->y());
             }
             return true;
           }
         }
       }
     }
     // swap
     if (sample_list_b_.size() < sample_list_f_.size())
       std::swap(sample_list_f_, sample_list_b_);
     iteration++;
   }
   return false;
 }
References rmp::path_planner::RRTPathPlanner::_findNearestPoint(), rmp::path_planner::RRTPathPlanner::_generateRandomNode(), rmp::path_planner::PathPlanner::costmap_, rmp::path_planner::PathPlanner::factor_, rmp::common::structure::Node< T >::g(), rmp::path_planner::RRTPathPlanner::goal_, rmp::path_planner::PathPlanner::grid2Index(), rmp::common::structure::Node< T >::id(), rmp::path_planner::RRTPathPlanner::max_dist_, tf_map2odom::node, rmp::common::structure::Node< T >::pid(), rmp::path_planner::RRTPathPlanner::sample_list_, sample_list_b_, sample_list_f_, rmp::path_planner::RRTPathPlanner::sample_num_, rmp::common::structure::Node< T >::set_g(), rmp::common::structure::Node< T >::set_id(), rmp::common::structure::Node< T >::set_pid(), rmp::common::structure::Node< T >::set_x(), rmp::common::structure::Node< T >::set_y(), rmp::path_planner::RRTPathPlanner::start_, rmp::common::structure::Node< T >::x(), rmp::common::geometry::Point3_< T >::x(), rmp::common::structure::Node< T >::y(), and rmp::common::geometry::Point3_< T >::y().
Member Data Documentation
sample_list_b_
std::unordered_map<int, Node> rmp::path_planner::RRTConnectPathPlanner::sample_list_b_ protected
Referenced by plan().
sample_list_f_
std::unordered_map<int, Node> rmp::path_planner::RRTConnectPathPlanner::sample_list_f_ protected
Referenced by plan().
The documentation for this class was generated from the following files:
src/core/path_planner/path_planner/include/path_planner/sample_planner/rrt_connect_planner.h
src/core/path_planner/path_planner/src/sample_planner/rrt_connect_planner.cpp