ROS Motion Planning: rmp::common::geometry::Point2_< T > Class Template Reference
rmp::common::geometry::Point2_< T > Class Template Reference
#include <point.h>
Public Member Functions
Point2_ (T x=0, T y=0)
~Point2_ ()=default
T x () const
T y () const
void setX (T x)
void setY (T y)
T operator[] (size_t i) const
bool operator== (const Point2_ &other)
bool operator!= (const Point2_ &other)
Static Public Attributes
static const int dim = 2
Private Attributes
T x_
T y_
Constructor & Destructor Documentation
Point2_()
template<typename T > rmp::common::geometry::Point2_< T >::Point2_ (T x = 0, T y = 0) inline
 :
   Point3_(T x = 0, T y = 0, T theta = 0) : x_(x), y_(y), theta_(theta){};
~Point2_()
template<typename T > rmp::common::geometry::Point2_< T >::~Point2_ () default
Member Function Documentation
operator!=()
template<typename T > bool rmp::common::geometry::Point2_< T >::operator!= (const Point2_< T > & other) inline
   {
     return i == 0 ? x_ : (i == 1 ? y_ : theta_);
operator==()
template<typename T > bool rmp::common::geometry::Point2_< T >::operator== (const Point2_< T > & other) inline
   {
     theta_ = theta;
References rmp::common::geometry::Point3_< T >::theta(), and rmp::common::geometry::Point3_< T >::theta_.
operator[]()
template<typename T > T rmp::common::geometry::Point2_< T >::operator[] (size_t i) const inline
   {
     y_ = y;
References rmp::common::geometry::Point3_< T >::y(), and rmp::common::geometry::Point3_< T >::y_.
setX()
template<typename T > void rmp::common::geometry::Point2_< T >::setX (T x) inline
   {
     return theta_;
References rmp::common::geometry::Point3_< T >::theta_.
Referenced by rmp::path_planner::ACOPathPlanner::plan(), rmp::path_planner::GAPathPlanner::plan(), and rmp::path_planner::PSOPathPlanner::plan().
setY()
template<typename T > void rmp::common::geometry::Point2_< T >::setY (T y) inline
   {
     x_ = x;
References rmp::common::geometry::Point3_< T >::x(), and rmp::common::geometry::Point3_< T >::x_.
Referenced by rmp::path_planner::ACOPathPlanner::plan(), rmp::path_planner::GAPathPlanner::plan(), and rmp::path_planner::PSOPathPlanner::plan().
x()
template<typename T > T rmp::common::geometry::Point2_< T >::x () const inline
   {
     return x_;
References rmp::common::geometry::Point3_< T >::x_.
Referenced by rmp::path_planner::ACOPathPlanner::initializePositions(), rmp::path_planner::GAPathPlanner::initializePositions(), and rmp::path_planner::PSOPathPlanner::initializePositions().
y()
template<typename T > T rmp::common::geometry::Point2_< T >::y () const inline
   {
     return y_;
References rmp::common::geometry::Point3_< T >::y_.
Referenced by rmp::path_planner::ACOPathPlanner::initializePositions(), rmp::path_planner::GAPathPlanner::initializePositions(), and rmp::path_planner::PSOPathPlanner::initializePositions().
Member Data Documentation
dim
template<typename T > const int rmp::common::geometry::Point2_< T >::dim = 2 static
x_
template<typename T > T rmp::common::geometry::Point2_< T >::x_ private
y_
template<typename T > T rmp::common::geometry::Point2_< T >::y_ private
The documentation for this class was generated from the following file:
src/core/common/include/common/geometry/point.h