ROS Motion Planning: rmp::path_planner::HybridAStarPathPlanner Class Reference
rmp::path_planner::HybridAStarPathPlanner Class Reference
Class for objects that plan using the A* algorithm.
#include <hybrid_astar_planner.h>
Classes
class HybridNode
Public Types
using Node = rmp::common::structure::Node< double >
Public Types inherited from rmp::path_planner::PathPlanner
using Point2d = rmp::common::geometry::Point2d
using Point3d = rmp::common::geometry::Point3d
using Points2d = rmp::common::geometry::Points2d
using Points3d = rmp::common::geometry::Points3d
Public Member Functions
HybridAStarPathPlanner (costmap_2d::Costmap2DROS *costmap_ros, bool is_reverse, double max_curv)
Construct a new Hybrid A* object.
~HybridAStarPathPlanner ()=default
Destory the Hybrid A* object.
bool plan (const Point3d &start, const Point3d &goal, Points3d &path, Points3d &expand)
Hybrid A* implementation.
bool dubinsShot (const HybridNode &start, const HybridNode &goal, std::vector< HybridNode > &path)
Try using Dubins curves to connect the start and goal.
void updateIndex (HybridNode &node)
update index of hybrid node
void updateHeuristic (HybridNode &node)
update the h-value of hybrid node
void genHeurisiticMap (const Node &start)
generate heurisitic map using A* algorithm, each matric of map is the distance between it and start.
Public Member Functions inherited from rmp::path_planner::PathPlanner
PathPlanner (costmap_2d::Costmap2DROS *costmap_ros)
Construct a new Global PathPlanner object.
virtual ~PathPlanner ()=default
Destroy the Global PathPlanner object.
void setFactor (float factor)
Set or reset obstacle factor.
costmap_2d::Costmap2D * getCostMap () const
get the costmap
int getMapSize () const
get the size of costmap
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap ()
Inflate the boundary of costmap into obstacles to prevent cross planning.
Protected Member Functions
int _worldToIndex (double wx, double wy)
Tranform from world map(x, y) to grid index(i)
std::vector< HybridNode > _convertClosedListToPath (std::unordered_map< int, HybridNode > &closed_list, const HybridNode &start, const HybridNode &goal)
Convert closed list to path.
Protected Member Functions inherited from rmp::path_planner::PathPlanner
template<typename Node >
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
template<typename Node >
std::vector< Node > _convertBiClosedListToPath (std::unordered_map< int, Node > &f_closed_list, std::unordered_map< int, Node > &b_closed_list, const Node &start, const Node &goal, const Node &boundary)
Private Attributes
HybridNode goal_
std::unordered_map< int, Node > h_map_
bool is_reverse_
double max_curv_
std::unique_ptr< AStarPathPlanner > a_star_planner_
std::unique_ptr< rmp::common::geometry::DubinsCurve > dubins_gen_
Additional Inherited Members
Protected Attributes inherited from rmp::path_planner::PathPlanner
int map_size_
float factor_
costmap_2d::Costmap2DROS * costmap_ros_
costmap_2d::Costmap2D * costmap_
Detailed Description
Class for objects that plan using the A* algorithm.
Member Typedef Documentation
Node
using rmp::path_planner::HybridAStarPathPlanner::Node = rmp::common::structure::Node<double>
Constructor & Destructor Documentation
HybridAStarPathPlanner()
rmp::path_planner::HybridAStarPathPlanner::HybridAStarPathPlanner (costmap_2d::Costmap2DROS * costmap_ros, bool is_reverse, double max_curv)
Construct a new Hybrid A* object.
Parameters
costmap the environment for path planning
is_reverse whether reverse operation is allowed
max_curv maximum curvature of model
   : PathPlanner(costmap_ros)
   , is_reverse_(is_reverse)
   , max_curv_(max_curv)
   , dubins_gen_(std::make_unique<rmp::common::geometry::DubinsCurve>(1.5, max_curv))
   , a_star_planner_(std::make_unique<AStarPathPlanner>(costmap_ros))
   , goal_(HybridNode())
 {
 }
~HybridAStarPathPlanner()
rmp::path_planner::HybridAStarPathPlanner::~HybridAStarPathPlanner () default
Destory the Hybrid A* object.
Member Function Documentation
_convertClosedListToPath()
std::vector< HybridAStarPathPlanner::HybridNode > rmp::path_planner::HybridAStarPathPlanner::_convertClosedListToPath (std::unordered_map< int, HybridNode > & closed_list, const HybridNode & start, const HybridNode & goal) protected
Convert closed list to path.
Parameters
closed_list closed list
start start node
goal goal node
Returns
vector containing path nodes
 {
   double cur_x, cur_y;
   std::vector<HybridNode> path;
   auto current = closed_list.find(goal.id());
   while (current->second != start)
   {
     world2Map(current->second.x(), current->second.y(), cur_x, cur_y);
     path.emplace_back(cur_x, cur_y);
     auto it = closed_list.find(current->second.pid());
     if (it != closed_list.end())
       current = it;
     else
       return {};
   }
   world2Map(start.x(), start.y(), cur_x, cur_y);
   path.emplace_back(cur_x, cur_y);
   return path;
 }
References rmp::common::structure::Node< T >::id(), rmp::path_planner::PathPlanner::world2Map(), rmp::common::structure::Node< T >::x(), and rmp::common::structure::Node< T >::y().
Referenced by plan().
_worldToIndex()
int rmp::path_planner::HybridAStarPathPlanner::_worldToIndex (double wx, double wy) protected
Tranform from world map(x, y) to grid index(i)
Parameters
wx world map x
wy world map y
Returns
index
 {
   double gx, gy;
   world2Map(wx, wy, gx, gy);
   return grid2Index(gx, gy);
 }
References rmp::path_planner::PathPlanner::grid2Index(), and rmp::path_planner::PathPlanner::world2Map().
Referenced by plan(), updateHeuristic(), and updateIndex().
dubinsShot()
bool rmp::path_planner::HybridAStarPathPlanner::dubinsShot (const HybridNode & start, const HybridNode & goal, std::vector< HybridNode > & path)
Try using Dubins curves to connect the start and goal.
Parameters
start start node
goal goal node
path dubins path between start and goal
Returns
true if shot successfully, else false
 {
   double sx, sy, gx, gy;
   world2Map(start.x(), start.y(), sx, sy);
   world2Map(goal.x(), goal.y(), gx, gy);
   rmp::common::geometry::Points3d poes = { { sx, sy, start.theta() }, { gx, gy, goal.theta() } };
   rmp::common::geometry::Points2d path_dubins;
   if (dubins_gen_->run(poes, path_dubins))
   {
     path.clear();
     for (auto const& p : path_dubins)
     {
       if (costmap_->getCharMap()[grid2Index(p.x(), p.y())] >= costmap_2d::LETHAL_OBSTACLE * factor_)
         return false;
       else
         path.emplace_back(p.x(), p.y());
     }
     return true;
   }
   else
     return false;
 }
References rmp::path_planner::PathPlanner::costmap_, dubins_gen_, rmp::path_planner::PathPlanner::factor_, rmp::path_planner::PathPlanner::grid2Index(), rmp::path_planner::HybridAStarPathPlanner::HybridNode::theta(), rmp::path_planner::PathPlanner::world2Map(), rmp::common::structure::Node< T >::x(), and rmp::common::structure::Node< T >::y().
Referenced by plan().
genHeurisiticMap()
void rmp::path_planner::HybridAStarPathPlanner::genHeurisiticMap (const Node & start)
generate heurisitic map using A* algorithm, each matric of map is the distance between it and start.
Parameters
start start node
 {
   // open list and closed list
   std::priority_queue<Node, std::vector<Node>, Node::compare_cost> open_list;
   std::unordered_map<int, Node> open_set;
   open_list.push(start);
   open_set.emplace(start.id(), start);
   // main process
   while (!open_list.empty())
   {
     // pop current node from open list
     auto current = open_list.top();
     open_list.pop();
     h_map_.emplace(current.id(), current);
     // explore neighbor of current node
     for (const auto& motion : motions)
     {
       // explore a new node
       auto node_new = current + motion;
       node_new.set_g(current.g() + motion.g());
       node_new.set_id(grid2Index(node_new.x(), node_new.y()));
       // node_new in closed list
       if (h_map_.find(node_new.id()) != h_map_.end())
         continue;
       // next node hit the boundary or obstacle
       // prevent planning failed when the current within inflation
       if ((node_new.id() < 0) || (node_new.id() >= map_size_))
         continue;
       if (open_set.find(node_new.id()) != open_set.end())
       {
         if (open_set[node_new.id()].g() > node_new.g())
           open_set[node_new.id()].set_g(node_new.g());
       }
       else
       {
         open_list.push(node_new);
         open_set.emplace(node_new.id(), node_new);
       }
     }
   }
 }
References rmp::path_planner::PathPlanner::grid2Index(), h_map_, rmp::common::structure::Node< T >::id(), rmp::path_planner::PathPlanner::map_size_, and rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::motions.
Referenced by plan().
plan()
bool rmp::path_planner::HybridAStarPathPlanner::plan (const Point3d & start, const Point3d & goal, Points3d & path, Points3d & expand) virtual
Hybrid A* implementation.
Parameters
start start node
goal goal node
path optimal path consists of Node
expand containing the node been search during the process
Returns
true if path found, else false
Implements rmp::path_planner::PathPlanner.
 {
   // intialization
   path.clear();
   expand.clear();
   HybridNode start_node(start.x(), start.y(), start.theta());
   HybridNode goal_node(goal.x(), goal.y(), goal.theta());
   updateIndex(start_node);
   updateIndex(goal_node);
   // update heuristic map
   if (goal_ != goal_node)
   {
     goal_.set_x(goal.x());
     goal_.set_y(goal.y());
     goal_.set_theta(goal.theta());
     double gx, gy;
     world2Map(goal.x(), goal.y(), gx, gy);
     HybridNode h_start(gx, gy, 0, 0, 0, grid2Index(gx, gy), 0);
     genHeurisiticMap(h_start);
   }
   // possible directions and motions
   int dir = is_reverse_ ? 6 : 3;
   const std::vector<HybridNode> motions = HybridNode::getMotion();
   // open list and closed list
   std::priority_queue<HybridNode, std::vector<HybridNode>, HybridNode::compare_cost> open_list;
   std::unordered_map<int, HybridNode> closed_list;
   open_list.push(start_node);
   // main process
   while (!open_list.empty())
   {
     // pop current node from open list
     HybridNode current = open_list.top();
     open_list.pop();
     // current node does not exist in closed list
     if (closed_list.find(current.id()) != closed_list.end())
       continue;
     closed_list.insert(std::make_pair(current.id(), current));
     expand.emplace_back(current.x(), current.y());
     // goal shot
     std::vector<HybridNode> path_dubins;
     if (std::hypot(current.x() - goal.x(), current.y() - goal.y()) < 50)
     {
       if (dubinsShot(current, goal_node, path_dubins))
       {
         const auto& backtrace = _convertClosedListToPath(closed_list, start_node, current);
         for (auto iter = backtrace.rbegin(); iter != backtrace.rend(); ++iter)
         {
           path.emplace_back(iter->x(), iter->y());
         }
         for (const auto& dubins_pt : path_dubins)
         {
           path.emplace_back(dubins_pt.x(), dubins_pt.y());
         }
         return true;
       }
     }
     // explore neighbor of current node
     for (size_t i = 0; i < dir; i++)
     {
       // explore a new node
       HybridNode node_new = current + motions[i];
       updateIndex(node_new);
       // node_new in closed list
       if (closed_list.find(node_new.id()) != closed_list.end())
         continue;
       // next node hit the boundary or obstacle
       // prevent planning failed when the current within inflation
       if ((_worldToIndex(node_new.x(), node_new.y()) < 0) || (_worldToIndex(node_new.x(), node_new.y()) >= map_size_) ||
           (node_new.theta() / kDeltaHeading >= kHeadings) ||
           (costmap_->getCharMap()[_worldToIndex(node_new.x(), node_new.y())] >= costmap_2d::LETHAL_OBSTACLE * factor_ &&
            costmap_->getCharMap()[_worldToIndex(node_new.x(), node_new.y())] >=
                costmap_->getCharMap()[_worldToIndex(current.x(), current.y())]))
         continue;
       node_new.set_pid(current.id());
       updateHeuristic(node_new);
       open_list.push(node_new);
     }
   }
   // candidate A* path
   return a_star_planner_->plan(start, goal, path, expand);
 }
References _convertClosedListToPath(), _worldToIndex(), a_star_planner_, rmp::path_planner::PathPlanner::costmap_, dubinsShot(), rmp::path_planner::PathPlanner::factor_, genHeurisiticMap(), rmp::path_planner::HybridAStarPathPlanner::HybridNode::getMotion(), goal_, rmp::path_planner::PathPlanner::grid2Index(), rmp::common::structure::Node< T >::id(), is_reverse_, rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::kDeltaHeading, rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::kHeadings, rmp::path_planner::PathPlanner::map_size_, rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::motions, rmp::common::structure::Node< T >::set_pid(), rmp::path_planner::HybridAStarPathPlanner::HybridNode::set_theta(), rmp::common::structure::Node< T >::set_x(), rmp::common::structure::Node< T >::set_y(), rmp::path_planner::HybridAStarPathPlanner::HybridNode::theta(), rmp::common::geometry::Point3_< T >::theta(), updateHeuristic(), updateIndex(), rmp::path_planner::PathPlanner::world2Map(), rmp::common::structure::Node< T >::x(), rmp::common::geometry::Point3_< T >::x(), rmp::common::structure::Node< T >::y(), and rmp::common::geometry::Point3_< T >::y().
updateHeuristic()
void rmp::path_planner::HybridAStarPathPlanner::updateHeuristic (HybridNode & node)
update the h-value of hybrid node
Parameters
node hybrid node to update
 {
   // Dubins cost function
   double cost_dubins = 0.0;
   // std::vector<std::tuple<double, double, double>> poes = { { node.x_, node.y_, node.t_ },
   //                                                          { goal_.x_, goal_.y_, goal_.t_ } };
   // std::vector<std::pair<double, double>> path_dubins;
   // if (dubins_gen_.run(poes, path_dubins))
   //   cost_dubins = dubins_gen_.len(path_dubins);
   // 2D search cost function
   double cost_2d = h_map_[_worldToIndex(node.x(), node.y())].g() * costmap_->getResolution();
   node.set_h(std::max(cost_2d, cost_dubins));
 }
References _worldToIndex(), rmp::path_planner::PathPlanner::costmap_, h_map_, and tf_map2odom::node.
Referenced by plan().
updateIndex()
void rmp::path_planner::HybridAStarPathPlanner::updateIndex (HybridNode & node)
update index of hybrid node
Parameters
node hybrid node to update
 {
   node.set_id(static_cast<int>(node.theta() / kDeltaHeading) + _worldToIndex(node.x(), node.y()));
 }
References _worldToIndex(), rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::kDeltaHeading, and tf_map2odom::node.
Referenced by plan().
Member Data Documentation
a_star_planner_
std::unique_ptr<AStarPathPlanner> rmp::path_planner::HybridAStarPathPlanner::a_star_planner_ private
Referenced by plan().
dubins_gen_
std::unique_ptr<rmp::common::geometry::DubinsCurve> rmp::path_planner::HybridAStarPathPlanner::dubins_gen_ private
Referenced by dubinsShot().
goal_
HybridNode rmp::path_planner::HybridAStarPathPlanner::goal_ private
Referenced by plan().
h_map_
std::unordered_map<int, Node> rmp::path_planner::HybridAStarPathPlanner::h_map_ private
Referenced by genHeurisiticMap(), and updateHeuristic().
is_reverse_
bool rmp::path_planner::HybridAStarPathPlanner::is_reverse_ private
Referenced by plan().
max_curv_
double rmp::path_planner::HybridAStarPathPlanner::max_curv_ private
The documentation for this class was generated from the following files:
src/core/path_planner/path_planner/include/path_planner/graph_planner/hybrid_astar_planner.h
src/core/path_planner/path_planner/src/graph_planner/hybrid_astar_planner.cpp