ROS Motion Planning: rmp::path_planner::HybridAStarPathPlanner::HybridNode Class Reference
rmp::path_planner::HybridAStarPathPlanner::HybridNode Class Reference
#include <hybrid_astar_planner.h>
Public Member Functions
HybridNode (double x=0, double y=0, double theta=0, double g=0.0, double h=0.0, int id=0, int pid=0, int prim=0)
Constructor for Hybrid Node class.
double theta () const
void set_theta (double theta)
HybridNode operator+ (const HybridNode &n) const
Overloading operator + for Node class.
bool operator== (const HybridNode &n) const
Overloading operator == for Node class.
bool operator!= (const HybridNode &n) const
Overloading operator != for Node class.
Public Member Functions inherited from rmp::common::structure::Node< T >
Node (T x=0, T y=0, double g=0.0, double h=0.0, int id=0, int pid=0)
Constructor for Node class.
Node (const Node &n)
T x () const
get the property of node
T y () const
double g () const
double h () const
int id () const
int pid () const
void set_x (T x)
set the property of node
void set_y (T y)
void set_g (double g)
void set_h (double h)
void set_id (int id)
void set_pid (int pid)
Node operator+ (const Node &n) const
Overloading operator + for Node class.
Node operator- (const Node &n) const
Overloading operator - for Node class.
bool operator== (const Node &n) const
Overloading operator == for Node class.
bool operator!= (const Node &n) const
Overloading operator != for Node class.
Static Public Member Functions
static std::vector< HybridNode > getMotion ()
Get permissible motion.
Private Attributes
double theta_
int prim_
Additional Inherited Members
Protected Attributes inherited from rmp::common::structure::Node< T >
T x_
T y_
double g_
double h_
int id_
int pid_
Constructor & Destructor Documentation
HybridNode()
rmp::path_planner::HybridAStarPathPlanner::HybridNode::HybridNode (double x = 0, double y = 0, double t = 0, double g = 0.0, double h = 0.0, int id = 0, int pid = 0, int prim = 0)
Constructor for Hybrid Node class.
Constructor for 3d Node class.
Parameters
x x value
y y value
t
g g value, cost to get to this node
h h value, heuritic cost of this node
id node's id
pid node's parent's id
x x value
y y value
g g value, cost to get to this node
h h value, heuritic cost of this node
id node's id
pid node's parent's id
   : Node(x, y, g, h, id, pid), theta_(t), prim_(prim)
 {
 }
Member Function Documentation
getMotion()
std::vector< HybridAStarPathPlanner::HybridNode > rmp::path_planner::HybridAStarPathPlanner::HybridNode::getMotion () static
Get permissible motion.
Returns
Node vector of permissible motions
 {
   // R, alpha
   double dy[] = { 0, -R * (1 - cos(alpha)), R * (1 - cos(alpha)) };
   double dx[] = { alpha * R, R * sin(alpha), R * sin(alpha) };
   double dt[] = { 0, alpha, -alpha };
   return {
     HybridNode(dx[0], dy[0], dt[0], 0, 0, 0, 0, 0),   HybridNode(dx[1], dy[1], dt[1], 0, 0, 0, 0, 1),
     HybridNode(dx[2], dy[2], dt[2], 0, 0, 0, 0, 2),   HybridNode(-dx[0], dy[0], -dt[0], 0, 0, 0, 0, 3),
     HybridNode(-dx[1], dy[1], -dt[1], 0, 0, 0, 0, 4), HybridNode(-dx[2], dy[2], -dt[2], 0, 0, 0, 0, 5),
   };
 }
References rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::alpha, multi_pub_real_coordinate::dt, and rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::R.
Referenced by rmp::path_planner::HybridAStarPathPlanner::plan().
operator!=()
bool rmp::path_planner::HybridAStarPathPlanner::HybridNode::operator!= (const HybridNode & n) const
Overloading operator != for Node class.
Parameters
n another Node
Returns
true if current node equals node n, else false
 {
   return !operator==(n);
 }
operator+()
HybridAStarPathPlanner::HybridNode rmp::path_planner::HybridAStarPathPlanner::HybridNode::operator+ (const HybridNode & n) const
Overloading operator + for Node class.
Parameters
n another Node
Returns
Node with current node's and input node n's values added
 {
   HybridNode result;
   result.x_ = x_ + n.x_ * cos(theta_) - n.y_ * sin(theta_);
   result.y_ = y_ + n.x_ * sin(theta_) + n.y_ * cos(theta_);
   result.theta_ = rmp::common::math::mod2pi(theta_ + n.theta_);
   result.prim_ = n.prim_;
   // forward driving
   if (prim_ < 3)
   {
     // penalize turning
     if (n.prim_ != prim_)
     {
       // penalize change of direction
       if (n.prim_ > 2)
         result.set_g(g() + n.x_ * kPenaltyTurning * kPenaltyCod);
       else
         result.set_g(g() + n.x_ * kPenaltyTurning);
     }
     else
       result.set_g(g() + n.x_);
   }
   // reverse driving
   else
   {
     // penalize turning and reversing
     if (n.prim_ != prim_)
     {
       // penalize change of direction
       if (n.prim_ < 3)
         result.set_g(g() + n.x_ * kPenaltyTurning * kPenaltyCod * kPenaltyReversing);
       else
         result.set_g(g() + n.x_ * kPenaltyTurning * kPenaltyReversing);
     }
     else
       result.set_g(g() + n.x_ * kPenaltyReversing);
   }
   return result;
 }
References rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::kPenaltyCod, rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::kPenaltyReversing, rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::kPenaltyTurning, rmp::common::math::mod2pi(), prim_, rmp::common::structure::Node< T >::set_g(), theta_, rmp::common::structure::Node< T >::x_, and rmp::common::structure::Node< T >::y_.
operator==()
bool rmp::path_planner::HybridAStarPathPlanner::HybridNode::operator== (const HybridNode & n) const
Overloading operator == for Node class.
Parameters
n another Node
Returns
true if current node equals node n, else false
 {
   return (x_ == n.x_) && (y_ == n.y_) &&
          ((std::abs(theta_ - n.theta_) <= kDeltaHeading) ||
           (std::abs(theta_ - n.theta_) >= (2 * M_PI - kDeltaHeading)));
 }
References rmp::common::math::abs(), rmp::path_planner::anonymous_namespace{hybrid_astar_planner.cpp}::kDeltaHeading, theta_, rmp::common::structure::Node< T >::x_, and rmp::common::structure::Node< T >::y_.
set_theta()
void rmp::path_planner::HybridAStarPathPlanner::HybridNode::set_theta (double theta)
 {
   theta_ = theta;
 }
Referenced by rmp::path_planner::HybridAStarPathPlanner::plan().
theta()
double rmp::path_planner::HybridAStarPathPlanner::HybridNode::theta () const
 {
   return theta_;
 }
Referenced by rmp::path_planner::HybridAStarPathPlanner::dubinsShot(), and rmp::path_planner::HybridAStarPathPlanner::plan().
Member Data Documentation
prim_
int rmp::path_planner::HybridAStarPathPlanner::HybridNode::prim_ private
Referenced by operator+().
theta_
double rmp::path_planner::HybridAStarPathPlanner::HybridNode::theta_ private
Referenced by operator+(), and operator==().
The documentation for this class was generated from the following files:
src/core/path_planner/path_planner/include/path_planner/graph_planner/hybrid_astar_planner.h
src/core/path_planner/path_planner/src/graph_planner/hybrid_astar_planner.cpp