ROS Motion Planning: rmp::path_planner::DStarLitePathPlanner Class Reference
rmp::path_planner::DStarLitePathPlanner Class Reference
Class for objects that plan using the LPA* algorithm.
#include <dstar_lite_planner.h>
Classes
class LNode
Public Member Functions
DStarLitePathPlanner (costmap_2d::Costmap2DROS *costmap_ros)
Construct a new DStarLite object.
~DStarLitePathPlanner ()
void initMap ()
Init map.
void reset ()
Reset the system.
double getH (LNodePtr n1, LNodePtr n2)
Get heuristics between n1 and n2.
double calculateKey (LNodePtr s)
Calculate the key of s.
bool isCollision (LNodePtr n1, LNodePtr n2)
Check if there is collision between n1 and n2.
void getNeighbours (LNodePtr u, std::vector< LNodePtr > &neighbours)
Get neighbour LNodePtrs of nodePtr.
double getCost (LNodePtr n1, LNodePtr n2)
Get the cost between n1 and n2, return INF if collision.
void updateVertex (LNodePtr u)
Update vertex u.
void computeShortestPath ()
Main process of D* lite.
bool extractPath (const LNode &start, const LNode &goal)
Extract path for map.
LNode getState (const LNode &current)
Get the closest Node of the path to current state.
bool plan (const Point3d &start, const Point3d &goal, Points3d &path, Points3d &expand)
D* lite implementation.
Public Member Functions inherited from rmp::path_planner::PathPlanner
PathPlanner (costmap_2d::Costmap2DROS *costmap_ros)
Construct a new Global PathPlanner object.
virtual ~PathPlanner ()=default
Destroy the Global PathPlanner object.
void setFactor (float factor)
Set or reset obstacle factor.
costmap_2d::Costmap2D * getCostMap () const
get the costmap
int getMapSize () const
get the size of costmap
int grid2Index (int x, int y)
Transform from grid map(x, y) to grid index(i)
void index2Grid (int i, int &x, int &y)
Transform from grid index(i) to grid map(x, y)
bool world2Map (double wx, double wy, double &mx, double &my)
Tranform from world map(x, y) to costmap(x, y)
void map2World (double mx, double my, double &wx, double &wy)
Tranform from costmap(x, y) to world map(x, y)
void outlineMap ()
Inflate the boundary of costmap into obstacles to prevent cross planning.
Public Attributes
unsigned char * curr_global_costmap_
unsigned char * last_global_costmap_
LNodePtr ** map_
std::multimap< double, LNodePtr > open_list_
Points3d path_
Points3d expand_
LNode start_
LNode goal_
LNodePtr start_ptr_
LNodePtr goal_ptr_
LNodePtr last_ptr_
double km_
Private Types
using Node = rmp::common::structure::Node< int >
using LNodePtr = LNode *
Additional Inherited Members
Public Types inherited from rmp::path_planner::PathPlanner
using Point2d = rmp::common::geometry::Point2d
using Point3d = rmp::common::geometry::Point3d
using Points2d = rmp::common::geometry::Points2d
using Points3d = rmp::common::geometry::Points3d
Protected Member Functions inherited from rmp::path_planner::PathPlanner
template<typename Node >
std::vector< Node > _convertClosedListToPath (std::unordered_map< int, Node > &closed_list, const Node &start, const Node &goal)
Convert closed list to path.
template<typename Node >
std::vector< Node > _convertBiClosedListToPath (std::unordered_map< int, Node > &f_closed_list, std::unordered_map< int, Node > &b_closed_list, const Node &start, const Node &goal, const Node &boundary)
Protected Attributes inherited from rmp::path_planner::PathPlanner
int map_size_
float factor_
costmap_2d::Costmap2DROS * costmap_ros_
costmap_2d::Costmap2D * costmap_
Detailed Description
Class for objects that plan using the LPA* algorithm.
Member Typedef Documentation
LNodePtr
using rmp::path_planner::DStarLitePathPlanner::LNodePtr = LNode* private
Node
using rmp::path_planner::DStarLitePathPlanner::Node = rmp::common::structure::Node<int> private
Constructor & Destructor Documentation
DStarLitePathPlanner()
rmp::path_planner::DStarLitePathPlanner::DStarLitePathPlanner (costmap_2d::Costmap2DROS * costmap_ros)
Construct a new DStarLite object.
Parameters
costmap the environment for path planning
                                                                               : PathPlanner(costmap_ros)
 {
   curr_global_costmap_ = new unsigned char[map_size_];
   last_global_costmap_ = new unsigned char[map_size_];
   start_.set_x(std::numeric_limits<int>::max());
   start_.set_y(std::numeric_limits<int>::max());
   goal_.set_x(std::numeric_limits<int>::max());
   goal_.set_y(std::numeric_limits<int>::max());
   initMap();
 }
References curr_global_costmap_, goal_, initMap(), last_global_costmap_, rmp::path_planner::PathPlanner::map_size_, rmp::common::structure::Node< T >::set_x(), rmp::common::structure::Node< T >::set_y(), and start_.
~DStarLitePathPlanner()
rmp::path_planner::DStarLitePathPlanner::~DStarLitePathPlanner ()
 {
   delete curr_global_costmap_;
   delete last_global_costmap_;
 }
References curr_global_costmap_, and last_global_costmap_.
Member Function Documentation
calculateKey()
double rmp::path_planner::DStarLitePathPlanner::calculateKey (LNodePtr s)
Calculate the key of s.
Parameters
s LNode pointer
Returns
the key value
 {
   return std::min(s->g(), s->rhs()) + 0.9 * (getH(s, start_ptr_) + km_);
 }
References getH(), km_, key_ctrl::s, and start_ptr_.
Referenced by computeShortestPath(), plan(), and updateVertex().
computeShortestPath()
void rmp::path_planner::DStarLitePathPlanner::computeShortestPath ()
Main process of D* lite.
 {
   while (1)
   {
     if (open_list_.empty())
       break;
     double k_old = open_list_.begin()->first;
     LNodePtr u = open_list_.begin()->second;
     open_list_.erase(open_list_.begin());
     u->setIterator(open_list_.end());
     expand_.emplace_back((*u).x(), (*u).y());
     // start reached
     if (u->key() >= calculateKey(start_ptr_) && start_ptr_->rhs() == start_ptr_->g())
       break;
     // affected by obstacles
     if (k_old < calculateKey(u))
     {
       u->setKey(calculateKey(u));
       u->setIterator(open_list_.insert(std::make_pair(u->key(), u)));
     }
     // Locally over-consistent -> Locally consistent
     else if (u->g() > u->rhs())
     {
       u->set_g(u->rhs());
     }
     // Locally under-consistent -> Locally over-consistent
     else
     {
       u->set_g(std::numeric_limits<double>::max());
       updateVertex(u);
     }
     std::vector<LNodePtr> neigbours;
     getNeighbours(u, neigbours);
     for (LNodePtr s : neigbours)
       updateVertex(s);
   }
 }
References calculateKey(), expand_, rmp::common::structure::Node< T >::g(), getNeighbours(), rmp::path_planner::DStarLitePathPlanner::LNode::key(), open_list_, rmp::path_planner::DStarLitePathPlanner::LNode::rhs(), key_ctrl::s, rmp::common::structure::Node< T >::set_g(), rmp::path_planner::DStarLitePathPlanner::LNode::setIterator(), rmp::path_planner::DStarLitePathPlanner::LNode::setKey(), start_ptr_, and updateVertex().
Referenced by plan().
extractPath()
bool rmp::path_planner::DStarLitePathPlanner::extractPath (const LNode & start, const LNode & goal)
Extract path for map.
Parameters
start start node
goal goal node
Returns
flag true if extract successfully else do not
 {
   Points3d path_temp;
   LNodePtr node_ptr = map_[static_cast<unsigned int>(start.x())][static_cast<unsigned int>(start.y())];
   int count = 0;
   while (node_ptr->x() != goal.x() || node_ptr->y() != goal.y())
   {
     path_temp.emplace_back((*node_ptr).x(), (*node_ptr).y());
     // argmin_{s\in pred(u)}
     std::vector<LNodePtr> neigbours;
     getNeighbours(node_ptr, neigbours);
     double min_cost = std::numeric_limits<double>::max();
     ;
     LNodePtr next_node_ptr;
     for (LNodePtr node_n_ptr : neigbours)
     {
       if (node_n_ptr->g() < min_cost)
       {
         min_cost = node_n_ptr->g();
         next_node_ptr = node_n_ptr;
       }
     }
     node_ptr = next_node_ptr;
     // TODO: it happens to cannnot find a path to start sometimes...
     // use counter to solve it templately
     if (count++ > 1000)
       return false;
   }
   path_ = path_temp;
   return true;
 }
References rmp::common::structure::Node< T >::g(), getNeighbours(), map_, path_, rmp::common::structure::Node< T >::x(), and rmp::common::structure::Node< T >::y().
Referenced by plan().
getCost()
double rmp::path_planner::DStarLitePathPlanner::getCost (LNodePtr n1, LNodePtr n2)
Get the cost between n1 and n2, return INF if collision.
Parameters
n1 LNode pointer of one LNode
n2 LNode pointer of the other LNode
Returns
cost between n1 and n2
 {
   if (isCollision(n1, n2))
     return std::numeric_limits<double>::max();
   return std::hypot(n1->x() - n2->x(), n1->y() - n2->y());
 }
References isCollision(), rmp::common::structure::Node< T >::x(), and rmp::common::structure::Node< T >::y().
Referenced by updateVertex().
getH()
double rmp::path_planner::DStarLitePathPlanner::getH (LNodePtr n1, LNodePtr n2)
Get heuristics between n1 and n2.
Parameters
n1 LNode pointer of on LNode
n2 LNode pointer of the other LNode
Returns
heuristics between n1 and n2
 {
   return std::hypot(n1->x() - n2->x(), n1->y() - n2->y());
 }
References rmp::common::structure::Node< T >::x(), and rmp::common::structure::Node< T >::y().
Referenced by calculateKey(), and plan().
getNeighbours()
void rmp::path_planner::DStarLitePathPlanner::getNeighbours (LNodePtr u, std::vector< LNodePtr > & neighbours)
Get neighbour LNodePtrs of nodePtr.
Parameters
node_ptr DNode to expand
neighbours neigbour LNodePtrs in vector
 {
   int x = u->x(), y = u->y();
   for (int i = -1; i <= 1; i++)
   {
     for (int j = -1; j <= 1; j++)
     {
       if (i == 0 && j == 0)
         continue;
       int x_n = x + i, y_n = y + j;
       if (x_n < 0 || x_n > costmap_->getSizeInCellsX() - 1 || y_n < 0 || y_n > costmap_->getSizeInCellsY() - 1)
         continue;
       LNodePtr neigbour_ptr = map_[x_n][y_n];
       if (isCollision(u, neigbour_ptr))
         continue;
       neighbours.push_back(neigbour_ptr);
     }
   }
 }
References rmp::path_planner::PathPlanner::costmap_, isCollision(), map_, FakeAMCL::x, rmp::common::structure::Node< T >::x(), FakeAMCL::y, and rmp::common::structure::Node< T >::y().
Referenced by computeShortestPath(), extractPath(), plan(), and updateVertex().
getState()
DStarLitePathPlanner::LNode rmp::path_planner::DStarLitePathPlanner::getState (const LNode & current)
Get the closest Node of the path to current state.
Parameters
current current state
Returns
the closest Node
 {
   LNode state(path_[0].x(), path_[0].y());
   double dis_min = std::hypot(state.x() - current.x(), state.y() - current.y());
   int idx_min = 0;
   for (int i = 1; i < path_.size(); i++)
   {
     double dis = std::hypot(path_[i].x() - current.x(), path_[i].y() - current.y());
     if (dis < dis_min)
     {
       dis_min = dis;
       idx_min = i;
     }
   }
   state.set_x(path_[idx_min].x());
   state.set_y(path_[idx_min].y());
   return state;
 }
References path_, rmp::common::structure::Node< T >::set_x(), rmp::common::structure::Node< T >::set_y(), FakeAMCL::x, rmp::common::structure::Node< T >::x(), FakeAMCL::y, and rmp::common::structure::Node< T >::y().
initMap()
void rmp::path_planner::DStarLitePathPlanner::initMap ()
Init map.
 {
   map_ = new LNodePtr*[costmap_->getSizeInCellsX()];
   for (int i = 0; i < costmap_->getSizeInCellsX(); i++)
   {
     map_[i] = new LNodePtr[costmap_->getSizeInCellsY()];
     for (int j = 0; j < costmap_->getSizeInCellsY(); j++)
     {
       map_[i][j] =
           new LNode(i, j, std::numeric_limits<double>::max(), std::numeric_limits<double>::max(), grid2Index(i, j), -1,
                     std::numeric_limits<double>::max(), std::numeric_limits<double>::max());
       map_[i][j]->setIterator(open_list_.end());  // allocate empty memory
     }
   }
 }
References rmp::path_planner::PathPlanner::costmap_, rmp::path_planner::PathPlanner::grid2Index(), map_, open_list_, and rmp::path_planner::DStarLitePathPlanner::LNode::setIterator().
Referenced by DStarLitePathPlanner(), and reset().
isCollision()
bool rmp::path_planner::DStarLitePathPlanner::isCollision (LNodePtr n1, LNodePtr n2)
Check if there is collision between n1 and n2.
Parameters
n1 DNode pointer of one DNode
n2 DNode pointer of the other DNode
Returns
true if collision, else false
 {
   return (curr_global_costmap_[n1->id()] > costmap_2d::LETHAL_OBSTACLE * factor_) ||
          (curr_global_costmap_[n2->id()] > costmap_2d::LETHAL_OBSTACLE * factor_);
 }
References curr_global_costmap_, rmp::path_planner::PathPlanner::factor_, and rmp::common::structure::Node< T >::id().
Referenced by getCost(), and getNeighbours().
plan()
bool rmp::path_planner::DStarLitePathPlanner::plan (const Point3d & start, const Point3d & goal, Points3d & path, Points3d & expand) virtual
D* lite implementation.
Parameters
start start node
goal goal node
expand containing the node been search during the process
Returns
tuple contatining a bool as to whether a path was found, and the path
Implements rmp::path_planner::PathPlanner.
 {
   // update costmap
   memcpy(last_global_costmap_, curr_global_costmap_, map_size_);
   memcpy(curr_global_costmap_, costmap_->getCharMap(), map_size_);
   expand_.clear();
   // new goal set
   if (goal_.x() != goal.x() || goal_.y() != goal.y())
   {
     reset();
     start_.set_x(start.x());
     start_.set_y(start.y());
     start_.set_id(grid2Index(start.x(), start.y()));
     goal_.set_x(goal.x());
     goal_.set_y(goal.y());
     goal_.set_id(grid2Index(goal_.x(), goal_.y()));
     start_ptr_ = map_[static_cast<unsigned int>(start.x())][static_cast<unsigned int>(start.y())];
     goal_ptr_ = map_[static_cast<unsigned int>(goal.x())][static_cast<unsigned int>(goal.y())];
     last_ptr_ = start_ptr_;
     goal_ptr_->setRhs(0.0);
     goal_ptr_->setKey(calculateKey(goal_ptr_));
     goal_ptr_->setIterator(open_list_.insert(std::make_pair(goal_ptr_->key(), goal_ptr_)));
     computeShortestPath();
     extractPath(start_, goal_);
     expand = expand_;
     path = path_;
     return true;
   }
   else
   {
     start_.set_x(start.x());
     start_.set_y(start.y());
     start_.set_id(grid2Index(start.x(), start.y()));
     start_ptr_ = map_[static_cast<unsigned int>(start.x())][static_cast<unsigned int>(start.y())];
     for (int i = -win_size / 2; i < win_size / 2; i++)
     {
       for (int j = -win_size / 2; j < win_size / 2; j++)
       {
         int x_n = start.x() + i, y_n = start.y() + j;
         if (x_n < 0 || x_n > costmap_->getSizeInCellsX() - 1 || y_n < 0 || y_n > costmap_->getSizeInCellsY() - 1)
           continue;
         int idx = grid2Index(x_n, y_n);
         if (curr_global_costmap_[idx] != last_global_costmap_[idx])
         {
           km_ = km_ + getH(last_ptr_, start_ptr_);
           last_ptr_ = start_ptr_;
           LNodePtr u = map_[x_n][y_n];
           std::vector<LNodePtr> neigbours;
           getNeighbours(u, neigbours);
           updateVertex(u);
           for (LNodePtr s : neigbours)
           {
             updateVertex(s);
           }
         }
       }
     }
     computeShortestPath();
     path_.clear();
     extractPath(start_, goal_);
     expand = expand_;
     path = path_;
     return true;
   }
 }
References calculateKey(), computeShortestPath(), rmp::path_planner::PathPlanner::costmap_, curr_global_costmap_, expand_, extractPath(), getH(), getNeighbours(), goal_, goal_ptr_, rmp::path_planner::PathPlanner::grid2Index(), Layer2_RandomPlanner_laser::idx, rmp::path_planner::DStarLitePathPlanner::LNode::key(), km_, last_global_costmap_, last_ptr_, map_, rmp::path_planner::PathPlanner::map_size_, open_list_, path_, reset(), key_ctrl::s, rmp::common::structure::Node< T >::set_id(), rmp::common::structure::Node< T >::set_x(), rmp::common::structure::Node< T >::set_y(), rmp::path_planner::DStarLitePathPlanner::LNode::setIterator(), rmp::path_planner::DStarLitePathPlanner::LNode::setKey(), rmp::path_planner::DStarLitePathPlanner::LNode::setRhs(), start_, start_ptr_, updateVertex(), rmp::path_planner::anonymous_namespace{dstar_lite_planner.cpp}::win_size, rmp::common::structure::Node< T >::x(), rmp::common::geometry::Point3_< T >::x(), rmp::common::structure::Node< T >::y(), and rmp::common::geometry::Point3_< T >::y().
reset()
void rmp::path_planner::DStarLitePathPlanner::reset ()
Reset the system.
 {
   open_list_.clear();
   km_ = 0.0;
   for (int i = 0; i < costmap_->getSizeInCellsX(); i++)
     for (int j = 0; j < costmap_->getSizeInCellsY(); j++)
       delete map_[i][j];
   for (int i = 0; i < costmap_->getSizeInCellsX(); i++)
     delete[] map_[i];
   delete[] map_;
   initMap();
 }
References rmp::path_planner::PathPlanner::costmap_, initMap(), km_, map_, and open_list_.
Referenced by plan().
updateVertex()
void rmp::path_planner::DStarLitePathPlanner::updateVertex (LNodePtr u)
Update vertex u.
Parameters
u LNode pointer to update
 {
   // u != goal
   if (u->x() != goal_.x() || u->y() != goal_.y())
   {
     std::vector<LNodePtr> neigbours;
     getNeighbours(u, neigbours);
     // min_{s\in pred(u)}(g(s) + c(s, u))
     u->setRhs(std::numeric_limits<double>::max());
     for (LNodePtr s : neigbours)
     {
       if (s->g() + getCost(s, u) < u->rhs())
       {
         u->setRhs(s->g() + getCost(s, u));
       }
     }
   }
   // u in openlist, remove u
   if (u->iter() != open_list_.end())
   {
     open_list_.erase(u->iter());
     u->setIterator(open_list_.end());
   }
   // g(u) != rhs(u)
   if (u->g() != u->rhs())
   {
     u->setKey(calculateKey(u));
     u->setIterator(open_list_.insert(std::make_pair(u->key(), u)));
   }
 }
References calculateKey(), rmp::common::structure::Node< T >::g(), getCost(), getNeighbours(), goal_, rmp::path_planner::DStarLitePathPlanner::LNode::iter(), rmp::path_planner::DStarLitePathPlanner::LNode::key(), open_list_, rmp::path_planner::DStarLitePathPlanner::LNode::rhs(), key_ctrl::s, rmp::path_planner::DStarLitePathPlanner::LNode::setIterator(), rmp::path_planner::DStarLitePathPlanner::LNode::setKey(), rmp::path_planner::DStarLitePathPlanner::LNode::setRhs(), rmp::common::structure::Node< T >::x(), and rmp::common::structure::Node< T >::y().
Referenced by computeShortestPath(), and plan().
Member Data Documentation
curr_global_costmap_
unsigned char* rmp::path_planner::DStarLitePathPlanner::curr_global_costmap_
Referenced by DStarLitePathPlanner(), isCollision(), plan(), and ~DStarLitePathPlanner().
expand_
Points3d rmp::path_planner::DStarLitePathPlanner::expand_
Referenced by computeShortestPath(), and plan().
goal_
LNode rmp::path_planner::DStarLitePathPlanner::goal_
Referenced by DStarLitePathPlanner(), plan(), and updateVertex().
goal_ptr_
LNodePtr rmp::path_planner::DStarLitePathPlanner::goal_ptr_
Referenced by plan().
km_
double rmp::path_planner::DStarLitePathPlanner::km_
Referenced by calculateKey(), plan(), and reset().
last_global_costmap_
unsigned char* rmp::path_planner::DStarLitePathPlanner::last_global_costmap_
Referenced by DStarLitePathPlanner(), plan(), and ~DStarLitePathPlanner().
last_ptr_
LNodePtr rmp::path_planner::DStarLitePathPlanner::last_ptr_
Referenced by plan().
map_
LNodePtr** rmp::path_planner::DStarLitePathPlanner::map_
Referenced by extractPath(), getNeighbours(), initMap(), plan(), and reset().
open_list_
std::multimap<double, LNodePtr> rmp::path_planner::DStarLitePathPlanner::open_list_
Referenced by computeShortestPath(), initMap(), plan(), reset(), and updateVertex().
path_
Points3d rmp::path_planner::DStarLitePathPlanner::path_
Referenced by extractPath(), getState(), and plan().
start_
LNode rmp::path_planner::DStarLitePathPlanner::start_
Referenced by DStarLitePathPlanner(), and plan().
start_ptr_
LNodePtr rmp::path_planner::DStarLitePathPlanner::start_ptr_
Referenced by calculateKey(), computeShortestPath(), and plan().
The documentation for this class was generated from the following files:
src/core/path_planner/path_planner/include/path_planner/graph_planner/dstar_lite_planner.h
src/core/path_planner/path_planner/src/graph_planner/dstar_lite_planner.cpp