ROS Motion Planning: rviz_generate Namespace Reference
rviz_generate Namespace Reference
Variables
dir_path = os.path.dirname(os.path.realpath(__file__))
robot_num = int(sys.argv[1])
r = RVizConfig("cache", os.path.split(os.path.realpath(__file__))[0] + "/../../../sim_env/rviz/")
d = Displays()
topic
name
color
size
alpha
meta_robot = Displays()
parameter
tf_prefix
None
Variable Documentation
alpha
rviz_generate.alpha
color
rviz_generate.color
Referenced by rmp::common::util::Visualizer._colorInit(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >.getColorFromId(), rmp::common::util::Visualizer.publishLines2d(), and rmp::common::util::Visualizer.publishPoints().
d
rviz_generate.d = Displays()
Referenced by rmp::common::geometry::BezierCurve.getControlPoints(), rmp::common::geometry::BSplineCurve.paramSelection(), rmp::controller::Controller.prune(), rmp::common::geometry::CubicSplineCurve.run(), and rmp::common::geometry::CubicSplineCurve.spline().
dir_path
rviz_generate.dir_path = os.path.dirname(os.path.realpath(__file__))
meta_robot
rviz_generate.meta_robot = Displays()
name
rviz_generate.name
Referenced by rmp::controller::APFController.APFController(), rmp::controller::DWA.DWA(), rmp::controller::ORCAController.initialize(), rmp::controller::DWAController.initialize(), rmp::controller::StaticController.initialize(), rmp::controller::RPPController.initialize(), rmp::path_planner::PathPlannerNode.initialize(), rmp::controller::MPCController.initialize(), rmp::controller::LQRController.initialize(), rmp::controller::PIDController.initialize(), rmp::controller::APFController.initialize(), gazebo::PedestrianSFMPlugin.Load(), rmp::controller::LQRController.LQRController(), rmp::controller::MPCController.MPCController(), rmp::controller::ORCAController.ORCAController(), rmp::path_planner::PathPlannerNode.PathPlannerNode(), rmp::controller::PIDController.PIDController(), spencer_tracking_rviz_plugin::RosPackagePathResourceLoadingListener.resourceLoading(), rmp::controller::RPPController.RPPController(), and rmp::controller::StaticController.StaticController().
None
rviz_generate.None
parameter
rviz_generate.parameter
r
rviz_generate.r = RVizConfig("cache", os.path.split(os.path.realpath(__file__))[0] + "/../../../sim_env/rviz/")
Referenced by rmp::common::util::Visualizer._colorInit(), rmp::common::geometry::BezierCurve._comb(), rmp::common::math.circleSegmentIntersection(), spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >.getColorFromId(), rmp::path_planner::ACOPathPlanner.initializePositions(), rmp::path_planner::GAPathPlanner.initializePositions(), rmp::path_planner::PSOPathPlanner.initializePositions(), RVO::Agent.insertObstacleNeighbor(), rmp::common::geometry::ReedsSheppCurve.LRL(), rmp::common::geometry::ReedsSheppCurve.LRSL(), rmp::common::geometry::ReedsSheppCurve.LRSLR(), rmp::common::geometry::ReedsSheppCurve.LSR(), DynamicVoronoi.prune(), and rmp::common::geometry::ReedsSheppCurve.R().
robot_num
rviz_generate.robot_num = int(sys.argv[1])
size
rviz_generate.size
tf_prefix
rviz_generate.tf_prefix
topic
rviz_generate.topic