ROS Motion Planning: multi_pub_car_velocity Namespace Reference
multi_pub_car_velocity Namespace Reference
Variables
car_name = sys.argv[1]
v_puber = rospy.Publisher(f'/{car_name}/cmd_vel', Twist, queue_size = 1)
twist = Twist()
rate = rospy.Rate(2)
tuple sign = (random.random()>0.5)
interval = random.randint(1,20)
x
z
Variable Documentation
car_name
multi_pub_car_velocity.car_name = sys.argv[1]
interval
multi_pub_car_velocity.interval = random.randint(1,20)
rate
multi_pub_car_velocity.rate = rospy.Rate(2)
sign
tuple multi_pub_car_velocity.sign = (random.random()>0.5)
twist
multi_pub_car_velocity.twist = Twist()
Referenced by spencer_tracking_rviz_plugin::PersonDisplayCommon< spencer_tracking_msgs::TrackedGroups >.getVelocityVector(), rmp::controller::ORCAController.initState(), and rmp::controller::ORCAController.updateState().
v_puber
multi_pub_car_velocity.v_puber = rospy.Publisher(f'/{car_name}/cmd_vel', Twist, queue_size = 1)
x
multi_pub_car_velocity.x
z
multi_pub_car_velocity.z