ROS Motion Planning: Layer2_RandomPlanner_laser Namespace Reference
Layer2_RandomPlanner_laser Namespace Reference
Classes
class Gazebo_Layer2_Random_Planner
class LaserThread
Variables
idx = int(sys.argv[1])
planner = Gazebo_Layer2_Random_Planner(idx)
rate = rospy.Rate(25)
Variable Documentation
idx
Layer2_RandomPlanner_laser.idx = int(sys.argv[1])
Referenced by rmp::path_planner::ACOPathPlanner.initializePositions(), rmp::path_planner::DStarPathPlanner.plan(), rmp::path_planner::LPAStarPathPlanner.plan(), rmp::path_planner::DStarLitePathPlanner.plan(), rmp::path_planner::GAPathPlanner.selection(), and rmp::common::geometry::CubicSplineCurve.spline().
planner
Layer2_RandomPlanner_laser.planner = Gazebo_Layer2_Random_Planner(idx)
rate
Layer2_RandomPlanner_laser.rate = rospy.Rate(25)