ROS Motion Planning: key_ctrl Namespace Reference
key_ctrl Namespace Reference
Functions
def on_press (key)
def on_release (key)
Variables
anonymous
env = Gazebo_fml_robot_env()
keys = pygame.key.get_pressed()
a
s = env.step(a)
int ACTION = 7
listener = Listener(on_press=on_press, on_release=on_release)
win
collide
Function Documentation
on_press()
def key_ctrl.on_press (key)
 def on_press(key):
     global ACTION
     #key control
     if key == Key.up: ACTION = 2
     elif key == Key.down: ACTION = 5
     elif key == Key.left: ACTION = 0
     elif key == Key.right: ACTION = 4
     else: ACTION = 7  # Stop
on_release()
def key_ctrl.on_release (key)
 def on_release(key):
     global ACTION
     ACTION = 7  # Stop
Variable Documentation
a
key_ctrl.a
Referenced by rmp::common::util::Visualizer._colorInit(), rmp::path_planner::InformedRRTStarPathPlanner._transform(), spencer_tracking_rviz_plugin::ProbabilityEllipseCovarianceVisual.calc_ellipse(), spencer_tracking_rviz_plugin::ProbabilityEllipseCovarianceVisual.calc_prob_elli_95(), spencer_tracking_rviz_plugin::ProbabilityEllipseCovarianceVisual.calc_prob_elli_99(), rmp::controller::Controller.getLookAheadPoint(), rmp::path_planner::ACOPathPlanner.initializePositions(), rmp::path_planner::GAPathPlanner.initializePositions(), rmp::path_planner::PSOPathPlanner.initializePositions(), rmp::path_planner::ACOPathPlanner.plan(), rmp::path_planner::GAPathPlanner.plan(), rmp::path_planner::PSOPathPlanner.plan(), rmp::path_planner::GAPathPlanner.selection(), and rmp::common::geometry::CubicSplineCurve.spline().
ACTION
int key_ctrl.ACTION = 7
anonymous
key_ctrl.anonymous
collide
key_ctrl.collide
env
key_ctrl.env = Gazebo_fml_robot_env()
keys
key_ctrl.keys = pygame.key.get_pressed()
Referenced by plugins.maps_generate.MapsGenerator.__init__(), plugins.pedestrians_generate.PedGenerator.__init__(), plugins.obstacles_generate.ObstacleGenerator.__init__(), plugins.maps_generate.MapsGenerator.plugin(), and plugins.robot_generate.RobotGenerator.writeRobotsXml().
listener
key_ctrl.listener = Listener(on_press=on_press, on_release=on_release)
s
key_ctrl.s = env.step(a)
Referenced by rmp::controller::RPPController._applyApproachConstraint(), rmp::controller::LQRController._lqrControl(), rmp::controller::MPCController._mpcControl(), rmp::controller::PIDController._pidControl(), rmp::path_planner::DStarLitePathPlanner.calculateKey(), rmp::path_planner::LPAStarPathPlanner.calculateKey(), RVO::Agent.computeNewVelocity(), rmp::path_planner::LPAStarPathPlanner.computeShortestPath(), rmp::path_planner::DStarLitePathPlanner.computeShortestPath(), rmp::controller::LQRController.computeVelocityCommands(), rmp::controller::MPCController.computeVelocityCommands(), rmp::controller::PIDController.computeVelocityCommands(), rmp::common::geometry::BSplineCurve.paramSelection(), rmp::path_planner::LPAStarPathPlanner.plan(), rmp::path_planner::DStarLitePathPlanner.plan(), rmp::common::geometry::CubicSplineCurve.run(), rmp::path_planner::LPAStarPathPlanner.updateVertex(), and rmp::path_planner::DStarLitePathPlanner.updateVertex().
win
key_ctrl.win