ROS Motion Planning: rmp::common::math Namespace Reference
rmp::common::math Namespace Reference
Functions
template<typename T >
T abs (T val)
template<typename T >
bool less (T query, T target)
template<typename T >
bool large (T query, T target)
template<typename T >
bool equal (T query, T target)
double mod2pi (double theta)
Perform modulus operation on 2π.
double pi2pi (double theta)
Truncate the angle to the interval of -π to π.
template<typename T >
T Square (const T value)
Compute squared value.
template<typename T >
T clamp (const T value, T bound1, T bound2)
Clamp a value between two bounds. If the value goes beyond the bounds, return one of the bounds, otherwise, return the original value.
double crossProd (const rmp::common::geometry::Vec2d &start_point, const rmp::common::geometry::Vec2d &end_point_1, const rmp::common::geometry::Vec2d &end_point_2)
Cross product between two 2-D vectors from the common start point, and end at two other points.
double innerProd (const rmp::common::geometry::Vec2d &start_point, const rmp::common::geometry::Vec2d &end_point_1, const rmp::common::geometry::Vec2d &end_point_2)
Inner product between two 2-D vectors from the common start point, and end at two other points.
double crossProd (const double x0, const double y0, const double x1, const double y1)
Cross product between two vectors. One vector is formed by 1st and 2nd parameters of the function. The other vector is formed by 3rd and 4th parameters of the function.
double innerProd (const double x0, const double y0, const double x1, const double y1)
Inner product between two vectors. One vector is formed by 1st and 2nd parameters of the function. The other vector is formed by 3rd and 4th parameters of the function.
std::vector< std::pair< double, double > > circleSegmentIntersection (const std::pair< double, double > &p1, const std::pair< double, double > &p2, double r)
Formula for intersection of a line with a circle centered at the origin.
Variables
constexpr double kMathEpsilon = 1e-10
Function Documentation
abs()
template<typename T > T rmp::common::math::abs (T val)
 {
   return val < 0 ? -val : val;
 }
Referenced by rmp::path_planner::QuickInformedRRTStarPathPlanner::_generateRandomNode(), rmp::controller::LQRController::_lqrControl(), DynamicVoronoi::checkVoro(), equal(), large(), less(), rmp::common::geometry::Vec2d::operator/(), rmp::common::geometry::Vec2d::operator/=(), rmp::path_planner::HybridAStarPathPlanner::HybridNode::operator==(), rmp::common::geometry::Vec2d::operator==(), and spencer_tracking_rviz_plugin::ProbabilityEllipseCovarianceVisual::setMeanCovariance().
circleSegmentIntersection()
std::vector< std::pair< double, double > > rmp::common::math::circleSegmentIntersection (const std::pair< double, double > & p1, const std::pair< double, double > & p2, double r)
Formula for intersection of a line with a circle centered at the origin.
Note
https://mathworld.wolfram.com/Circle-LineIntersection.html
Parameters
p1/p2 the two point in the segment
r the radius of circle centered at the origin
Returns
points the intersection points of a line and the circle
 {
   std::vector<std::pair<double, double>> i_points;
   double x1 = p1.first;
   double x2 = p2.first;
   double y1 = p1.second;
   double y2 = p2.second;
   double dx = x2 - x1;
   double dy = y2 - y1;
   double dr2 = dx * dx + dy * dy;
   double D = x1 * y2 - x2 * y1;
   // the first element is the point within segment
   double d1 = x1 * x1 + y1 * y1;
   double d2 = x2 * x2 + y2 * y2;
   double dd = d2 - d1;
   double delta = std::sqrt(r * r * dr2 - D * D);
   if (delta >= 0)
   {
     if (delta == 0)
       i_points.emplace_back(D * dy / dr2, -D * dx / dr2);
     else
     {
       i_points.emplace_back((D * dy + std::copysign(1.0, dd) * dx * delta) / dr2,
                             (-D * dx + std::copysign(1.0, dd) * dy * delta) / dr2);
       i_points.emplace_back((D * dy - std::copysign(1.0, dd) * dx * delta) / dr2,
                             (-D * dx - std::copysign(1.0, dd) * dy * delta) / dr2);
     }
   }
   return i_points;
 }
References rviz_generate::r.
Referenced by rmp::controller::Controller::getLookAheadPoint().
clamp()
template<typename T > T rmp::common::math::clamp (const T value, T bound1, T bound2)
Clamp a value between two bounds. If the value goes beyond the bounds, return one of the bounds, otherwise, return the original value.
Parameters
value The original value to be clamped.
bound1 One bound to clamp the value.
bound2 The other bound to clamp the value.
Returns
The clamped value.
 {
   if (bound1 > bound2)
   {
     std::swap(bound1, bound2);
   }
   if (value < bound1)
   {
     return bound1;
   }
   else if (value > bound2)
   {
     return bound2;
   }
   return value;
 }
Referenced by rmp::controller::Controller::getLookAheadDistance(), gazebo::PedestrianSFMPlugin::handleObstacles(), rmp::path_planner::PSOPathPlanner::updateParticlePosition(), and rmp::path_planner::PSOPathPlanner::updateParticleVelocity().
crossProd() [1/2]
double rmp::common::math::crossProd (const double x0, const double y0, const double x1, const double y1)
Cross product between two vectors. One vector is formed by 1st and 2nd parameters of the function. The other vector is formed by 3rd and 4th parameters of the function.
Parameters
x0 The x coordinate of the first vector.
y0 The y coordinate of the first vector.
x1 The x coordinate of the second vector.
y1 The y coordinate of the second vector.
Returns
The cross product result.
 {
   return x0 * y1 - x1 * y0;
 }
crossProd() [2/2]
double rmp::common::math::crossProd (const rmp::common::geometry::Vec2d & start_point, const rmp::common::geometry::Vec2d & end_point_1, const rmp::common::geometry::Vec2d & end_point_2)
Cross product between two 2-D vectors from the common start point, and end at two other points.
Parameters
start_point The common start point of two vectors in 2-D.
end_point_1 The end point of the first vector.
end_point_2 The end point of the second vector.
Returns
The cross product result.
 {
   return (end_point_1 - start_point).crossProd(end_point_2 - start_point);
 }
equal()
template<typename T > bool rmp::common::math::equal (T query, T target)
 {
   return abs(query - target) <= kMathEpsilon ? true : false;
 }
References abs(), and kMathEpsilon.
innerProd() [1/2]
double rmp::common::math::innerProd (const double x0, const double y0, const double x1, const double y1)
Inner product between two vectors. One vector is formed by 1st and 2nd parameters of the function. The other vector is formed by 3rd and 4th parameters of the function.
Parameters
x0 The x coordinate of the first vector.
y0 The y coordinate of the first vector.
x1 The x coordinate of the second vector.
y1 The y coordinate of the second vector.
Returns
The inner product result.
 {
   return x0 * x1 + y0 * y1;
 }
innerProd() [2/2]
double rmp::common::math::innerProd (const rmp::common::geometry::Vec2d & start_point, const rmp::common::geometry::Vec2d & end_point_1, const rmp::common::geometry::Vec2d & end_point_2)
Inner product between two 2-D vectors from the common start point, and end at two other points.
Parameters
start_point The common start point of two vectors in 2-D.
end_point_1 The end point of the first vector.
end_point_2 The end point of the second vector.
Returns
The inner product result.
 {
   return (end_point_1 - start_point).innerProd(end_point_2 - start_point);
 }
large()
template<typename T > bool rmp::common::math::large (T query, T target)
 {
   return query > target && abs(query - target) > kMathEpsilon ? true : false;
 }
References abs(), and kMathEpsilon.
less()
template<typename T > bool rmp::common::math::less (T query, T target)
 {
   return query < target && abs(query - target) > kMathEpsilon ? true : false;
 }
References abs(), and kMathEpsilon.
mod2pi()
double rmp::common::math::mod2pi (double theta)
Perform modulus operation on 2π.
Parameters
theta the angle to modulu
Returns
theta_m the angle after modulus operator
 {
   return theta - 2.0 * M_PI * floor(theta / M_PI / 2.0);
 }
Referenced by rmp::common::geometry::DubinsCurve::generation(), rmp::common::geometry::DubinsCurve::LRL(), rmp::common::geometry::DubinsCurve::LSL(), rmp::common::geometry::DubinsCurve::LSR(), rmp::path_planner::HybridAStarPathPlanner::HybridNode::operator+(), rmp::common::geometry::DubinsCurve::RLR(), rmp::common::geometry::DubinsCurve::RSL(), and rmp::common::geometry::DubinsCurve::RSR().
pi2pi()
double rmp::common::math::pi2pi (double theta)
Truncate the angle to the interval of -π to π.
Parameters
theta the angle to truncate
Returns
theta_t the truncated angle
 {
   while (theta > M_PI)
     theta -= 2.0 * M_PI;
   while (theta < -M_PI)
     theta += 2.0 * M_PI;
   return theta;
 }
Referenced by rmp::common::geometry::ReedsSheppCurve::M().
Square()
template<typename T > T rmp::common::math::Square (const T value) inline
Compute squared value.
Parameters
value The target value to get its squared value.
Returns
Squared value of the input value.
 {
   return value * value;
 }
Variable Documentation
kMathEpsilon
constexpr double rmp::common::math::kMathEpsilon = 1e-10 constexpr
Referenced by equal(), large(), and less().