PIDController:
  # offset of transform from world(x,y) to grid map(x,y)
  convert_offset: 0.0

  # goal reached tolerance
  goal_dist_tolerance: 0.2
  rotate_tolerance: 0.5

  # linear velocity
  max_v: 0.5
  min_v: 0.0
  max_v_inc: 0.5

  # angular velocity
  max_w: 2
  min_w: 0.0
  max_w_inc: 2

  # pid controller params
  k_v_p: 1.00
  k_v_i: 0.10
  k_v_d: 0.10

  k_w_p: 1.00
  k_w_i: 0.10
  k_w_d: 0.10

  k_theta: 0.7

  k: 2.5 # 源代码中的1.0无法达到0.5m/s的最大线速度
  l: 0.2

  # lookahead
  lookahead_time: 0.5
  min_lookahead_dist: 0.3
  #max_lookahead_dist: 0.9
  max_lookahead_dist: 2

  # frame id
  base_frame: base_link
  map_frame: map
